### ISSUE TITLE
intersect set operator type error (MiniZinc 2)

### ISSUE THREAD

**Issue by markmanser** [MiniZinc/libminizinc#10]
MiniZinc 2 currently raises the following type error when I use the intersect set operator and then compile using mzn2fzn.exe on Windows 7:

`MiniZinc: type error: type error in operator application for 'intersect'. No matching operator found with left-hand side type 'int' and right-hand side type 'set of int'.`

Changing the operator from intersect to union results in the minizinc to flatzinc conversion executing without error.

Also, note that the minizinc tutorial at:
http://www.minizinc.org/downloads/doc-latest/minizinc-tute.pdf
lists the intersection operator as "inter" instead of "intersect".

**Comment by guidotack** [comment]
Can you please post some sample code?  The error message looks like you're trying to intersect an integer with a set, but if changing the operation to union fixes the issue there might be something else that's wrong.

**Comment by markmanser** [comment]
Sure:  Changing the `intersect` to any of (`union`, `symdiff`, `diff`) in the following code results in the flatzinc model being compiled without an error being raised.

```
par int: UB = 31;
par int: qty = 12;

array[1..qty, 1..qty, 1..UB] of var int: my_3D_array;
array[1..UB] of set of int: array_of_indices = [1..i | i in 1..UB];

constraint
forall (layer_index in 1..UB)
(
  forall (row_index in 1..qty)
  (
    forall (col_index in (1..qty intersect array_of_indices[row_index]))
    (
      (my_3D_array[row_index, col_index, layer_index] == 1)
    )
  )
);

solve satisfy;
```

**Comment by guidotack** [comment]
Right, that's due to a strange definition of operator precedence in the MiniZinc specification.  We will change the specification and the parser for the next release.
