### ISSUE TITLE
How to compile .mzn model file

### ISSUE THREAD

**Issue by nguyenhailong** [MiniZinc/libminizinc#101]
Hi,

How can I compile .mzn model files?
I found this information; however it doesn't work: http://www.minizinc.org/g12_www/zinc/doc-2.0/html/zinc-manual.html

```
[label=simple_p.zinc]
int: p;
var 1..10: x;
constraint x >= p;
solve minimize x;
output [ "x is ", show(x), "" ];
The value for p is in a data file:

[label=data.dzn]
p = 4;
Now we compile only the model and then call the executable with the data file as an argument:

$ zinc simple_p.zinc
$ simple_p data.dzn
```

The command zinc is invalid. Can you please advise on this?

Thank you.

**Comment by scand1sk** [comment]
.mzn is MiniZinc, not Zinc. You should refer to the MiniZinc tutorial available on page http://www.minizinc.org/resources.html
