### ISSUE TITLE
Unsatisfiable program becomes satisfiable after adding a constraint (Gecode solver)

### ISSUE THREAD

**Issue by gschenner** [MiniZinc/libminizinc#104]
Hi,
The attached program has a strange behavior. 
It is unsatisfiable running it with the bundled Gecode solver of the MiniZinc IDE 2.0.13, and satisfiable running it with the G12 fd solver.

When the solution is added as a constraint to the program:
`constraint
nrofobjects = array1d(1..17 ,[0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0]);`
the program becomes satisfiable for Gecode, i.e. an unsatisfiable program becomes satisfiable after adding a constraint.

Any ideas, how this can be explained?

[oocsp_racks_bug.zip](https://github.com/MiniZinc/libminizinc/files/272413/oocsp_racks_bug.zip)

**Comment by guidotack** [comment]
That was a bug in Gecode. It will be fixed in the next release. Thanks!
