### ISSUE TITLE
"cannot determine bounds" when using abs function outside solve statement

### ISSUE THREAD

**Issue by Zero3** [MiniZinc/libminizinc#106]
I have a model with a set of of float decision variables (`itemValues`) that runs fine with the following solve statement:

```
solve minimize sum (i in Items) (abs(itemPrices[i] - itemValues[i]));
```

However, it breaks if I move the sum into its own variable, which should have no effect as far as I am concerned:

```
var float: diffs = sum (i in Items) (abs(itemPrices[i] - itemValues[i]));
solve minimize diffs;
```

If I remove the `abs` function, both work fine. So it appears to be a bug/limitation related to this function.

The error thrown is:

```
MiniZinc: evaluation error: 
<.mzn file path>:23:
  in variable declaration for 'diffs'
  in call 'sum'
  in array comprehension expression
    with i = 1
  in call 'abs'
C:\Program Files (x86)\MiniZinc IDE (bundled)/share/minizinc/std/builtins.mzn:321:
  in if-then-else expression
C:\Program Files (x86)\MiniZinc IDE (bundled)/share/minizinc/std/builtins.mzn:322:
  in let expression
  in call 'max'
  in call 'ub'
  cannot determine bounds
```

**Comment by a1880** [comment]
Looking at the implementation of abs() in builtins.mzn, it appears that abs() requires the argument to be bounded, i.e. there has to be an upper and a lower bound for the argument imposed by some constraints.
