### ISSUE TITLE
g12mip solver statistics

### ISSUE THREAD

**Issue by layeghy** [MiniZinc/libminizinc#107]
The -s flag does not work for mzn-g12mip. In fact it does not generate any statistics at output.
With MiniZinc IDE I used the -S (not -s) flag and it generates this output:

[User time: +0.020s, 0.020s, Real time: +0.026s, 0.026s, C Stack: 1.165k, Trail: 0.000k,
# GCs: 3, Heap used since last GC: 2137.703k, Total used: 6856.000k]

[User time: +0.000s, 0.020s, Real time: +0.000s, 0.026s, C Stack: 1.368k, Trail: 0.000k,
# GCs: 3, Heap used since last GC: 2386.922k, Total used: 6856.000k]

[User time: +0.020s, 0.040s, Real time: +0.020s, 0.046s, C Stack: 1.368k, Trail: 0.000k,
# GCs: 5, Heap used since last GC: 1058.375k, Total used: 9144.000k]

[User time: +0.040s, 0.080s, Real time: +0.055s, 0.101s, C Stack: 1.899k, Trail: 0.000k,
# GCs: 7, Heap used since last GC: 8005.953k, Total used: 49896.000k]

[0 choice points explored.]

that I cannot understand. But -S flag does not even work with the command line version.
Thanks,
Siamak

**Comment by guidotack** [comment]
g12mip is deprecated, you can use mzn-cbc now which supports -s.

**Comment by layeghy** [comment]
Thanks a lot
