### ISSUE TITLE
Ide crash on variable redef

### ISSUE THREAD

**Issue by jdupl123** [MiniZinc/libminizinc#108]
solve maximize 20*B + 30 * T;
constraint 140 * B + 200 * T <= 40 * 200 * 140;

var 0..6000: B;
var 0..4000: B;

output ["B=\(B) T=\(T)\n"]

ide crashes with redefinition of B. windows 32 bit

**Comment by a1880** [comment]
My 64bit IDE 2.0.14 does not crash.

I only get a proper error message:

`MiniZinc: type error: identifier B already defined`

**Comment by jdupl123** [comment]
Tested on different laptop windows 10. with 2.0.14 32 bit ide. Crash occurs when the editing area is clicked after running a script with variable redifinition.

**Comment by guidotack** [comment]
Thanks for the report. I can reproduce a crash but I'm not sure it's the one you saw. For me it only crashes if I enter the the model into a fresh file, save it, then run it. I've been able to track that down, there will be a workaround in the next version of the IDE.

**Comment by jdupl123** [comment]
@guidotack seems like the correct issue to me. :)

**Comment by guidotack** [comment]
Great! It will still take a few weeks to release the next version. A workaround for the time being is to create a file using another text editor, then load it into the IDE (instead of saving from a fresh file inside the IDE).
