### ISSUE TITLE
fails when range is used

### ISSUE THREAD

**Issue by RobertAditazz** [MiniZinc/libminizinc#11]
Hello,

I have a simple testcase.  The expected answer to the "floors" variable is 205.
Perhaps I am doing something wrong.  Thanks for your help.

% ----------------------------

include "globals.mzn";

int: target = 20500 ;

% this works:
var int: floors ;

% But if I replace the above with a range,
% it fails and outputs floors = 1
% but works in minizinc 1.6
% var 1..1000: floors ;

var int: actual = (floors * 10 * 10) ;
constraint actual >= target ;
solve minimize floors ;

output [
    "target: ",  show(target), "\n",
    "actual: ",  show(actual), "\n",
    "floors: ",  show(floors), "\n",
    "\n"
] ;

**Comment by guidotack** [comment]
Thanks for the bug report. This problem is already fixed in the develop branch and the fix will be part of the 2.0.2 release next week.

**Comment by RobertAditazz** [comment]
Thanks.  I'll build from develop branch in the meantime.

**Comment by RobertAditazz** [comment]
The develop branch fixed this problem, and others.  Would it be possible to release windows binaries?  I have linux and mac compilers, but no MSVS.  Thanks.
