### ISSUE TITLE
mzn2fzn erronously reports "model inconsistency detected"

### ISSUE THREAD

**Issue by gablin** [MiniZinc/libminizinc#110]
For the attached model, mzn2fzn in version 2.0.13 manages to flatten the model without errors. However, in version 2.0.14, mzn2fzn reports:

```
Warning: model inconsistency detected
  full-model.mzn:365:
  in call 'forall'
  in array comprehension expression
    with m = 2
  full-model.mzn:366:
    with o = 5
  full-model.mzn:370:
  in call 'table'
```

Using git bisect I managed to track down the bug as being located in commit ebdfa44e6f5a0a369b53045b05fbe9c6063bb511.

[model.zip](https://github.com/MiniZinc/libminizinc/files/429952/model.zip)

**Comment by guidotack** [comment]
I just had a look, are you sure that the declaration of your Alt function is correct?  It constrains the result to be in the set allBlocksInFunction (that's the change in ebdfa44, before that change the compiler actually ignored the declared return type). So Alt(5) returns 9, which is outside of allBlocksInFunction, which leads to the inconsistency.

**Comment by gablin** [comment]
It's Mats Carlsson who wrote it, so I'll check with him.

Gabriel Hjort Blindell
Doctoral Student @ KTH

**Comment by gablin** [comment]
Have been in contact with Mats, and it was indeed a mistake in our model. Thanks for pointing that out. This issue can now be closed.
