### ISSUE TITLE
Unable to execute file: c:\...MiniZinc IDE(bundled)MiniZincIDE.exe CreateProcess failed; code 193. %1 is not a valid Win32 appliation."

### ISSUE THREAD

**Issue by manythanks** [MiniZinc/libminizinc#111]
I installed MiniZincIDE 2.0.14 for Windows 32 bit from here 
https://www.minizinc.org/
in 2 minilaptops that have windows xp service pack 3, win32., but when I double click to open it I have 
this error message.
Unable to execute file: c:\...MiniZinc IDE(bundled)MiniZincIDE.exe
CreateProcess failed; code 193.
%1 is not a valid Win32 appliation."
I have seen http://www.computerhope.com/issues/ch000726.htm
Does anyone have  any other idea what should I do?

**Comment by a1880** [comment]
I am running 2.0.14 on Windows 7 32 bit without this problem.
It might be that the GUI library Qt5 for Windows is not compiled with XP support.
Look here: http://doc.qt.io/qt-5/windows-issues.html

To get a checksum of the executable, I used

C:\.....\MiniZinc_IDE_2.0.14>certutil -hashfile minizincide.exe MD5

The resulting MD5 hash:

5d 30 fa cc f6 d0 1d 58 06 44 d2 12 5a c2 95 6e

**Comment by guidotack** [comment]
We don't build or test on Windows XP machines, and we use pre-compiled Qt5 libraries. At this point, we don't have the resources to add another build environment, so unfortunately we can't support Windows XP.
