### ISSUE TITLE
logistic constraints with continuous variables

### ISSUE THREAD

**Issue by gqy1005** [MiniZinc/libminizinc#115]
The following simple programs involving continuous variables in logistic constraints are said to be unsatisfiable:

array[1..5] of var 0.0..1.0: C;
var bool: alpha;
constraint 
        if alpha then C[1] + C[2] + C[3] + C[4] + C[5] == 1.0 else true endif;
solve satisfy;

and:

var 0.0..1.0: x;
var 0.0..1.0: y;
constraint 
        if x > 0 then y == 0 else y > 0 endif;
solve maximize x + y;

**Comment by guidotack** [comment]
Can you please let me know which version of MiniZinc and which solver you were using? Both models seem to work with MiniZinc 2.0.13 and Gecode.

**Comment by gqy1005** [comment]
@guidotack I'm using MiniZinc IDE (bundled) on Windows 7 Professional and the version is 2.0.14. The first model does not work for G12 MIP solver and the second one does not work for Gecode (bundled) solver.
I attached the screenshot of the first model with G12 MIP:
![test_g12mip](https://cloud.githubusercontent.com/assets/11623229/18978392/5a6ad704-86f5-11e6-87e8-44f3110a6718.JPG)

**Comment by zhangwei0402** [comment]
Sometimes I get unsatisfiable but I don't know why. For example, 
constraint
forall(k in 1..V, i in 1..N, j in 1..N)(
        DepartureTimes[k,i] + weight[i, j] - DepartureTimes[k, j] <= (1 - x[k, i, j]) * 1000000000
);
DepartureTimes is from -1.0 to 86400.0 and weight is integer from 0 to 99999. If I use 100,000,000 instead of 1,000,000,000, sometimes I get unsatisfiable.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
