### ISSUE TITLE
Flattening of global_cardinality_low_up does not work properly

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#124]
I played around with the gbac instance reduced_UD10-gbac (from the MiniZinc benchmark library) and I think I observed a bug in flattening.

gbac is a course scheduling problem; there are curricula and, for each curriculum and for each time slot (period), the number of scheduled courses is bounded:

```
%course load of all periods for each curriculum
constraint forall(c in curricula)(
  global_cardinality_low_up_closed(
      [period_of[i]|i in courses_of[c]],
      [i|i in periods],
      [min_courses |i in periods],
      [max_courses |i in periods])
);
```

global_cardinality_low_up_closed is based on global_cardinality_low_up which is defined as follows in the MiniZinc standard library:

```
predicate global_cardinality_low_up(array[int] of var int: x,
                                    array[int] of int: cover,
                                    array[int] of int: lbound,
                                    array[int] of int: ubound) =
     forall(i in index_set(cover)) (
         sum(j in index_set(x)) ( bool2int(x[j] = cover[i]) )
         in lbound[i]..ubound[i]
     );
```

Now let's focus on course 43 which is part of the second-to-last curriculum, namely {42, 43, 44, 7}. According to the definition of global_cardinality_low_up, flattening should result in two constraints for each period (out of 1 to 6), namely a int_eq_reif and a bool2int constraint, and this is what mzn2fzn 1.6 gives us for course 43:

```
constraint int_eq_reif(period_of[43], 1, BOOL____00645) :: defines_var(BOOL____00645);
constraint int_eq_reif(period_of[43], 2, BOOL____00652) :: defines_var(BOOL____00652);
constraint int_eq_reif(period_of[43], 3, BOOL____00659) :: defines_var(BOOL____00659);
constraint int_eq_reif(period_of[43], 4, BOOL____00666) :: defines_var(BOOL____00666);
constraint int_eq_reif(period_of[43], 5, BOOL____00673) :: defines_var(BOOL____00673);
constraint int_eq_reif(period_of[43], 6, BOOL____00680) :: defines_var(BOOL____00680);

constraint bool2int(BOOL____00645, INT____00646) :: defines_var(INT____00646);
constraint bool2int(BOOL____00652, INT____00653) :: defines_var(INT____00653);
constraint bool2int(BOOL____00659, INT____00660) :: defines_var(INT____00660);
constraint bool2int(BOOL____00666, INT____00667) :: defines_var(INT____00667);
constraint bool2int(BOOL____00673, INT____00674) :: defines_var(INT____00674);
constraint bool2int(BOOL____00680, INT____00681) :: defines_var(INT____00681);
```

mzn2fzn 2.0.14, however, does not produce these constraints for course 43.

To reproduce, I suggest to simplify the problem by removing all but the course load constraints.

In the output of mzn2fzn 2.0.14, period_of[43] is called X_INTRODUCED_42. It gets declared but stays unconstrained.

(In total, more than 200 constraints are missing.)

**Comment by guidotack** [comment]
Does it actually produce incorrect solutions?  To me it looks like 1.6 and 2.0.14 in fact produce the same solutions.

I only traced variable BOOL____00645 through the code generated by 1.6, and it is linked to INT____00646, which then occurs in a linear constraint

    constraint int_lin_eq([-1, 1, 1, 1, 1], [INT____00649, INT____00228, INT____00644, INT____00646, INT____00648], 0) :: defines_var(INT____00649);

The domain of INT____00649 is 0..4 (and all elements of the sum are 0..1). That's why 2.0.14 removes INT____00649 (since it's not actually constraining anything), which in turn makes INT____00646 unconstrained and unused, which in turn removes the bool2int constraints. As far as I can see, this is just a correct optimisation.

**Comment by informarte** [comment]
Ok, thanks for this explanation, and sorry for raising this issue but I was not aware that mzn2fzn implements entailment checking for FlatZinc builtins. Is there a document that describes the optimizations implemented by libminizinc? And is there a way to disable these optimizations? (According to the command-line help, --no-optimize is dead). For example, disabling optimizations could be useful when developing a decomposition for a user-defined constraint.

**Comment by guidotack** [comment]
The command line option --no-optimize still works, but it only switches off the optimisations that are done in a separate step after the main compilation (which would be the kind your are describing).  We have no document that describes all the optimisations, but the main ones are common subexpression elimination, aggregation of linear and boolean expressions, constant folding, and removal of "free" variables and constraints (this is only done for a few built-in constraints).
