### ISSUE TITLE
MIP solver not finding all solutions

### ISSUE THREAD

**Issue by spakin** [MiniZinc/libminizinc#127]
I encountered a case in which the MIP solver isn't finding all solutions to a problem.  Consider the following model, which should be minimized at {0,0,0}, {0,1,0}, {1,0,0}, and {1,1,1} (an AND relationship):
```MiniZinc
var 0..1: q1;
var 0..1: q2;
var 0..1: q3;

var 0..1: a12;
constraint a12 >= q1 + q2 - 1;
constraint a12 <= q1;
constraint a12 <= q2;

var 0..1: a13;
constraint a13 >= q1 + q3 - 1;
constraint a13 <= q1;
constraint a13 <= q3;

var 0..1: a23;
constraint a23 >= q2 + q3 - 1;
constraint a23 <= q2;
constraint a23 <= q3;

var int: energy =
   3 * q3 +
   1 * a12 +
  -2 * a13 +
  -2 * a23;

solve minimize energy;

%constraint energy = 0;
%solve satisfy;

output [
  "Energy = ", show(energy), "\n\n",
  "A = ", show(q1), "\n",
  "B = ", show(q2), "\n",
  "Y = ", show(q3), "\n"
]
```

I ran the above to find the minimum value of the `energy` variable:
```bash
$ minizinc -b mip mip-find-all.mzn 
Energy = 0

A = 1
B = 0
Y = 0
----------
==========
```
So far, so good.  I then commented out the `solve minimize energy` line, un-commented the following two lines, and re-ran `minizinc`:
```bash
$ minizinc -a -b mip mip-find-all.mzn 
Energy = 0

A = 0
B = 0
Y = 0
----------
==========
```
What happened to the remaining solutions?  Shouldn't the MIP solver find them?

Thanks,
— Scott

**Comment by guidotack** [comment]
Hi,
not all backends support all options, in particular enumerating all solutions is not supported by the MIP backends at the moment.

**Comment by spakin** [comment]
I see; thanks.  Would it be possible for the backend (or something) to issue an error message so newbies like me can distinguish between "not supported" and "I'm doing something stupid"?

**Comment by ccoffrin** [comment]
I am inclined to agree with Scott, if there is no way to pass on the "all solutions" directive to the underling solver it would be helpful to throw a warning that this is being omitted.

Another option would be to simulate "all solutions" by adding cuts to the model, which simply block all the solutions found thus far.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
