### ISSUE TITLE
regular constraint with incorrect arguments crashes computer

### ISSUE THREAD

**Issue by pafnucy** [MiniZinc/libminizinc#134]
Using regular constraint with inappropriate arguments crashes computer (Ubuntu 16.04, G12 MiniZinc evaluation driver, version 2.0.2). mzn-gecode that calls script below makes computer totally unresponsive, with only option of hard reboot. An assert preventing above problems would help a lot.

```
array[1..2] of var 1..2: x;

include "regular.mzn";
constraint regular(x, 2, 3, [|1,1|1,1|], 2, 1..2);  % incorrect, no crash
% constraint regular(x, 3, 2, [|1,1|1,1|], 2, 1..2);  % crash
% constraint regular(x, 3, 3, [|1,1|1,1|], 2, 1..2);  % crash

solve satisfy; ```

By the way, couldn't 2nd and 3rd argument of regular be inferenced from automaton table?

edit:  unhidden first line

**Comment by guidotack** [comment]
Can you please post a full model to reproduce the crash (this one lacks a definition of x).
The computer becoming unresponsive is usually a sign of extensive memory usage. The likely cause is if your variables don't have tight bounds (and the search therefore needs to go very deep).
The definition of regular could indeed be simplified in the way you suggest. We may consider that for a future release.

**Comment by pafnucy** [comment]
Edited code. I didn't notice triple backtick hiding code directly behind it.

**Comment by guidotack** [comment]
Thanks. That's a bug in Gecode, not MiniZinc (I didn't read your post carefully, I thought that the MiniZinc compiler had crashed). I'll close it here, it'll be fixed in a future Gecode release.
