### ISSUE TITLE
sum for opt float

### ISSUE THREAD

**Issue by silgon** [MiniZinc/libminizinc#137]
I was trying to do a sum with opt floats and then I got the following message:

    MiniZinc: type error: no function or predicate with this signature found: `sum(array[int] of var opt float)'

Then, looking at the source code, at stdlib.mzn I found the function sum with the opt option but it exists only for integers:

```
function var int: sum(array[int] of var opt int: x) =
  sum (i in index_set(x)) (let { var int: dx = deopt(x[i]) } in if occurs(x[i]) then dx else 0 endif);
```

Do you have any workaround for this?

**Comment by guidotack** [comment]
Optional float vars are not supported at this point. The compiler should emit a better error message, I'll see if we can do something for the next release.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
