### ISSUE TITLE
var set producing segfault/bad result/good result depending on solver

### ISSUE THREAD

**Issue by pafnucy** [MiniZinc/libminizinc#139]
Summing over variable set works with gecode, segfaults chuffed, makes g12lazy produce bad result and lots of warnings and good result for g12fd, even though with some warnings. Main error message is "set variables not supported in line no. 17", which gives user some idea on what the problem is, this line number is related to flatzinc file.

Issue1: error caught in later stage, after creating .fzn file, while it could happen earlier
Issue2: (solver specific/mzn2fzn translation, so this might be off-topic here) inconsistent behavior of solvers, no matter gecode vs chuffed, g12lazy gives bad result

Code of "varset_crash.mzn"
```
array[1..3] of int: val = [2,-1,2];
var 1..3: len;
var int: obj = sum(i in 1..len)(val[i]);  % this makes chuffed segfault
%var int: obj = sum(i in 1..3 where i <= len)(val[i]);  % this works with chuffed
solve maximize obj;
```

GECODE
$ mzn-gecode varset_crash.mzn
len = 3;
----------
==========

CHUFFED
$ mzn-chuffed varset_crash.mzn
Error: LazyGeoff: set variables not supported in line no. 17
Aborted (core dumped)

G12LAZY
$ mzn-g12lazy varset_crash.mzn
varset_crash.fzn:19:
  symbol warning: annotation `maybe_partial' not recognised, ignoring
varset_crash.fzn:19:
  symbol warning: annotation `promise_total' not recognised, ignoring
varset_crash.fzn:20:
  symbol warning: annotation `promise_total' not recognised, ignoring
varset_crash.fzn:21:
  symbol warning: annotation `maybe_partial' not recognised, ignoring
varset_crash.fzn:21:
  symbol warning: annotation `promise_total' not recognised, ignoring
varset_crash.fzn:22:
  symbol warning: annotation `promise_total' not recognised, ignoring
warning: LAZY solver backend: ignoring promise_total/0 annotation.
warning: LAZY solver backend: ignoring maybe_partial/0 annotation.
warning: LAZY solver backend: ignoring promise_total/0 annotation.
warning: LAZY solver backend: ignoring promise_total/0 annotation.
warning: LAZY solver backend: ignoring maybe_partial/0 annotation.
warning: LAZY solver backend: ignoring promise_total/0 annotation.
=====UNSATISFIABLE=====

G12FD
$ mzn-g12fd varset_crash.mzn
varset_crash.fzn:19:
  symbol warning: annotation `maybe_partial' not recognised, ignoring
varset_crash.fzn:19:
  symbol warning: annotation `promise_total' not recognised, ignoring
varset_crash.fzn:20:
  symbol warning: annotation `promise_total' not recognised, ignoring
varset_crash.fzn:21:
  symbol warning: annotation `maybe_partial' not recognised, ignoring
varset_crash.fzn:21:
  symbol warning: annotation `promise_total' not recognised, ignoring
varset_crash.fzn:22:
  symbol warning: annotation `promise_total' not recognised, ignoring
warning: FD solver backend: ignoring promise_total/0 annotation.
warning: FD solver backend: ignoring maybe_partial/0 annotation.
warning: FD solver backend: ignoring promise_total/0 annotation.
warning: FD solver backend: ignoring promise_total/0 annotation.
warning: FD solver backend: ignoring maybe_partial/0 annotation.
warning: FD solver backend: ignoring promise_total/0 annotation.
len = 3;

**Comment by guidotack** [comment]
g12lazy and g12fd are both deprecated and will be removed in a future version of the bundled download. The behaviour of Chuffed is not related to MiniZinc (although the next version of MiniZinc will enable set constraints to be compiled to something that Chuffed can solve).
