### ISSUE TITLE
Suggestion: add pseudo-boolean (bool_lin_*) constraints

### ISSUE THREAD

**Issue by scand1sk** [MiniZinc/libminizinc#14]
A lot of models make use of pseudo-boolean constraints, which are currently implemented with int_lin_\* constraints on boolean variables coerced to Int using `bool2int` function. This generate many useless variables (one 0/1 and one boolean for each actual decision variable), and potentially many constraints (or other specific solver feature) to enforce the coercion.

Maybe this could be improved if native pseudo-boolean constraints were available.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
