### ISSUE TITLE
mzn-gecode missing index set mismatch in diffn resulting in segfault

### ISSUE THREAD

**Issue by pafnucy** [MiniZinc/libminizinc#140]
Calling mzn-gecode on faulty invocation of diffn bypasses type checking and leads to noninformative segfault, while mzn-chuffed, mzn2fzn indentify index set mismatch properly.

**mzn-gecode behavior:**
mzn-gecode segfault.mzn -> Segmentation fault (core dumped)

**correct behavior:**
mzn2fzn segfault.mzn -> Assertion failed: diffn: index set mismatch
mzn-chuffed segfault.mzn -> Assertion failed: diffn: index set mismatch
IDE run with gecode-> `fzn-gecode': error code 1

**segfault.mzn:**
```
include "globals.mzn";
set of int: WORKER = 1..2;
set of int: CARGO = 1..4;
set of int: TIME = 0..30;
array[CARGO] of var TIME: task;
array[CARGO] of var TIME: finished;
array[CARGO] of var WORKER: which;
array[CARGO] of var TIME: total_duration = [finished[s] - task[s] | s in CARGO];
solve minimize max(finished);

constraint diffn(task, which, total_duration, [1 | r in WORKER]);  % problematic line
```

**Comment by Dekker1** [comment]
include "globals.mzn";
set of int: WORKER = 1..2;
set of int: CARGO = 1..4;
set of int: TIME = 0..30;
array[CARGO] of var TIME: task;
array[CARGO] of var TIME: finished;
array[CARGO] of var WORKER: which;
array[CARGO] of var TIME: total_duration = [finished[s] - task[s] | s in CARGO];
solve minimize max(finished);

constraint diffn(task, which, total_duration, [1 | r in WORKER]);  % problematic line
