### ISSUE TITLE
accessing array via function in set operation fails

### ISSUE THREAD

**Issue by angee** [MiniZinc/libminizinc#141]
I stumbled across this bug for solution validation when I retrieve an array using a function, and impose one of its elements to a set operator. Accessing the array via the function works, but imposing the set operator fails. I attached an example that reproduces the error (and shows what works). Note that I did not get this error in version 2.1.2. Thank for looking at it! [array_access_via_function.txt](https://github.com/MiniZinc/libminizinc/files/761643/array_access_via_function.txt)

**Comment by guidotack** [comment]
Not sure where the problem is: the assertion fails for key=2 and i=1 because myArray(2)[1] is 6 (the first element of array2) which is not in mySet.

**Comment by angee** [comment]
oh my, you are right. I derived that example from my actual problem and included that mistake. I also already found out the source of my original problem: from v2.1.3 on, it is no longer possible to write functions like:

`function array[1..4] of int: myArray(int: key) = `
`if key=1 then [1,2,3]`
`elseif key = 2 then [1,2,3,4]`
`else [] endif;`

because the return value of the function varies and is not exactly an array `array[1..4] of int`. Now you have to write `array[int] of int` in the signature, which, in the end, makes more sense anyway :-)
