### ISSUE TITLE
Bug Assertion failed : when run pre-solver in command window 

### ISSUE THREAD

**Issue by MargaridaLobato** [MiniZinc/libminizinc#142]
I installed the pre-solver and test if works with models and files dzn in this repository: https://github.com/jjdekker/MiniZinc-Auto-Tabling-Models. I don't have problems but when I tried run my model I have problems. 
In command window, I have the same error in this two cases: 
**mzn2fzn.exe -G gecode --presolver "C:\Program Files\MiniZinc IDE (bundled)\fzn-gecode" -d dados_20.dzn novomodelo.mzn** 
**mzn2fzn.exe -G gecode --no-presolve -d dados_20.dzn novomodelo.mzn**
# Error: 
Assertion failed: t1enumIds.size() == t2enumIds.size(), file C:\Program Files\MiniZinc IDE (bundled)\libminizinc\lib\flatten.cpp, line 399

**Comment by Dekker1** [comment]
The MiniZinc version used in this branch did not yet include the release version of enumerations, which seems to be causing this problem. The autotabling feature will hopefully be available soon within the releases of MiniZinc, which will solve this problem.
