### ISSUE TITLE
Type (int-enum) mismatch crashes MiniZincIDE

### ISSUE THREAD

**Issue by pafnucy** [MiniZinc/libminizinc#144]
Comparing int with enum crashes IDE. Behavior: execution stops, but run button is inactive, stop button active, crashes after pressing. Kind of similar to [#143](https://github.com/MiniZinc/libminizinc/issues/143)

enum crash crashes both versions: 2.1.3 and 2.1.2
but in 2.1.2 it doesn't crash when we remove output statement

solver independent, Ubuntu 16.04

**IDE error msg:** 
Unknown error while executing the MiniZinc interpreter `fzn-gecode': error code 1

**Output window error:**
MiniZinc: result of evaluation is undefined: array access out of bounds
/tmp/MiniZinc IDE (bundled)-AE3Lu8/poetry_idecrash_enum.ozn:9

**console call error (proper behavior):** 
MiniZinc: result of evaluation is undefined: array access out of bounds
poetry_idecrash_enum.ozn:9

code:

```
int: k=3;
int: l=3;
int: m=3;
set of int: ESSTANZA = 1..k+l;
int: other = 0;
set of int: STANZA = 0..k+l; 
enum KIND = { E, S, O };
array[ESSTANZA] of int: effect = [10,13,14,9,7,6];
int: n = k+l+m;
set of int: POSN = 1..n;
array[ESSTANZA] of var POSN:  place;
array[POSN] of var STANZA: what;     

constraint what[1] != other /\ forall(i in 1..n-1)(what[i] = other /\ what[i+1] = other -> forall(j in i..n)(what[j] = other));
constraint forall(i in ESSTANZA, j in POSN)(place[i] = j <-> what[j] = i);

% source of bug: (erronous) enum "O" instead of 0 in "what[p] = 0"
var int: obj = sum(p in 1..n-1)(if what[p] = O \/ what[p+1] = O then 0 else abs(effect[what[p]] - effect[what[p+1]]) endif);

solve maximize obj;

% 2.1.2: without output, there is no error
output ["obj = \(obj);\nwhat = \(what);\nplace = \(place);\n"];
```

**Comment by pafnucy** [comment]
there seems to be interaction with if-then-else-endif, when removing it, there is no crash.

**Comment by guidotack** [comment]
The crash is fixed now in the develop branch of the IDE repository (will be part of the next release).
