### ISSUE TITLE
solns2out does not free memory while parsing lots of data

### ISSUE THREAD

**Issue by paolodragone** [MiniZinc/libminizinc#145]
Hi!
I am parsing a big solution stream with solns2out but it allocates a lot of memory in the process.
I believe this is not necessary since the single solutions are quite small, so it should be able to free the allocated memory for the solutions as soon as it outputs them.
Cheers.
Paolo

**Comment by paolodragone** [comment]
I just noticed this was already fixed (#36), but it still uses quite a lot of memory.
I'm running it on a ~4GB solution stream and it slowly accumulates more than 4 times as much.

**Comment by guidotack** [comment]
Can you try running solns2out with the --non-unique flag?  That might be the problem here (solns2out by default currently stores all solutions so as to be able to remove duplicates).

**Comment by paolodragone** [comment]
Using the --non-unique flag does not seem to make much of a difference.
If it can help, [here](https://gist.github.com/paolodragone/948a366a0497dc924fe44581b5ac9c81) you can find the model that I have been having this issue with (actually a simplified version which still makes solns2out occupy quite a lot of memory).

**Comment by Wwkr** [comment]
Is there any fix related to the above issue in the recent minizinc version 2.1.7.  ?
