### ISSUE TITLE
Download error: missing dll 

### ISSUE THREAD

**Issue by hsfrey** [MiniZinc/libminizinc#148]
I downloaded the MiniZincIDE-2.1.3-bundled-setup-win64.exe to my win 7 system.

Upon trying to execute the file I got the error message:
api-ms-win-crt-runtime-l1-1-1.dll is missing from my computer

What do I do to correct this problem?

**Comment by a1880** [comment]
Looks like this update is missing: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

**Comment by guidotack** [comment]
Thanks, we will distribute the necessary DLLs with the next release.
