### ISSUE TITLE
compiler: constant folding can be improved

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#149]
I'm working on a project where it's evident from the FlatZinc that the compiler's constant folding is far from optimal, which makes the flattened model bigger than necesssary.  I can work around most of it, at the cost of obfuscating the MiniZinc model. Is this something that you plan to improve?

Here is a small artificial sample illustrating some problems:

    array[1..2] of var bool: sel;
    var 1..3: omatch;
    var {1,33,113,116}: loc;

    constraint
      let {var bool: b} in
      omatch in 3..3 /\
      (omatch=3 <-> sel[1]) /\
      loc in {1,33} /\
      loc in {1,116} /\
      (loc in 1..32 <-> b) /\
      (sel[1] -> b);

    solve satisfy;

becomes:

    var bool: X_INTRODUCED_0:: is_defined_var;
    var bool: X_INTRODUCED_1;
    var 3..3: omatch:: output_var;
    var 1..1: loc:: output_var;
    var bool: X_INTRODUCED_2 ::var_is_introduced :: is_defined_var;
    array [1..2] of var bool: sel:: output_array([1..2]) = [X_INTRODUCED_0,X_INTRODUCED_1];
    constraint bool_clause([X_INTRODUCED_2],[X_INTRODUCED_0]);
    constraint int_eq_reif(omatch,3,X_INTRODUCED_0):: defines_var(X_INTRODUCED_0);
    constraint set_in_reif(1,1..32,X_INTRODUCED_2):: defines_var(X_INTRODUCED_2);
    solve  satisfy;

**Comment by guidotack** [comment]
Thanks for the example, I had seen this before but hadn't had time yet to track it down. I've just pushed a fix that should solve it at least for this type of constant folding.

**Comment by matsc-at-sics-se** [comment]
Great! In fact, I would be happy to test your fix on my full model, where more patterns surface. Can I build your development version myself? Could you send some instructions?


Best,


Mats Carlsson

RISE SICS

https://www.sics.se/people/mats-carlsson

________________________________

**Comment by guidotack** [comment]
It's part of 2.1.4.
