### ISSUE TITLE
Constraint array_float_element not found

### ISSUE THREAD

**Issue by kim0** [MiniZinc/libminizinc#15]
With the following simple traveling salesman model:
https://gist.github.com/kim0/ba480a0f918c41e1a2e9

I get this error when I run it
$ mzn-gecode -a solver-sa.mzn
Error: Registry: Constraint array_float_element not found

**Comment by guidotack** [comment]
Hi,
this is a limitation in the Gecode FlatZinc interface, not in MiniZinc itself.

Cheers,
Guido

**Comment by kim0** [comment]
@guidotack Thanks .. g12mip also yields this error .. Any thoughts ?

MiniZinc: evaluation error:
  cannot determine bounds
