### ISSUE TITLE
compiler: puzzling bool_eq/2 constraints

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#151]
Looking at a FlatZinc file, I see a large number of constraints like:

    constraint bool_eq(X_INTRODUCED_10180,X_INTRODUCED_464);

How come the two variables were not simply aliased instead?  This looks like a useless inflation of the constraint model.

**Comment by guidotack** [comment]
Hm, I think this currently occurs when there are multiple reified expressions that are constrained to be equal - at the point where the compiler unifies variables it can't see yet that the right hand sides of the variables will be turned into relational form later, so it has to add equality constraints. I'll think about how to fix that at least for the var bool case.
