### ISSUE TITLE
Request/Discussion: Using a binary serialization framework for interfacing with a compiled model

### ISSUE THREAD

**Issue by saosebastiao** [MiniZinc/libminizinc#152]
Sorry if this is the wrong place for this (and sorry if something similar already exists...I haven't come across it yet in the docs I've read). 

One of the benefits of Minizinc is that it gives a high level language for modeling a specific problem. But the major drawback is that if you want to productionize a model, you have to either fuss with a bunch of hacky ways of creating data files, passing them to your compiled model, and then waiting for a response. So in practice, that typically means Minizinc is a prototype-only system, and production models need to be rewritten in order to interface with the solver. 

I'd like to propose a way of productionizing models with very low overhead to users. It would involve a mode of compilation that takes the model and datafile parameters, and then creates a schema for a binary serialization protocol, like Cap'n Proto, Protobuf, or Thrift, in addition to compiling the model in a way to receive and respond using that protocol. And if possible, allow for calling the model in process (as a shared library), or as an RPC (allowing the compiled model to function as a remote service).

**Comment by guidotack** [comment]
We're very aware of this, in fact one of the main arguments for developing MiniZinc 2 was to make it accessible as a library from other languages and through APIs. We currently don't define any binary formats, but it should be very easy to implement that on top of the C++ API, which should be finalised and documented within the next six months. In addition, we will have someone working on the compiler itself, so there will be a "byte code" version of the intermediate code at some point, but that could still take 18 months or so.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
