### ISSUE TITLE
JSON-output of two-dimensional arrays seems to group incorrectly.

### ISSUE THREAD

**Issue by einarjohan** [MiniZinc/libminizinc#157]
Using latest HEAD on develop https://github.com/MiniZinc/libminizinc/commit/f90ec5db0f96e2274ae5f2ddc58a55ee3ab30fc8 and a simple model based on experimentation with the sudoku model from the tutorial:

```
array[0..2,0..4] of var int: start;

constraint forall(i in 0..2, j in 0..4) (
    start[i, j] == i * 10 + j
);

solve satisfy;
```

JSON-output yields:
```
{
  "start" : [[0, 1, 2], [3, 4, 10], [11, 12, 13], [14, 20, 21], [22, 23, 24]]
}
----------
```

Which does not match the expected 3x5 size. What I would expect as output is:
```
{
  "start" : [[0, 1, 2, 3, 4], [10, 11, 12, 13, 14], [20, 21, 22, 23, 24]]
}
----------
```

Using the resulting output as input to mzn2fzn yields:
```
MiniZinc: evaluation error:
  sudoku.mzn:1:
  in variable declaration for 'start'
  Index set mismatch
```

**Comment by guidotack** [comment]
Sorry, I pushed too early. Should be fixed now.
