### ISSUE TITLE
JSON as input for 2D-arrays seems to require 1-indexed arrays

### ISSUE THREAD

**Issue by einarjohan** [MiniZinc/libminizinc#158]
Using latest HEAD on develop https://github.com/MiniZinc/libminizinc/commit/f90ec5db0f96e2274ae5f2ddc58a55ee3ab30fc8 I find that 2-dimensional array output using JSON isn't usable as input if the arrays are not 1-indexed. (adapting the simple model used in #157)
```
array[0..2,0..2] of var int: start;

constraint forall(i in 0..2, j in 0..2) (
    start[i, j] == 0
);

solve satisfy;
```

with the following JSON file as data:
```
{
  "start" : [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
}
```

yields:
```
MiniZinc: evaluation error:
  sudoku.mzn:1:
  in variable declaration for 'start'
  Index set mismatch
```

However, if I shift the ranges such that the array is 1-indexed:
```
array[1..3,1..3] of var int: start;

constraint forall(i in 1..3, j in 1..3) (
    start[i, j] == 0
);

solve satisfy;
```
mzn2fzn succeds.

As a curiosity, 2-indexed arrays fail the same way 0-indexed arrays do:
```
array[2..4,2..4] of var int: start;

constraint forall(i in 2..4, j in 2..4) (
    start[i, j] == 0
);

solve satisfy;
```

**Comment by guidotack** [comment]
That's right, index sets that are not 1-based are not supported in JSON input at the moment.

**Comment by Dekker1** [comment]
Recent versions of MiniZinc have automatic coercion of index sets for arrays coming from JSON data.
