### ISSUE TITLE
`minizinc -c` results in `sh: 1: solns2dzn: not found`

### ISSUE THREAD

**Issue by scand1sk** [MiniZinc/libminizinc#16]
For testing, I want to solve some MiniZinc problem, ignoring the "output" section (so that I can reinject the solution into the MiniZinc file to verify it using another solver). It seems that there is no much documentation about the "minizinc" and "flatzinc" commands themselves, I thought the "-c" parameter would do the job, but it seems that it is broken.

**Comment by guidotack** [comment]
I will include solns2dzn from MiniZinc 1.6 in the next release (it still works with 2.0).  We're also working on a tool for verifying solutions (in fact you don't even need another solver, libminizinc itself is enough), but that will take another couple of months or so.
