### ISSUE TITLE
Errors while building minizinc with GECODE_HOME

### ISSUE THREAD

**Issue by paolodragone** [MiniZinc/libminizinc#160]
Hi, I am trying to build libminizinc with the gecode interface and I get some compilation errors.
I am using the latest master version of libminizinc and Gecode 4.4.0.
[Here](https://gist.github.com/paolodragone/a8e36d2787c21c1ac64b74bc7455e667) you can find the compilation errors I am getting.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
