### ISSUE TITLE
How to tune bool_search annotation

### ISSUE THREAD

**Issue by a1880** [MiniZinc/libminizinc#162]
I am trying to solve a satisfiability problem (purely Boolean decision variables) with MiniZinc.

To speed up the search, I experimented with a `bool_search` annotation

```
solve :: bool_search([F[i,j,k] | k in Products, i in ARows, j in ACols ] ++  
                     [G[m,n,k] | k in Products, m in BRows, n in BCols ] ++
                     [D[p,q,k] | k in Products, p in CRows, q in CCols ], 
                     input_order,                                            
                     indomain_split,                                       
                     complete                                                
                     )  satisfy;
```

So far, all my attempts failed. The annotated version always took much longer than the non-annotated default search. I used Gecode as solver back-end.

What happens, if the array of variables supplied to the bool_search() annotation does not contain all decision variables?

Is there any way I could apply the default search but ask the solver to try `false `before `true `variable values (i.e. only change the value selection strategy, but leave the other strategies unchanged)?

**Comment by pafnucy** [comment]
FlatZinc 1.6 spec on indomain_split: "Bisect the variable’s domain, excluding the upper half first". Not 100% sure about this, but I think in this case it means trying 'false' value first. This, accompanied with 'input_order' varchoiceannotation means trying F, G, D in deterministic order, trying false on first try.

**Comment by guidotack** [comment]
For Gecode, you can use int_default_search, bool_default_search etc which are defined in gecode.mzn. So for example you can do

    include "gecode.mzn"
    solve :: bool_default_search(afc_max, indomain_min) satisfy;

If you're using dynamic searches (such as afc, dom_w_deg or similar), you should also try to run Gecode with restarts, by adding a couple of flags to the command line options of fzn-gecode, e.g.

    -restart luby -nogoods true

or

    -restart geometric -nogoods true

Cheers,
Guido

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
