### ISSUE TITLE
Unexpected compilation error related to string variables

### ISSUE THREAD

**Issue by broesdecat** [MiniZinc/libminizinc#163]
Hi,

When executing the below specification in the IDE 2.1.4, a compilation error is given which I was not expecting. It seems specifically related to the use of strings; if I replace them replaced by integers, the specification behaves as expected.
Is there some restriction on strings I am overlooking or is this a bug?

```
set of int: classes = 1..1;
array[classes] of string: fieldName = ["a"];
set of int: instances = 1..2;
array[instances] of var classes: classOf;
  
constraint forall(i in instances)(
    if(fieldName[classOf[i]]="a") then true else false endif
);
solve satisfy;
```

Compilation error: 
```
  in if-then-else expression
  in binary '=' operator expression
  in array access
  cannot find matching declaration
```

Thanks!
Broes

**Comment by guidotack** [comment]
String variables are not supported natively in MiniZinc (accessing an array of strings with a var int would require a var string result). We've written a paper on string variables but it's not yet part of the released version of MiniZinc.

**Comment by broesdecat** [comment]
Thanks for the info. Then I'll replace all my strings with some integer mapping (and try not to make it completely unreadable :) ).
Any ETA on a version supporting them?

Thx,
Broes

**Comment by Dekker1** [comment]
I'm afraid no ETA has been set for string variables at this point. We'll try to keep you updated though. In the meantime I'll close this issue.
