### ISSUE TITLE
Bug: missing compilation error on unsupported constraint

### ISSUE THREAD

**Issue by broesdecat** [MiniZinc/libminizinc#164]
Hi,

When running the below model with the bundled CBC interface in IDE 2.1.4, an incorrect solution is returned, instead of giving the expected error that float_times is not supported by the interface.

```
var -10.0..10.0: x;
var -10.0..10.0: y;

constraint x*y < 10;

solve satisfy;
```

Solution x=10.0, y=10.0 is returned.
Replacing < with <= does result in a float_times compilation error.

Best,
Broes

**Comment by guidotack** [comment]
This seems to be fixed in 2.1.5.
