### ISSUE TITLE
symbol error: `int_pow' undeclared

### ISSUE THREAD

**Issue by Hi-Angel** [MiniZinc/libminizinc#168]
E.g. this works fine:

	λ cat test.mzn 
	var 1..1: i;
	constraint i*i = 1;
	output ["\(i)"];
	solve satisfy;
	λ minizinc /tmp/test.mzn
	1
	----------

However this *(semantically the same)* results in the error:

	λ cat test.mzn
	var 1..1: i;
	constraint pow(i,2) = 1;
	output ["\(i)"];
	solve satisfy;
	λ minizinc /tmp/test.mzn
	/tmp/test.fzn:2:
	  symbol error: `int_pow' undeclared

OS: Archlinux x86_64
minizinc version: 2.0.2

FTR: found while solving the first exercise in this course https://www.coursera.org/learn/basic-modeling

**Comment by borisalmonacid** [comment]
This bug is specifically for the solvers G12 Lazy and G12 fd (Minizinc 2.1.6)

_In Minizinc IDE_
Compiling test.mzn
Running test.mzn
/var/folders/8c/_pzthwjd1bs6mv14kx7n50p40000gn/T/MiniZinc IDE (bundled)-RE56v2/test.fzn:2:
  symbol error: `int_pow' undeclared
Finished in 47msec

_In console_
➜  0 mzn-g12fd test.mzn
test.fzn:2:
  symbol error: `int_pow' undeclared
➜  0 mzn-g12lazy test.mzn
test.fzn:2:
  symbol error: `int_pow' undeclared

**Comment by schutta** [comment]
The predicate int_pow/3 is not supported by G12/FD and G12/LazyFD. However, to get both solvers working with the function int_pow/2 following redefinition for int_pow/3 can be added to the solvers redefinition file `redefinitions.mzn` in their library, if I am not wrong.
```
predicate int_pow(var int: x, var int: y, var int: r) = ( 
    if lb(y) < 0 then
        let { 
            var bool: b = y < 0;
            var 0..ub(y): y_prime;
            array[dom(x), dom(y_prime)] of int: x2y = 
                array2d(
                    dom(x), dom(y_prime), 
                    [ pow(cx, cy) | cx in dom(x), cy in dom(y_prime) ]
                );  
        } in (
            % Negative case of the power
            (b -> (r = x /\ y_prime = 0 /\ (x = 1 \/ x = -1)))
            % Non-negative case of the power
        /\  (not(b) -> (y = y_prime /\ r = x2y[x, y_prime]))
        )   
    else
        let {
            array[dom(x), dom(y)] of int: x2y =
                array2d(dom(x), dom(y), [ pow(x, y) | x in dom(x), y in dom(y) ])
        } in
        r = x2y[x,y]
    endif
);
```
Note that the array created is of the size `dom(x) * dom(y)` which might be prohibitive for large domains. However, the redefinition can also be defined by a recursion over the power variable `y`.
```
predicate int_pow(var int: x, var int: y, var int: r) = (
    let {
        array[dom(y)] of var int: x2y = array1d(dom(y),
            [int_pow_aux(x, cy) | cy in dom(y)]);
        constraint (y < 0 -> (x = 1 \/ x = -1));
    } in r = x2y[y]
);

function var int: int_pow_aux(var int: x, int: y) =
    if y < 0 \/ y = 1 then
        % Note that this only correct in the combination with the constraint (y < 0 -> (x = 1 \/ x = -1)) for a negative power
        x
    elseif y = 0 then
        1
    else
        x * int_pow_aux(x, y - 1) 
    endif;
```

Tested on MiniZinc 2.1.6.
