### ISSUE TITLE
Allow creation of arrays of unknown length

### ISSUE THREAD

**Issue by skosch** [MiniZinc/libminizinc#17]
Hi,
there was some ambition in 2011 to allow the declaration of arrays without a length, if they are initialized with constant data (see page 8 of http://www.minizinc.org/workshop2011/report.pdf). To my knowledge this still isn't possible—if that's so, are there efforts underway to allow this?

Cheers :)

**Comment by guidotack** [comment]
That's been possible since MiniZinc 1.6 actually ;-)  You can write something like

`array[int] of int: x = [ i | i in 1..10];`

or even

`array[int] of var int: x = [ y[i] | i in 1..10];`

Cheers,
Guido

**Comment by skosch** [comment]
Ahh ... awesome! Thanks.
