### ISSUE TITLE
Heterogeneous capacitated vehicle routing problem 

### ISSUE THREAD

**Issue by Bjack1** [MiniZinc/libminizinc#171]
Hi everyone I'm working on a project and Im using Minizinc for the first time and I need your help, I was trying to solve a cvrp and I have this error" MiniZinc: type error: no function or predicate with this signature found: `forall(array[int] of var int)' "

Here is my program 

include "globals.mzn";
% Noeuds 
int : N;
% Capacité de véhicules 
int : M;
array [1..M] of int : Capacity;
% Demande de chaque ville 
array [1..N] of int : Demand;
% Distances entre noeuds 
array [1..N+1, 1..N+1] of int : Distance;
% Coût camion / km
array [1..M] of int : CCamion;
%Variable de décision 
array [0..N, 0..N, 1..M] of var 0..1 : X;
%Variable de décision supplémentaire
array [1..N] of var 0..Capacity[M] : Y;

% Contraintes
constraint 
  forall(j in 1..N) (
    sum(i in 0..N, k in 1..M)(X[i, j, k])=1
                    );
constraint
  forall(k in 1..M, p in 1..M)(
    (sum(i in 1..N)(X[i, p, k]))-(sum(j in 0..N)(X[p, j, k]))
                    );  
constraint 
  forall(k in 1..M)(
    sum(j in 1..N)(X[0, j, k]) <= M[k]
                    );                                        
constraint 
  forall(j in 1..N)(
    sum(i in 0..N)(Y[i, j])-sum(i in 0..N)(Y[j, i])=Demand[j]
                    );
constraint
  forall(i in 0..N, j in 0..N, k in 1..M)(
    Demand[j]*X[i, j, k] <= Y[i, j] 
                );
constraint
   forall(i in 0..N, j in 0..N, k in 1..M)(      
   Y[i, j] <= (Capacity[k]-Demand[i] * X[i, j, k])
                     );
var int : objective = sum(i in 0..N, j in 0..N, k in 1..M) (Distance[i+1, j+1] * X[i, j, k] * CCamion[k] );                          
solve 
    :: int_search(Y ++ [X[i, j, k] | i in 1..N, j in 1..N, k in 1..M],
        first_fail, indomain_min, complete) 
    minimize objective;

output [
    "X = ", show(X), "\n",
    "objective = ", show(objective),"\n"
];

and my data :

N = 12;
M=9;
Capacity = [12,12,12,12,22,22,22,22,22];
Demand = [10,12,9,6,7,8,15,12,10,13,10,13];
CCamion= [5,5,5,5,7,7,7,7,7]

Distance = [| 0, 34, 488, 315, 215, 245, 265, 592, 1109, 270, 118, 535, 380
            | 34, 0, 468, 338, 240, 222, 242, 615, 1085, 294, 141, 536, 404
            | 488, 468, 0, 798, 701, 450, 259, 1077, 644, 756, 602, 673, 865
            | 315, 338, 798, 0, 343, 477, 574, 719, 1418, 398, 207, 662, 507
            | 215, 240, 701, 343, 0, 303, 475, 385,	1318, 64, 145, 326, 173
            | 245, 222, 450, 477, 303, 0, 191, 679, 1070, 358, 280, 359, 467
            | 265, 242, 259, 574, 475, 191, 0, 853, 871, 533, 379, 496, 642
            | 592, 615, 1077, 719, 385, 679, 853, 0, 1695, 331, 522, 534, 233
            | 1109, 1085, 644, 1418, 1318, 1070, 871, 1695, 0, 1377, 1223, 1312, 1486
            | 270, 294, 756, 398, 64, 358, 533, 331, 1377, 0, 201, 341, 119 
            | 118, 141, 602, 207, 145, 280, 379, 522, 1223, 201, 0, 464, 310
            | 535, 536, 673, 662, 326, 359, 496, 534, 1312, 341, 464, 0, 432
            | 380, 404, 865, 507, 173, 467, 642, 233, 1486, 119, 310, 432,0
            |];

**Comment by a1880** [comment]
The following constraint is probably not correct:

```
constraint
forall(k in 1..M, p in 1..M)(
(sum(i in 1..N)(X[i, p, k]))-(sum(j in 0..N)(X[p, j, k]))
);
```

The inner difference of sums lacks some relational operator like "> 0".

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
