### ISSUE TITLE
fresh installation crashes

### ISSUE THREAD

**Issue by riemaxi** [MiniZinc/libminizinc#173]
I just installed a fresh copy ... followed all the instructions and when I run a model ... any model ... I get:
MiniZinc: internal error: Error occurred when executing FZN solver with command "flatzinc /tmp/fznfilehQJFIo.fzn

This is my model. 
I believe the syntax is correct, because I introduced a mistake on purpose (on another model) and the parser complained.

% solve inequation
var 0..4: x;
var 0..4: y;

constraint x + y <= 6;

solve satisfy;

output ["x = ", show(x), "\n", "y = ", show(y)];

**Comment by guidotack** [comment]
When installing from sources, you need to also install a flatzinc solver before you can use the mzn-fzn tool.
