### ISSUE TITLE
Flattening large, linear input files takes a long time

### ISSUE THREAD

**Issue by skosch** [MiniZinc/libminizinc#174]
I often experience that the flattening of my input takes (easily) 10 times as long as the search itself.

This isn't a bug per se, but it can certainly feel frustrating. A few `foralls` – just basic linear inequalities, nothing complex – unrolled over a few big matrices of input data, and everything grinds to a halt. Right now I'm dealing with a .fzn that takes a few minutes to generate and weighs in at ~100MB, for a problem that ends up taking CBC mere seconds to solve.

I completely understand that FlatZinc is what it is, but do you have some tips for users like myself, or any ideas you guys have in the pipeline that may improve the situation in the future?

**Comment by guidotack** [comment]
There's a few flaws in how arrays and floats are handled internally that slow down the compilation at the moment. We'll be looking into this over the next few months. It would be great if you could share some concrete examples (email me at guido.tack@monash.edu), just for me to check if it's related to the known issues or something else.

**Comment by skosch** [comment]
Will do as soon as I can, thanks Guido!

**Comment by tstumm** [comment]
Is there any update on this? I'm currently dealing with quite large sparse matrices (2200x2200). Flattening takes literally ages.

**Comment by lalithsuresh** [comment]
+1. We're running into scenarios where flattening/compilation easily takes up more than 90% of the overall runtime.

@guidotack : happy to share examples if you'd like to work on it.

**Comment by guidotack** [comment]
There's no special support for large spare matrices. We're aware that flattening can be very slow in certain circumstances. If you have examples, please do share them (best via email), perhaps there are some simple things that can be done to get at least some speed-up.
