### ISSUE TITLE
CMAKE_OSX_DEPLOYMENT_TARGET pinned at 10.7

### ISSUE THREAD

**Issue by dunn** [MiniZinc/libminizinc#18]
Is MiniZinc unsupported on newer versions of OSX, or can this be changed to detect the SDK version?

**Comment by guidotack** [comment]
That's ok, the deployment target is different from the SDK (you can deploy for 10.7 with a 10.10 SDK), but the declaration was in the wrong place in the CMAKE file. It's fixed now in the develop branch.
Cheers,
Guido

**Comment by dunn** [comment]
That did the trick, thanks!
