### ISSUE TITLE
error in running minizinc through cmd (windows) :Error: constraint not found: bool_clause

### ISSUE THREAD

**Issue by mastajvidi** [MiniZinc/libminizinc#182]
Hi, 
I run my model through IDE and everything is working perfectly fine (solver: COIN-or CBC).
For some data files, the IDE shows me some intermediate solutions as well as the optimal solution. 
I tried to run the same models using cmd, It is ok for models with one ultimate solution. However, when I run the models and IDE gave me some intermediate solutions, I get this error:
Error: constraint not found: bool_clause

So for example for one data file, the IDE result is :
NumRES = array3d(1..1,1..2 ,1..3 ,[0, 1, 0, 0, 0, 0]);%
----------
NumRES = array3d(1..1,1..2 ,1..3 ,[0, 0, 0, 0, 0, 0]);%
----------
==========
Finished in 4s 713msec
 but in the CMD when I  have mzn-cbs mymodel.mzn
I get the above mentioned **error**

However for another datafile with this results in IDE:

NumRES = array3d(1..1,1..2 ,1..3 ,[0, 0, 0, 0, 0, 0]);%
----------
==========
Finished in 57msec

I get the exact same result using cmd.

Whats wrong here and how can I only get the last (optimal) solution?
Thanks,

**Comment by Dekker1** [comment]
Hello mastajvidi,

Although you are using a specialised version of the MiniZinc compiler, you currently still need to choose the MiniZinc library which has to be used to compile the model. For CBC the IDE would use the "linear" library, which redefines the `bool_clause` predicate.

You can select a library with the `-G` flag. The command you should use would thus be:
`mzn-cbc -G linear mymodel.mzn`.

I assume this solves your problem and will thus close this issue. If your problem persists, then feel free to comment below.
