### ISSUE TITLE
G12/fd + JaCoP: incorrect set_le / set_lt implementation

### ISSUE THREAD

**Issue by PatrickTrentin88** [MiniZinc/libminizinc#185]
The [FlatZinc 1.6 specification][1], reports:

> - a ⊆ b v min(a△b) ∈ a
>
>         set_le(var set of int: a, var set of int: b)
> 
> - a ⊂ b v min(a△b) ∈ a
>
>         set_lt(var set of int: a, var set of int: b)

However, the following snippet of `fzn` code:

    var set of 1..10: a ::output_var = {8};
    var set of 1..10: b ::output_var = {7, 8, 9};
    
    constraint set_le(a, b);

    solve  satisfy;

results in the following output:

    ~$ flatzinc test.fzn 
    =====UNSATISFIABLE=====
    % test.fzn:4: warning: model inconsistency detected before search.

Clearly, it holds that `a ⊆ b` since `{8} ⊆ {7, 8, 9}`.

Therefore, the formula should be satisfiable.

Why is it not?

-- 

**EDIT:**

- `fzn-gecode` reports `sat`
- `JaCoP` reports `unsat`

I am using *MiniZinc 2.1.5* distribution.

  [1]: http://www.minizinc.org/downloads/doc-1.6/flatzinc-spec.pdf

**Comment by Dekker1** [comment]
The correct answer should adhere to the specifications and would in this case be satisfiable.

The `flatzinc` binary solves the problems using the `g12-fd` solver, which apparently contains a bug in one of it's propagators. The solver itself is not developed by the MiniZinc team and I'm actually not sure if it's still actively developed. I'll try to notify the responsible people of the problem.

Note that in any case `fzn-gecode` is more modern solver that's used broadly within the MiniZinc team. It is likely to perform better.

**Comment by PatrickTrentin88** [comment]
Hi, 
**Krzysztof Kuchcinski** recently opened a discussion in the [MiniZinc Forum](http://www.minizinc.org/forum.html?place=topic%2Fminizinc%2FFYb8TGsaASQ%2Fdiscussion) which I think it's related to this issue.

He mentions that the following code example 

```
var set of 1..2: a ::output_var = {1, 2};
var set of 1..1: b ::output_var = {1};

constraint set_lt(a, b);

solve  satisfy;
```

should be satisfiable, since `min(a△b) = min({1, 2} △ {1}) = min({2}) = 2 ∈ a = { 1, 2}`.

However, all of the following tools report **unsat**:
- flatzinc
- fzn-gecode
- JaCoP

When I was working on this for OptiMathSAT, I wrote among in my notes that `flatzinc` seems to also require both `a \ b` and `b \ a` to be different from the empty set, but this requirement does not appear in the FlatZinc 1.6 specification.

**Comment by PatrickTrentin88** [comment]
The following code sample:

```
var set of 1..2: a ::output_var;
var set of 1..2: b ::output_var;

constraint set_le(a, b);
constraint set_subset_reif(a, b, false);

solve  satisfy;
```
In which I explicitly block any solution coming from the part `a ⊆ b` being `true`, has the following solutions according to `flatzinc` and `JaCoP`:

```
~$ java -Xmx2G -cp "${PATH_JACOP}" org.jacop.fz.Fz2jacop -a t.fzn 
a = {1, 2};
b = {2};
----------
a = {1};
b = {2};
----------
==========

~$ flatzinc -a t.fzn 
a = {1, 2};
b = {2};
----------
a = {1};
b = {2};
----------
==========
```

but only the following solution according to `fzn-gecode`:

```
~$ fzn-gecode -a t.fzn 
a = 2..2;
b = 1..1;
----------
==========
```
**Observations:**

- both `flatzinc` and `JaCoP` don't report as satisfiable the solution proposed by **Krzysztof Kuchcinski**, which however should be compliant with the [FlatZinc 1.6 specification](http://www.minizinc.org/downloads/doc-1.6/flatzinc-spec.pdf).

- I can't make any sense of the solution proposed by `fzn-gecode`!

**Comment by PatrickTrentin88** [comment]
I read [here](http://www.minizinc.org/forum.html?place=topic%2Fminizinc%2FFYb8TGsaASQ%2Fdiscussion) the [FlatZinc 1.6 specification](http://www.minizinc.org/downloads/doc-1.6/flatzinc-spec.pdf) is wrong and that a lexicographic total ordering is expected, so I will be implementing that in `OptiMathSAT` now.

I'll leave here the following code sample:

```
var set of 1..3: x1 ::output_var;
var set of 1..3: x2 ::output_var;
var set of 1..3: x3 ::output_var;
var set of 1..3: x4 ::output_var;
var set of 1..3: x5 ::output_var;
var set of 1..3: x6 ::output_var;
var set of 1..3: x7 ::output_var;
var set of 1..3: x8 ::output_var;
%var set of 1..3: x9 ::output_var;

constraint set_lt(x1, x2);
constraint set_lt(x2, x3);
constraint set_lt(x3, x4);
constraint set_lt(x4, x5);
constraint set_lt(x5, x6);
constraint set_lt(x6, x7);
constraint set_lt(x7, x8);
%constraint set_lt(x8, x9);

solve  satisfy;
```

which, when solved with `--all-solutions`, shows that `flatzinc` adheres to the **correct** specification whereas both `JaCoP` and `fzn-gecode` don't.

**Comment by Dekker1** [comment]
Since the bug seems to have propagated to all the solver bug trackers, I will close the issue here.
