### ISSUE TITLE
minisearch LNS bash error -> DEBUG: interpreting combinator (...) repeating combinator (...) transformed binops (...) scope combinator

### ISSUE THREAD

**Issue by frietjoff** [MiniZinc/libminizinc#186]
Good evening,

I want to run a LNS on my large nurse scheduling model. Thanks to @Dekker1 I got minisearch working. It runs my model with a `solve satisfy` with the same result as the IDE.

When I run minisearch in bash (on Windus Subsystem for Linux) with 

```
include "globals.mzn";
include "minisearch.mzn";
(...)
int: iterations = 100;
float: destructionRate = 0.3;
int: time_ms = 5*1000; 
solve search lns_min(obj, flatSchedule_days, iterations, destructionRate, time_ms);
```

Bash returns the following error. What does that mean? How do I fix it?

Thanks !!

```
Typechecking ... done (94 ms)
Flattening ... done (16828 ms)
Optimizing ... done (578 ms)
Converting to old FlatZinc ... done (1641 ms)
DEBUG: interpreting combinator lns_min(obj,flatSchedule_days,iterations,destructionRate,time_ms) according to its defined body.
DEBUG: repeating combinator scope(post(neighbourhoodCts(x,d)) /\ time_limit(timeout_ms,bab_min(obj)) /\ commit() /\ print("Intermediate solution of LNS with objective "++format(sol(obj))++"\n")) /\ post(obj < sol(obj)) for 1/100 times
DEBUG: Transformed binops into call: and([scope(post(neighbourhoodCts(x,d)) /\ time_limit(timeout_ms,bab_min(obj)) /\ commit() /\ print("Intermediate solution of LNS with objective "++format(sol(obj))++"\n")),post(obj < sol(obj))])
DEBUG: SCOPE combinator
```

**Comment by Dekker1** [comment]
I assume that the output that is preceded by `DEBUG: ` are messages added by the developers of MiniSearch to perform debugging tasks. (I don't think this output is unexpected in any way, there doesn't appear to be an error)

If you find the same solution as with another solver, then I think it's safe to assume that there are no direct problems. If you had a problem other than the output that I missed, please feel free to comment below.
