### ISSUE TITLE
No array3d for par opt int values

### ISSUE THREAD

**Issue by udalrich** [MiniZinc/libminizinc#188]
There exist array3d functions to create 3d arrays of `var int`, `opt var int` and `par int` but there is not a corresponding function to create a 3d array of `par opt int`.  This makes it impossible to initialize such arrays.

My use case is that I have a job shop style program, where the jobs only require a subset of all tasks, and there are multiple combinations that will complete a job.  To model this, I am creating an array as such

    enum Tasks;
    enum Jobs;
    int: maxTasks;
    set of int: TaskIndex = 1..maxTasks;
    int maxOptions;
    set of int: Options = 1..maxOptions;

    array[Jobs, Options, TaskIndex] of Tasks: jobOptions;

I would like to initialize `jobOptions` by

    jobOptions = array3d(Jobs, Options, TaskIndex, [
         % Job 1
         Task1, Task2, % Option 1
         Task3, <>,      % Option 2

          % Job 2
         Task3, Task2, % Option 1
         <>, <>,      % Only one option for job 2
    ];

but that fails because it returns an array of `opt var Tasks`.  If I replace `<>` with `fix(<>)`, then none of the existing functions match the parameter.

**Comment by guidotack** [comment]
This has been fixed on the develop branch now, the fix will be part of an upcoming release.
