### ISSUE TITLE
ceil and float cause mzn-fzn to segfault

### ISSUE THREAD

**Issue by n-kall** [MiniZinc/libminizinc#193]
Both 'ceil' and 'float' coercions (as described at http://www.minizinc.org/doc-lib/doc-builtins-coercion.html) cause mzn-fzn to segfault, however 'round' works correctly.

Failing example:
float: x = 5.8;
var int: y;
constraint y = ceil(x);
solve satisfy;

**Comment by a1880** [comment]
This does not happen in my installation.
What version and what operating system platform are you using?

**Comment by n-kall** [comment]
Sorry, I forgot to add details:
OS: Debian 9 (Stretch) 64-bit
MiniZinc version: latest build from git master (2.1.6) -- also occurs in 2.1.5


MiniZinc to FlatZinc converter, version 2.1.6
Copyright (C) 2014-2018   Monash University, NICTA, Data61
FZN solver plugin, compiled  Jan  9 2018  10:05:13

$ ./mzn-fzn ceil.mzn -v

Parsing file(s) 'ceil.mzn' ...
processing file './libminizinc/build/../share/minizinc/std/stdlib.mzn'
processing file './libminizinc/build/../share/minizinc/std/builtins.mzn'
processing file './libminizinc/build/../share/minizinc/std/redefinitions-2.1.1.mzn'
processing file './libminizinc/build/../share/minizinc/std/redefinitions-2.1.mzn'
processing file './libminizinc/build/../share/minizinc/std/redefinitions-2.0.2.mzn'
processing file './libminizinc/build/../share/minizinc/std/redefinitions-2.0.mzn'
processing file '/home/book/Documents/Tinkering/minizinc_git/libminizinc/build/../share/minizinc/std/redefinitions.mzn'
processing file './libminizinc/build/../share/minizinc/std/flatzinc_builtins.mzn'
processing file 'ceil.mzn'
 done parsing (27 ms)
Typechecking ... done (36 ms)
Flattening ...Segmentation fault

**Comment by n-kall** [comment]
This also occurs when building on Debian testing (Buster) which currently has GCC 7.2.0

**Comment by guidotack** [comment]
This was a problem with namespaces in certain versions of gcc (or its standard library). It's been fixed on the develop branch and the fix will be part of 2.1.7 (which will be released shortly).

**Comment by n-kall** [comment]
Thanks for the info. I have confirmed this is fixed when building the current develop branch. Looking forward to the next release.
