### ISSUE TITLE
Behavior of partial functions in element constraint

### ISSUE THREAD

**Issue by jnmonette** [MiniZinc/libminizinc#197]
Not sure this is to be considered as a bug but this is at least some strange behavior. I have the following piece of code:

```
set of int: mint = -10..10;

var mint: z;
var mint: y;
var mint: x;

constraint x = [z div y, z][1+(y!=0)];
%constraint x = if y!=0 then z div y else z endif;

constraint y = 0;

solve satisfy;
```
This model is unsatisfiable, while if one replaces the first constraint by the commented out constraint, one gets a solution. 

I thought that both constraints would have the same behavior/semantics but it appears that this is not the case with partial functions. Is that expected?

**Comment by Dekker1** [comment]
It seems that because the array contains an expression that is partially undefined the whole model becomes inconsistent.

The question is if undefined elements can be allowed in an array. The same behavior is seen in this example:

```
var int: z;
var int: x;

constraint x = [z div 0, z][2];

solve satisfy;
```
