### ISSUE TITLE
Missing 2.1.7 Binary Packages

### ISSUE THREAD

**Issue by jim-carciofini** [MiniZinc/libminizinc#204]
With release of 2.1.7 it appears that the binary packages did not get built. The Minizinc website points at non existent files.  Are binary packages no longer supported?

**Comment by Dekker1** [comment]
Hi,

I'm sorry it took me so long to get back to you. With some consideration the team decided that we would no longer provide separate executables for just the compiler. The number of downloads for these executables suggested that there was only a very limited interest in these executables and the audience for the bare command-line compiler, without any solvers, would probably be able to compile these executables themselves. (These might actually be the people who would benefit from trying the `development` branch).

Note that the executables are still part of the full MiniZinc distribution, which distributes the compiler with several solvers and the IDE. I would suggest adding the location of the executables in the distribution to the path to use them from the command-line. Alternatively you could filter the executables in the distribution as you see fit and use them as before.

We are sorry for the sudden change and the website not being up-to-date.
