### ISSUE TITLE
value_precede() not effective for MIP solvers

### ISSUE THREAD

**Issue by fbrandt** [MiniZinc/libminizinc#205]
Hi,

the following model returns a solution ([I3, I2, I1]) for MIP solvers but is UNSAT for CP solvers (which is the expected behaviour):

    include "globals.mzn";
    enum ITEMS = {I1, I2, I3};
    array[1..length(ITEMS)] of var ITEMS: order;
    constraint all_different(order);
    constraint value_precede(I1, I2, order);
    constraint value_precede(I2, I1, order);
    solve satisfy;

If ``ITEMS={I1,I2}`` the MIP solvers also return UNSAT.
I'm using version 2.1.7 of the bundled MinizincIDE.

Cheers,
Felix

**Comment by Dekker1** [comment]
Hi Felix,

Thank you for reporting the problem. It seems that although this was a problem in 2.1.7 it has already been resolved on the development branch. The inconsistency will actually already be determined at compile time (`WARNING: model inconsistency detected`).

Cheers,
Jip
