### ISSUE TITLE
mzn-cbc giving inconsistent output with json file input

### ISSUE THREAD

**Issue by Strider26** [MiniZinc/libminizinc#209]
I have a minizinc model which takes .json input file dynamically created by python code.
Strangely the same command line code gives "Unsatisfiable" output but when I rerun the code it gives me the expected optimal output.

`mzn-cbc --output-mode json -Glinear Prod.mzn InputData.json`

I have no clue how to debug this. The main program is in python which calls above command from subprocess. 
I have tried the same command from command prompt as well (Windows) it gives the same inconsistent result.

**Comment by Dekker1** [comment]
Hi @Strider26,

We've recently fixed a problem within the MiniZinc JSON parser that occurred on multi-digit numbers. I think this is probably the cause of your problem. The problem should be resolved in the next release.

**Comment by Strider26** [comment]
Hi @Dekker1 ,

Is there a way I could write json object in python to .dzn file as a workaround for this.
TIA.

**Comment by Dekker1** [comment]
@Strider26, The best solution would be to compile the development branch and see if that solves your problem.

**Comment by guidotack** [comment]
This should be fixed in the current release.
