### ISSUE TITLE
(doc request) add cmd line example

### ISSUE THREAD

**Issue by jwaldmann** [MiniZinc/libminizinc#210]
I needed some time, and some luck, to find out how to run even the simplest of examples. I recommend
to add a working cmd line to some top-level Readme.

I built and installed coin-or/Cbc and libminizinc from source and checked out minizinc-examples.
I was expecting that 
```
mzn-cbc  queens.mzn -Dn=4
```
'just works'. (I  guessed the '-Dn=4' part). But I got
```
Error: constraint not found: int_lin_ne
```
Luckily, I stumbled upon some issue here in this tracker from which could copy the missing argument
```
mzn-cbc  queens.mzn -Dn=4 -Glinear
```
Now this may be a feature of this particular back-end. I also tried
```
mzn-fzn  queens.mzn -Dn=4 -v
```
since this `mzn-fzn` gets installed by default. It gives
```
MiniZinc: internal error: Error occurred when executing FZN solver with command "flatzinc -v /tmp/fznfilexbSH5p.fzn".
```
and this looks like `flatzinc` be installed by default, but http://www.minizinc.org/ does not mention it.

**Comment by Dekker1** [comment]
Hi @jwaldmann,

Thank you for your feedback. I'm sorry you had to go to so much trouble to find the right information. As you might have guessed, MiniZinc is often used in combination with the MiniZincIDE. In combination with the IDE most of these parameters are set. I agree however that the information regarding these flags might not be fully apparent.

We are committed to improving the documentation and the general experience. The next upcoming release will likely resolve many issues. We also hope to release more documentation soon. 

Regarding your issues:

More information about the linear solvers, like `mzn-cbc` can be found in `README_MIP.txt`.

`flatzinc` is the standard solver used when no solver is chosen. It is distributed with our releases, but is ready to be phased out. To use mzn-fzn with a different solver the `-f` flag can be used. More information can be found by running `mzn-fzn -h`.

**Comment by jwaldmann** [comment]
see also https://github.com/MiniZinc/libminizinc/issues/130#issuecomment-383375715

**Comment by guidotack** [comment]
The documentation has been updated to include command line examples etc, and the new minizinc driver should make it easier to select different solvers.
