### ISSUE TITLE
mzn2fzn fails to parse negative numbers in JSON data

### ISSUE THREAD

**Issue by h-rummukainen** [MiniZinc/libminizinc#214]
I'm using mzn2fzn from the libminizinc develop branch (latest commit c5d133490c0905a769611a31bfb77be75a43e201), and encountered an issue with JSON data files.
Specifically, JSON input with negative numbers does not work, but gives the following error message:

    MiniZinc: JSON parsing error: unexpected token `-'

It looks like JSONParser::readToken in json_parser.cpp does not have a case for minus sign.  It appears to work if I change the condition in the default case to

    if ((buf[0]>='0' && buf[0]<='9') || (buf[0] == '-'))  {

Also, when testing the fix I noticed that mzn2fzn fails to recognize "x.json" as JSON, but "xx.json" works.

**Comment by guidotack** [comment]
Thanks. Those should be both fixed on the develop branch now.
