### ISSUE TITLE
MIP solver supports

### ISSUE THREAD

**Issue by lteu** [MiniZinc/libminizinc#215]
Hi all,

I hope the MIP solver parts will be updated,
e.g. the current version supports SCIP v.3.2.1 however, SCIP v.5 is released,
if you try to build with SCIP v.5 you will find a lot of dir-path and label problems.

Similar thing also for Cplex configuration, where the following error messages will be generated.
https://www.ibm.com/developerworks/community/forums/html/topic?id=ea08c6b2-560a-4b09-a0c1-faf8050a0165

Thanks for your attention
Cheers
LT

**Comment by guidotack** [comment]
The CPLEX linking problems should be fixed in the current release. We have not had the resources to update the SCIP interface yet (any volunteer efforts would be greatly appreciated!)

**Comment by Dekker1** [comment]
Both CPLEX and SCIP builds with their newest distributed versions are now possible. Please let us know if there are any more problems.

(Note that currently SCIP distributes a shared library, which needs to be on the linker path for the compiled minizinc executable to work)
