### ISSUE TITLE
Discrepance between generated FlatZinc file and FlatZinc specification

### ISSUE THREAD

**Issue by 95A31** [MiniZinc/libminizinc#216]
Hi, 
I am working on [Magic Sequence (Naive model)](https://github.com/MiniZinc/minizinc-benchmarks/tree/master/nmseq). Using the following  command:

`mzn2fzn nmseq.mzn 100.dzn`

the generated _nmseq.fzn_ file in line _20303_ contain the following constraint:

`constraint int_eq_reif(X_INTRODUCED_0_,0,X_INTRODUCED_100_):: defines_var(X_INTRODUCED_100_);`

The second argument is an integer, but the FlatZinc 1.6 (and 1.5) specification at page 18 state that the second argument is an integer variable. This give me the following error: 

`Error: Type error: integer variable expected in line no. 20303`

using the [GECODE FlatZinc Parser](http://www.gecode.org/flatzinc.html). 

How I should manage it?

**Comment by guidotack** [comment]
An integer constant is always allowed to be put in place of an integer variable. The Gecode FlatZinc parser skeleton may be a bit out of date, the actual Gecode FlatZinc parser accepts these constraints without complaining.

**Comment by 95A31** [comment]
I leave a comment in case someone has the same issue:
Gecode in commit [c12927f2](https://github.com/Gecode/gecode/commit/c12927f21f016a934d54f132c8bf2fe6b76a212b) introduce the function [arg2IntVar](https://github.com/Gecode/gecode/blob/712c9b3705fca5c6ae4c5f469065d7d1e7d758f5/gecode/flatzinc/flatzinc.cpp#L2282) that check if the argument is a variable, if it isn't then a variable is created on the fly.
