### ISSUE TITLE
Accessing multidimensionnal arrays with variables

### ISSUE THREAD

**Issue by Xyouz** [MiniZinc/libminizinc#219]
I've noticed an issue when using n dimension arrays (for n >= 5) and trying to access them with variables. The following example shows this issue. Note that when at least one of the dimension is a is accessed with a constant there is no issues.

```
var 1..2 : x;

var bool : s;

array[1..2,1..2,1..2,1..2,1..2] of bool : tab = array5d(1..2,1..2,1..2,1..2,1..2,[false, true, false, false, true, false, true, true, false, false, false, false, false, false, false, false, true, false, true, true, false, true, false, false, true, true, true, true, true, true, true, true]);

% Erreur
constraint s = tab[x,x,x,x,x];
% Ok
% constraint s = tab[2,x,x,x,x];
% Ok
% constraint s = tab[x,x,x,x,1];

solve satisfy;

output [show(s)];
```

(I'm using the bundle version 2.1.7)

**Comment by Dekker1** [comment]
This seems to be a limit in the compiler. When trying the same example with a 6 dimensional array, it still only work with an maximum of 4 levels of variables as accessors.

@guidotack Is this a limit by design within the compiler?
