### ISSUE TITLE
minizinc-2.0: 2 or 4 solutions?

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#22]
model:

```
include "globals.mzn";

var set of 1..2: x;
array[1..2] of var bool: y;

constraint
  x = {1} /\
  forall(i in x)(y[i]);

solve satisfy;

output [
  "x = ", show(x), "\n",
  "y = ", show(y), "\n",
  ];
```

run:

```
solovej>minizinc -a bug.mzn
x = 1..1
y = [true, false]
----------
x = 1..1
y = [true, false]
----------
x = 1..1
y = [true, true]
----------
x = 1..1
y = [true, true]
----------
==========
solovej>mzn-gecode -a bug.mzn
x = 1..1
y = [true, false]
----------
x = 1..1
y = [true, true]
----------
==========
```

Why are there multiple copies of solutions in the first query?

**Comment by guidotack** [comment]
The compiler generates a few auxiliary variables for this model, and the solvers still need to search over those variables. Gecode uses a special search that avoids enumerating solutions that only differ in auxiliary variables, but other solvers (such as G12fd) don't perform that kind of optimisation.

**Comment by matsc-at-sics-se** [comment]
Yes, but IMHO this is not an optimization issue. Surely the correct number of solutions should follow from the MiniZinc semantics. Is the correct number of solutions 2 or 4?

**Comment by guidotack** [comment]
Currently the MiniZinc semantics doesn't specify whether solvers are allowed to enumerate solutions that only differ in values for auxiliary variables more than once (so, in effect, it's allowed).
The MiniZinc 1.6 distribution contained the solns2dzn tool, which has an option -c to canonicalise the output. The following command line will remove all duplicates:

    flatzinc -a bug.fzn | solns2dzn -c | solns2out bug.ozn

I will include solns2dzn again in 2.0.3 (to be released next week), it still works with MiniZinc 2.  You can then also run

    minizinc -c bug.mzn

with the same effect (it currently abort with an error saying that solns2dzn cannot be found).

**Comment by Kris68360** [comment]
Hello,

I am glad to see that other persons have the same issue than me. Nevertheless, the use of gecode in addition to Minizinc 1.6 or 2 doesn't change anything in my case. I still get all the non-wanted solutions. On the other hand, when using Minizinc IDE 2.0.8 in addition to gecode, I got the desired result.

Are these different behaviours wanted by the community ?

Thank you for your help.

Chris

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
