### ISSUE TITLE
Installing other FlatZinc solvers beside the one supported by libminizinc

### ISSUE THREAD

**Issue by hakank** [MiniZinc/libminizinc#227]
My system contains a lot of different FlatZinc solvers as an executable + globals (e.g. PicatSAT, Chuffed, or-tools, minisatid, minicsp, etc) that I would like to support these as well. 

However, I cannot anything in the documentation about that.  Have I missed something?

/Hakan

**Comment by a1880** [comment]
Hej Hakan,
In the MiniZinc IDE, menu "MiniZinc/Preferences" there is a drop-down list "Solver" which has a final point "Add new ...". 
I found that the "MiniZinc path" in the same dialog ws not updated properly to the new 2.2.0 version.

**Comment by hakank** [comment]
Hej Axel.

Thanks for your input. 

However, I should have been mentioned that I want this to do this from pure command line, not via the MiniZinc IDE. 

And I should also have mentioned that the problem was introduced in MiniZinc version 2.2.0. Before this version one could use the minizinc option "--mzn2fzn-cmd" to state which executable - and its parameters - that should be run as a FlatZinc solver. That option is gone in 2.2.0, so I wonder how to proceed instead if I want to use plain command line (and for solvers for which support are not included in the MiniZinc distribution).

It seems that one have to - somehow - register a solver to able to use it with the MiniZinc's --solver option, but I have found no way to do that for solvers such as PicatSAT. 

Hope this is more clear. And sorry if I have confused anyone.

/Hakan

**Comment by a1880** [comment]
Hej Hakan again,

I added the following file as share/minizinc/solvers/picat.msc

```
{
  "id": "picat",
  "name": "picat",
  "description": "Picat FlatZinc script",
  "version": "24",
  "mznlib": "-Gpicat",
  "executable": "picatRun.cmd",
  "tags": ["cp","int", "float", "set", "restart"],
  "stdFlags": ["-a","-n","-s","-p","-r","-f"],
  "supportsMzn": false,
  "supportsFzn": true,
  "needsSolns2Out": true,
  "needsMznExecutable": false,
  "needsStdlibDir": false,
  "isGUIApplication": false
}
```

Not sure about every parameter, but I could solve a small MiniZinc problem using picat.
Actually, I took your picat MiniZinc library from 2014.

**Comment by hakank** [comment]
Thanks, Axel.

This actually works great. Where did you find this info?

**Comment by a1880** [comment]
Just by trial and error.

**Comment by guidotack** [comment]
Forgot to say: you can also still run solvers from the command line without creating configuration files, it's just that the options are not listed in the default --help output. Try
`minizinc --help org.minizinc.mzn-fzn`
That will output the options you're looking for. Perhaps this should be part of the default --help, we might change this in the next release.

**Comment by hakank** [comment]
Thanks Guido.

This helped a lot! 

(I cannot run the IDE at all now. The precompiled version assumes versions of libs that I don't have. Also my Ubuntu 18.04 LTS version of Qt 5 don't seems to be the latest one and I really would like to use the Ubuntu supported version. But I might upgrade that manually.)
