### ISSUE TITLE
Unexpected behaviour of array slices

### ISSUE THREAD

**Issue by hakank** [MiniZinc/libminizinc#229]
One nice addition of the syntax is the array slices and I wanted to test them with - of course - Sudoku. :-)

Here's a working Sudoku model (with the "old" coding of the region constraint):

```
include "globals.mzn"; 

int: n;
int: reg = ceil(sqrt(int2float(n)));
array[1..n, 1..n] of var 1..n: x;
solve satisfy;        

constraint 

forall(i in 1..n) (
    % Nice!    
    alldifferent(x[i,..]) /\
    alldifferent(x[..,i])
  )
  /\
  forall(i in 0..reg-1,j in 0..reg-1) (
    alldifferent([x[r,c] | r in i*reg+1..i*reg+reg, c in j*reg+1..j*reg+reg]) 
  )
;

output 
[
  if j = 1 then "\n" else " " endif ++
    show(x[i,j])
  | i,j in 1..n
] ++ ["\n"];

% Problem instance from  http://en.wikipedia.org/wiki/Sudoku
n = 9;
x = array2d(1..n, 1..n, [   
5,3,_,_,7,_,_,_,_,
6,_,_,1,9,5,_,_,_,
_,9,8,_,_,_,_,6,_,
8,_,_,_,6,_,_,_,3,
4,_,_,8,_,3,_,_,1,
7,_,_,_,2,_,_,_,6,
_,6,_,_,_,_,2,8,_,
_,_,_,4,1,9,_,_,5,
_,_,_,_,8,_,_,7,9,
]);
````

I expected that array slice coding the regions constraints would work as well:

`alldifferent(x[i*reg+1..i*reg+reg,j*reg+1..j*reg+reg]) `

But this error is thrown:

``MiniZinc: type error: no function or predicate with this signature found: `alldifferent(array[int,int] of var int)'``

Am I wrong that this should work?

/Hakan

**Comment by guidotack** [comment]
Array slices have the dimensions of the arguments, so the result is a 2d array and alldifferent is only defined for 1d. We should probably make alldifferent accept arbitrary arrays. I’ll change that for the next release.

**Comment by hakank** [comment]
Ah, I understand the error message now. Excellent if `alldifferent/1` would accept arbitrary arrays.

Until then, it can be fixed with `array1d/1` as in:

 `alldifferent(array1d(x[i*reg+1..i*reg+reg,j*reg+1..j*reg+reg])`

**Comment by pierfle** [comment]
I am also very happy to have slicing (and look forward to automated array1d coercion, maybe even in int_search/4?!): thanks!!!

Following up: column-slicing a 2d array does not yet work as expected when the row indices are defined by an enumeration as opposed to an integer interval.  Consider the following:
```
%enum Rows = {A,B,C,D,E}; % OK for row slicing (line 5), but NOT for column slicing (line 6)
set of int: Rows = 1..5; int: B=2; % OK for all slicing (lines 5 and 6)
set of int: Cols = 1..7;
array[Rows,Cols] of var 1..4: M;
output [show(M[B,..])]; % row slicing: show row B(=2)
output [show(M[..,3])]; % column slicing: show column 3
```
It works fine.  Now uncomment line 1 and comment away line 2, to obtain a normally equivalent model, but we get the type error:
```
MiniZinc: type error: array index 1 must be `Rows', but is `set of int'
```
on the second output statement (in line 6).

**Comment by guidotack** [comment]
The slicing has been fixed. The alldifferent constraint and the standard search annotations now support multi-dimensional arrays. Since these changes are fully backwards compatible they will be part of the 2.2.1 release (coming soon).

**Comment by pierfle** [comment]
Wonderful, thanks!

Is the idea for the search annotations not to specify how multi-dimensional arrays are coerced into 1d ones, despite that for instance input_order depends on this, with the actual coercing and the one assumed by the modeller possibly differing?

You can also make the other all-difference & co constraints and all counting constraints support multi-dimensional arrays, that is whenever there is full variable symmetry.

**Comment by guidotack** [comment]
The change to multi-dimensional arrays for other constraints will have to wait until 2.3.0, since it requires a major update of the global constraints library (the change can only be made for predicates that are not directly redefined by solver libraries).
