### ISSUE TITLE
OSICBC changes optimum depending on optimization

### ISSUE THREAD

**Issue by siritinga** [MiniZinc/libminizinc#234]
Hi!

I posted this as IDE issue but I think it's more a lib issue. I'll remove the IDE one.

I'm still in the learning curve of Minizinc, so I may be wrong. I have a simple model for a scheduling problem. I think the model is right (gives me what I want) but the implementation probably needs improvement.

In any case, I tried it with 2.2.0 version of Minizinc IDE and I changed the optimization for OSICBC optimizer. I'm getting different optimum value depending on the optimization level. I'm using the Windows 64 bit version in Windows 10.

For -O0 and -O1, last line (goal) is: 98.56434392517058
For -O2 and -O3: 53.54740703910277

Both shown the ======= at the end.

I'm attaching the model as reference
[model4.zip](https://github.com/MiniZinc/libminizinc/files/2344998/model4.zip)

**Comment by guidotack** [comment]
Thanks for the bug report. I have found the problem: the multi-pass approach re-evaluates the random number generators in each pass, so the parameters you generate (in the .dzn file) will be different between the first and second pass. I'm not sure yet how to fix this in the compiler, but for now you could simply generate the random numbers outside of MiniZinc (or accept that with multi-pass switched on you are essentially solving a different problem instance).

**Comment by siritinga** [comment]
I understand! Yes, I'm using random and I did't realize it.

Maybe to solve the issues it can be as simple as resetting the seed at the beginning of each evaluation? In any case, knowing that optimization is not introducing any issue, it's fine for me.

Thanks.

**Comment by guidotack** [comment]
Resetting the seed may not be enough, since it's not guaranteed that the second pass evaluates everything in the same order as the first. We may need to find a completely different solution (caching the random values in the first pass and reusing them in the second pass), but that won't be an easy fix so we'll have to leave it for a later release.
