### ISSUE TITLE
show2d and enum

### ISSUE THREAD

**Issue by pierfle** [MiniZinc/libminizinc#238]
show2d(M) shows 2d-matrix M over an enumerated type as an integer matrix: is that a feature?

**Comment by guidotack** [comment]
Due to the type erasure implementation of enums it is not possible to easily fix this in the current compiler (basically enumerated types are invisible inside any user-defined function).

**Comment by Dekker1** [comment]
This should be solved in a70394f2f1c2cd68256e755c936390c1bab6d0a7 and will be part of the next MiniZinc release
