### ISSUE TITLE
json input not giving result

### ISSUE THREAD

**Issue by Strider26** [MiniZinc/libminizinc#243]
I have updated minizinc to the latest release i.e. 2.1
I am trying to run a model from command prompt
`mzn-cbc --output-mode json -Glinear Prod.mzn InputData.json`

This gives me "Unsatisfiable" flag, while if I run same model in IDE or command line using .dzn format I get optimal output. I thought this bug related to json parser was fixed in this release. Not sure if I am making any mistake
TIA!

**Comment by Dekker1** [comment]
Hi @Strider26,

We'd be happy to take a look at the model + data that are giving you the error. Although some bugs in the json parser were fixed in the 2.2 release, one might still be present.

P.S. I assume you meant that you upgraded to the 2.2 release and not 2.1

**Comment by Strider26** [comment]
[InputData.txt](https://github.com/MiniZinc/libminizinc/files/2418220/InputData.txt)
[Production_Planning_Input.txt](https://github.com/MiniZinc/libminizinc/files/2418222/Production_Planning_Input.txt)
[Prod.txt](https://github.com/MiniZinc/libminizinc/files/2418223/Prod.txt)

Please see attched files.
Prod.txt is minizinc model
Production_Planning_Input.txt is json input which gives error
InputData.txt is dzn format input.

I am using 2.2.1 version

**Comment by Strider26** [comment]
I am using json extension while running.
I see that you have used different solver in command above, with this solver I am getting correct output now. 
I had used Glinear solver earlier, may be its an issue with this solver.
Is osicbc a new solver?

**Comment by Dekker1** [comment]
We have been shipping the CBC solver for a while. It used to be shipped as the `mzn-cbc` binary. It is one of the solvers that uses the linear library (like compiling with the `-G linear` flag).
What command did you use that failed?

**Comment by Dekker1** [comment]
@Strider26 mzn-cbc is no longer part of the MiniZinc release. The CBC solver is only shipped as part of the `minizinc` binary. It thus seems like you are still using an older binary.

If you want to use `mzn-cbc` in the same way as you did in previous releases, you might consider adding an alias to you shell `alias mzn-cbc='minizinc --solver osicbc`.
