### ISSUE TITLE
Compiling with solvers installed by package managers

### ISSUE THREAD

**Issue by skosch** [MiniZinc/libminizinc#247]
Hi,

I occasionally find myself using minizinc on other machines, where it then fails to work because the solver libraries aren't in their expected place. This is annoying, so I now install e.g. cbc & friends via `apt-get`, and override the cmake config with hard-coded lines like

```
  set(CBC_INCLUDEDIRS "/usr/include/coin")
  set(LNDIR "/usr/lib/x86_64-linux-gnu/")
  set(OSICBC_LIBS "CbcSolver" "Cbc" "Cgl" "OsiClp"  "Clp" "Osi"  "CoinUtils" "z") 
```
... which works great and is *way* faster than building everything from source every time.

But C build tools aren't exactly my bread and butter, so ... is there a better way of going about this that I don't know about? Or, alternatively, would you be open to extending the build config to automatically find the solver libraries on the major platforms/distributions, if that's even possible?

(Btw, loving the new monolithic `./minizinc` tool. Super convenient. Thank you!)

**Comment by Dekker1** [comment]
Hi @skosch,

The current CMake configuration is mostly based on the way in which we setup the compilation for the solvers for the released versions. I believe that there is a more modular approach, in the style of CMake packages is possible, but I haven't had the time yet to complete the implementation. This would try to find the solver automatically.

Currently the only way to set the solver library location is to use the home variables like `OSICBC_HOME`, which don't work for all distributions when headers and library files are split.

Thank you for the feedback!
