### ISSUE TITLE
libminizinc release tags 2.2.0 and 2.2.1 are missing

### ISSUE THREAD

**Issue by tkren** [MiniZinc/libminizinc#248]
https://github.com/MiniZinc/libminizinc/releases does not list releases 2.2.0 and 2.2.1.

**Comment by guidotack** [comment]
Thanks, the tags somehow disappeared between different git repos. I've added them back in.

**Comment by tkren** [comment]
The tags disappeared again, there are no tags from 2.2.0 through 2.2.3 anymore.  Last week, I could checkout tag 2.2.2.
