### ISSUE TITLE
Path for linux buildscript possibly not correct

### ISSUE THREAD

**Issue by leobuettiker** [MiniZinc/libminizinc#249]
I try to build libminizinc after cloning the repository with the BUILD.sh file. Only if I change the two points (parent directory) to one point (current directory) it does work for me. 

https://github.com/MiniZinc/libminizinc/blob/d8c9007a94080162a866f26d4f0f8b8887444aff/BUILD.sh#L16

**Comment by Dekker1** [comment]
Hi @leobuettiker,

The shell build is a fragment from a setup from someone in our developmental team, but it is not the supported way of building MiniZinc. (There has been talk about removing it).

I suggest you follow the instructions in https://github.com/MiniZinc/libminizinc/blob/master/INSTALL.txt

**Comment by jwaldmann** [comment]
these instructions do no longer exist? what is the recommended way of building?

**Comment by guidotack** [comment]
Just to leave the pointer here, installation instructions are now contained in the MiniZinc handbook:
https://www.minizinc.org/doc-latest/en/installation_detailed.html#ch-installation-detailed
