### ISSUE TITLE
xor problem (minizinc-2.0 + opturion-cpx)

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#25]
If I do:

    FLATZINC_CMD=fzn-cpx minizinc -G opturion-cpx foo.mzn

on foo.mzn:

    var bool: x;
    var bool: y;

    constraint x xor y;

    solve satisfy;

    output [ "x=", show(x), "\n"
	   , "y=", show(y), "\n"
	   ];

I get foo.fzn:

    predicate bool_xor(var bool: a,var bool: b,var bool: r) = array_bool_even([a,b,r]);
    var bool: x:: output_var;
    var bool: y:: output_var;
    constraint bool_xor(x,y,true);
    solve  satisfy;

which doesn't run:

    Opturion CPX(tm) Optimizer version 1.0.2.
    Academic license, issued to matsc@sics.se. 
    Error: syntax error, unexpected '=', expecting ';' in line no. 1

Evidently, the definition of bool_xor/3 was copied into foo.fzn from the redefinitions.mzn that comes with the Opturion CPX distribution.

How come bool_xor(x,y,true) wasn't unfolded to array_bool_even(x,y,true), and is the definition of bool_xor/3 legal FlatZinc at all?  This worked with MiniZinc 1.6.  Is there a work-around?

**Comment by guidotack** [comment]
Thanks for the report. Will be fixed in upcoming 2.0.3.
