### ISSUE TITLE
Flattening crash

### ISSUE THREAD

**Issue by kletzi** [MiniZinc/libminizinc#250]
Hi,

I realized that the conversion from .mzn to .fzn silently crashes (no warning or error message) on some models using 2.2.0 or 2.2.1 that worked well with 2.1.7.
The return code is 0xC0000005.

The issue seems to occur when using an array of variables in the where-part of an array comprehension. A minimal example reproducing the error is the following:

`array[1..1] of var bool: arr;`
`array[int] of var opt int: t = [j | j in 1..1 where arr[j]];`
`solve satisfy;`

I was able to track down the error to flatten.cpp lines 4304 and 4308:

`surround->id()` is called, but surround is NULL

Adding `surround != NULL && surround->id()==...` seems to get rid of the error, but I do not know if that properly fixes the problem.

**Comment by guidotack** [comment]
Thanks! Your fix is exactly right.
