### ISSUE TITLE
Array access warning

### ISSUE THREAD

**Issue by kletzi** [MiniZinc/libminizinc#251]
Hi,

the behavior regarding array access warnings changed from 2.1.7 to 2.2.0, as a small example see:

`var 0..1: last;`
`array[1..1] of var 0..2: arr;`
`constraint forall (i in 1..2 where i <= last) (arr[i] <= 1);`
`solve satisfy;`

While `arr[2]` would be an access violation, the where-clause ensures that this case never occurs for all possible values of `last`.
In 2.1.7 there was no warning, while in 2.2 a warning is issued.

This does not impact the created .fzn (which is actually more efficient in 2.2) and can be suppressed by `::maybe_partial`, but the previous handling of warnings made it easier to spot actual access violations vs. those that are unreachable anyway.

**Comment by guidotack** [comment]
Since this is a variable where clause, MiniZinc currently does not perform any static checks. It actually generates the arr[2] call at the moment, so it should output the warning.
