### ISSUE TITLE
MiniZinc 2.2.1: Flattening slower on Linux

### ISSUE THREAD

**Issue by alexmahrer-adventiumlabs** [MiniZinc/libminizinc#252]
On Linux with MiniZinc 2.2.1, there appears to be a regression in flattening performance compared to MiniZinc 2.1.7. I don't have a concise, self-contained example, but below is a timing comparison. MiniZinc 2.2.1 on OS X appears relatively unaffected, but MiniZinc 2.2.1 on Linux is considerably slower.

Ubuntu 16.04 (Linux kernel 4.4.0-137)  
2.6 GHz Intel Core i7  
16GB Memory
MiniZinc 2.2.1:
> MiniZinc to FlatZinc converter, version 2.2.1, build 29527117
> Copyright (C) 2014-2018 Monash University, NICTA, Data61
... [snip] ...
> done parsing (0.05 s)
> Flattening ...
> 	CompilePass: Flatten with '/opt/minizinc-2.2.1/bin/../share/minizinc//' library ...
> MIP domains ... done (12.32 s)
> Optimizing ... done (12.40 s)
> Converting to old FlatZinc ... done (12.43 s)
> done (12.43 s)
> done (12.49 s), max stack depth 40
... [snip] ...
> Maximum memory 48 Mbytes.
>  **Flattening done, 12.51 s**

Ubuntu 16.04 (Linux kernel 4.4.0-137)  
2.6 GHz Intel Core i7  
16GB Memory
MiniZinc 2.1.7:
> MiniZinc to FlatZinc converter, version 2.1.7
> Copyright (C) 2014-2018   Monash University, NICTA, Data61
... [snip] ...
>  done parsing (27 ms)
> Typechecking ... done (13 ms)
> Flattening ... done (1816 ms), max stack depth 39
> MIP domains ... done (0 ms)
> Optimizing ... done (46 ms)
> Converting to old FlatZinc ... done (9 ms)
... [snip] ...
> Maximum memory 67 Mbytes.
>   **Flattening done, 1.94 s**

macOS High Sierra (Version 10.13.6)  
2.3 GHz Intel Core i7  
16GB Memory 
MiniZinc 2.2.1:
> MiniZinc to FlatZinc converter, version 2.2.1, build 29527117
> Copyright (C) 2014-2018 Monash University, NICTA, Data61
... [snip] ...
> done parsing (0.06 s)
> Flattening ...
> 	CompilePass: Flatten with '/Applications/MiniZincIDE-2.2.1.app/Contents/Resources/share/minizinc//' library ...
> MIP domains ... done (2.99 s)
> Optimizing ... done (3.02 s)
> Converting to old FlatZinc ... done (3.03 s)
> done (3.03 s)
> done (3.09 s), max stack depth 40
... [snip] ...
> Maximum memory 48 Mbytes.
>  **Flattening done, 3.13 s**

**Comment by alexmahrer-adventiumlabs** [comment]
The same behavior occurs in MiniZinc 2.2.0 on Linux.

**Comment by guidotack** [comment]
This was due to a misconfiguration of our Linux build system (which was changed for 2.2.0). The upcoming 2.2.2 release will fix it.
