### ISSUE TITLE
add_to_output ignored for composite variables

### ISSUE THREAD

**Issue by kletzi** [MiniZinc/libminizinc#254]
Hi,
consider the following model:

`var 0..2: v1;`
`var 1..2: v2;`
`var int: s :: add_to_output = v1 + v2;`
`solve minimize s;`

The annotation for s is ignored, instead v1 and v2 are in the output.
Replacing the third line with

`var int: s :: add_to_output;`
`constraint s = v1 + v2;`

results in the correct output of s, however, shouldn't that also be the case for the one-line version?

**Comment by guidotack** [comment]
I tried this with MiniZinc 2.2.0 and 2.2.2 and can't reproduce it. Can you give us some more details: which version of MiniZinc are you using, and how are you calling it (from the IDE, command line)?

**Comment by kletzi** [comment]
Hi, thank you for the fast reply.

On closer investigation, the issue occurs when directly using the solver output without using solns2out (command line, first mzn2fzn, then solver).

The difference is that, while in both versions the variables v1, v2 and s are in the .fzn, the one-line version marks v1 and v2 with `output_var` and uses the .ozn to recalculate s, while the two-line version directly marks s with `output_var`, which was unexpected.
