### ISSUE TITLE
Using arrays in forall

### ISSUE THREAD

**Issue by mrmowji** [MiniZinc/libminizinc#256]
I checked the manual, but it seems MiniZinc doesn't support `forall` with arrays, something like this:

`forall(array [1..n] of var 1..m: arr)`

where `n` and `m` are parameters. I want to iterate over all possible values of an array cells. Is there any way to implement or simulate this in a model?

**Comment by Dekker1** [comment]
Hi @mrmowji,

It is likely that MiniZinc already supports what you are looking for, but I'm unclear on what exactly you mean. If you want to loop over an array you could use:

```
array[1..n] of var 1..m: arr;
constraint for ( i in arr ) (  *insert constraint that is for every element* );
```

**Comment by mrmowji** [comment]
Thanks @Dekker1 for your response.
I want to iterate over all possible values of an array cells.
Consider this line:
`forall (i, j in 1..m)`
This simply iterates `m*m` times (for each possible combination of `i` and `j` in range `1..m`).
Now I want to iterate over all possible combinations of **variable** number of parameters, for example `i1, i2, ..., in`.

**Comment by Dekker1** [comment]
This is possible. Let's assume we have an array `arr` with parameters, with `n` elements, and we want to iterate over a variable number of them. We do this by declaring a variable `m` with domain `1..n` and use this variable to loop:
```
int: n;
array[1..n] of int: arr;
var 1..n: m;
constraint for (i in 1..m) ( .... arr[i] .... );
```

**Comment by mrmowji** [comment]
But your array is one-dimensional, not n-dimensional.
And you're accessing your array inside `for`, not setting values to its cells with each iteration.
**How to assign a different combination of values (from a domain) to n-dimensional array cells on each iteration of `forall`?** That's the problem :). Perhaps it could be solved using combinatorial algorithms, but I wanted to know whether any way is implemented in MiniZinc itself.

**Comment by mrmowji** [comment]
But your array is one-dimensional, not n-dimensional.
And you're accessing your array inside `for`, not setting values to its cells with each iteration.
**How to assign a different combination of values (from a domain) to n-dimensional array cells on each iteration of `forall`?** That's the problem :). Perhaps it could be solved using combinatorial algorithms, but I wanted to know whether any way is implemented in MiniZinc itself.

**Comment by guidotack** [comment]
Please continue this discussion on the forum, since this doesn't seem to be a bug.

**Comment by tobiasBora** [comment]
Did you obtain a solution @mrmowji ? I have the same issue here, where I basically want to write a constraint where I need to check if a property (that depends on an array `x`) is valid for any array `x` of a given length.

**Comment by mrmowji** [comment]
@tobiasBora Unfortunately, I don't recall the specific solution I came up with. At the time, I was using MiniZinc for a few small projects, but I no longer have access to them.

**Comment by tobiasBora** [comment]
@mrmowji Ok, in this discussion someone gave a good solution for my use case https://github.com/MiniZinc/libminizinc/issues/922#issuecomment-2865918968
