### ISSUE TITLE
Release tags 2.2.0 through 2.2.3 disappeared again

### ISSUE THREAD

**Issue by tkren** [MiniZinc/libminizinc#257]
The tags disappeared again (see #248), there are no tags from 2.2.0 through 2.2.3 anymore.  Last week, I could checkout tag 2.2.2. After release 2.2.3 the tags went missing.

Funny thing is that they are visible at https://github.com/MiniZinc/libminizinc/releases/tag/2.2.3 but not in the git repository themselves:

     % git checkout 2.2.3
     error: pathspec '2.2.3' did not match any file(s) known to git.
     % git tag | tail -n5          
     2.1.3
     2.1.4
     2.1.5
     2.1.6
     2.1.7

_Originally posted by @tkren in https://github.com/MiniZinc/libminizinc/issues/248#issuecomment-435800428_

**Comment by guidotack** [comment]
There seems to be a problem with our repository mirroring set up, but we currently can't find out what causes it. I'll keep an eye on it.

**Comment by tkren** [comment]
Something is broken again, the tags 2.2.0 through 2.2.3 are not visible anymore. The last tag that shows up in the repository is 2.1.7.

**Comment by tkren** [comment]
Tags 2.2.0 through 2.2.3 are back again.
