### ISSUE TITLE
solns2out.exe and mzn2fzn.exe are broken on Windows

### ISSUE THREAD

**Issue by PerMildner** [MiniZinc/libminizinc#261]
On windows, solns2out.exe does not accept a single ozn file as argument.

```
$ '/cygdrive/c/Program Files/MiniZinc IDE (bundled)/solns2out.exe' foo.ozn
solns2out.exe: Unrecognized option or bad format `foo.ozn'
...
$ '/cygdrive/c/Program Files/MiniZinc IDE (bundled)/solns2out.exe' --version
MiniZinc to FlatZinc converter, version 2.2.3, build 34907429
Copyright (C) 2014-2018 Monash University, NICTA, Data61
```

I guess this is because `libminizinc/lib/solver.cpp` does not account for the `.exe` file extension when it tries to determine the name of the executable. It does:
```
MznSolver::OptionStatus MznSolver::processOptions(std::vector<std::string>& argv)
{
  executable_name = argv[0];
  executable_name = executable_name.substr(executable_name.find_last_of("/\\") + 1);
  string solver;
  bool mzn2fzn_exe = (executable_name=="mzn2fzn");
  if (mzn2fzn_exe) {
    is_mzn2fzn=true;
  } else if (executable_name=="solns2out") {
    s2out._opt.flag_standaloneSolns2Out=true;
  }
```
Presumably this fails to set `s2out._opt.flag_standaloneSolns2Out` true, which makes the argument processing in `libminizinc/lib/solns2out.cpp` fail to special case a lone .ozn file argument:
```
  } else if ( _opt.flag_standaloneSolns2Out ) { // <<<< Should be true, but presumably is false
    std::string oznfile(argv[i]);
    if (oznfile.length()<=4) {
      return false;
    }
    size_t last_dot = oznfile.find_last_of('.');
    if (last_dot == string::npos) {
      return false;
    }
    std::string extension = oznfile.substr(last_dot,string::npos);
    if (extension == ".ozn") {
      initFromOzn(oznfile);
      return true;
    }
    return false;
  } else {
    return false;
  }
``` 
(I have only looked at the code. I have not verified this in a debugger.)

**Comment by PerMildner** [comment]
`mzn2fzn` seems to have the same problem. Also, the release notes says 

> The minizinc executable can now also be used as a replacement for mzn2fzn (using -c)

I tried to pass `-c` to `mzn2fzn.exe` (which seems to be identical to `minizinc.exe`) as a workaround but adding `-c` does not seem to produce the same results as when `mzn2fzn` is run on non-Windows. Possibly this is related to the code in `solver.cpp` that uses `is_mzn2fzn` (also set when the option `-c` is present) but also uses `mzn2fzn_exe` (which is only set if it detects that the executable is `msn2fzn`, which is never detected on Windows.)

**Comment by PerMildner** [comment]
I think I have found workarounds.
A workaround for `solns2fzn.exe ... foo.ozn` is to instead use `minizinc.exe ... --ozn-file foo.ozn`.
A workaround for `mzn2fzn.exe ... foo.mzn` is to instead use `minizinc.exe --compile  --solver org.minizinc.mzn-fzn ... foo.mzn`.

**Comment by PerMildner** [comment]
Why was this closed? Is it fixed?

**Comment by Dekker1** [comment]
This issue has been closed because the deprecated executable, `mzn2fzn` and `solns2out`, will no longer exist in the next release. Your previous mentioned workaround is the intended option to do separate compilation and solution processing; however, we would encourage all users to create solver configurations so separate compilation and solution processing is not necessary.
