### ISSUE TITLE
loan example fails

### ISSUE THREAD

**Issue by maacl** [MiniZinc/libminizinc#262]
This example: https://www.minizinc.org/doc-2.2.3/en/modelling.html#ex-loan

fails with the following error:

`MiniZinc: internal error: Error: solver backend cannot handle constraint: float_times`

I am using the MiniZinc IDE version 2.2.3 on Windows 10 with OSICBC 2.9/1.16 [built-in] as solver configuration.

**Comment by Dekker1** [comment]
Hi @maacl,

The problem you are facing is that you are running the loan example without any given data. In this case, the problem cannot be encoded into a linear problem. In the text there is a reference to the data file [loan1.dzn](https://www.minizinc.org/doc-2.2.3/en/downloads/loan1.dzn). When the model is used on combination with the data file, then the problem becomes linear and it can be solved by linear solvers like CBC.

We should likely change the solver output to reflect this better.

**Comment by maacl** [comment]
Got it, thanks.
