### ISSUE TITLE
Neglected constraints when predicate boolean expression is "true" ?

### ISSUE THREAD

**Issue by cversari** [MiniZinc/libminizinc#263]
Hello,
  my apologies if this is not the right place to report this issue. 
I have noticed a strange behavior of Minizinc happening when the boolean expression of a predicate contains no variables. Here is an example:
```
var bool: x;
predicate P(var bool: y) = let
  {
      constraint y = true;
  } in true;

constraint P(x);

solve satisfy;
```
The expected result is that the variable `x` can only be `true`, however it turns out that `x` is completely unconstrained. This happens with all the default solver configurations available in Minizinc IDE 2.2.3 34907460 (downloaded yesterday), which makes me think that it may be a flattening error.

A workaround for this problem is to add any variable to the boolean expression: adding one variable is enough to make Minizinc take into account all the constraints on all the involved variables, apparently.
Here is an example:
```
var bool: x;
predicate P(var bool: y) = let
  {
      constraint y = true;
  } in true \/ y;

constraint P(x);

solve satisfy;
```
The above code works as expected, so that `x` is constrained to `true`.

Cristian

**Comment by Dekker1** [comment]
Hi Cristian,

Thank you for reporting the problem. It seems Guido found the problem and managed to address it. It will be part of the next MiniZinc release.
