### ISSUE TITLE
MiniZinc 2.2.3: Gecode Gist solver does not start Gist

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#265]
I want to inspect the search tree of a run with Gecode Gist.  I expected to get a Gist window as soon as `fzn-gecode` starts, but it just runs and opens no window:
```
$ minizinc --solver org.gecode.gist -O1 -a -s --fzn-flag -f ... *.mzn *.dzn
Generated FlatZinc statistics:
Paths: 0
Variables: 5089 bool, 5261 int
Constraints: 2230 bool, 10032 int
    This is a minimization problem.
```
`fzn-gecode` is running:
```
$ ps gx | grep fzn-gecode
 6414 pts/1    R+     6:31 /opt/MiniZincIDE-2.2.3-bundle-linux/bin/fzn-gecode -mode gist -f -a -s /tmp/mznfileIy4rdW.fzn
 6491 pts/2    S+     0:00 grep --color=auto fzn-gecode
```
Gist hasn't changed to post-mortem visualization, has it?

**Comment by matsc-at-sics-se** [comment]
Leaving out `-s` helped, but it wasn't enough:

```
$ fzn-gecode -mode gist -f -a gecode.fzn
Cannot mix incompatible Qt library (version 0x50906) with this library (version 0x50905)
Aborted (core dumped)
```

Is it mentioned anywhere that `-s` effectively disables Gist?

I solved the problem like this:

```
$ export LD_LIBRARY_PATH=/opt/MiniZincIDE-2.2.3-bundle-linux/lib:/usr/local/lib
$ fzn-gecode -mode gist -f -a gecode.fzn
```

For Linux users, perhaps `LD_LIBRARY_PATH` is worth mentioning?

**Comment by Dekker1** [comment]
This issue should be resolved in newer versions of the MiniZinc bundle
