### ISSUE TITLE
Support for Gurobi parameters, or implement "-n" option for Gurobi wrapper

### ISSUE THREAD

**Issue by cversari** [MiniZinc/libminizinc#266]
Hello,
  I am trying to list more than one solution of a MIP SAT problem by using Minizinc's Gurobi wrapper, however
- the option `-a` to get all solutions is apparently not supported,
- the option `-n` has no effect.

Theoretically, Gurobi solver can implement the `-n` option by means of parameters `PoolSearchMode` and `PoolSolutions` (see Gurobi reference manual [here](https://www.gurobi.com/documentation/8.1/refman/poolsearchmode.html)), however I don't understand how I could pass those parameters to Minizinc's Gurobi wrapper. I tried to put them in a file and read it with `--readParam` but without success (edit: to be more specific, putting those parameters in a file and reading the file with `--readParam` has no effect at all). Is there something that I missed?

Thank you,

Cristian

**Comment by cversari** [comment]
Update: actually, the parameters `PoolSearchMode` and `PoolSolutions` _are read_ by the wrapper by means of `--readParam` and passed to the Gurobi solver, and the `-n` parameter _has some effect_ on the solver too. In fact, if both the above parameters are set _and_ the `-n` command line parameter is specified with a sufficiently high solution limit, one can notice that the solver takes a lot of time before returning. So somehow the solver looks for more solutions but, independently of this, only the first one is printed by the wrapper.

**Comment by glebbelov** [comment]
Hi, you should add -a so that all solutions are printed.

**Comment by indrajitsg** [comment]
Is there any way we can pass parameters when we use gurobi with minizinc in command line (example: "presolve 2")

**Comment by glebbelov** [comment]
use --readParam

**Comment by indrajitsg** [comment]
@glebbelov So you are saying I should have a file which has a row like this:

`presolve 2 mipgap 0.01`

and I can refer to that file in the command line as:

`minizinc --readParam D:/Work/Params/gurobi_params.txt  --solver Gurobi model.mzn`

**Comment by indrajitsg** [comment]
@glebbelov I have tried the above, it give this error:

`minizinc: Unrecognized option or bad format '--readParam'`

**Comment by glebbelov** [comment]
Works for me in Ubuntu. Try backslashes in Windows: D:\Work..., if fails let me know the Windows and minizinc version

**Comment by indrajitsg** [comment]
Its the same error. I am using the latest MiniZinc version 2.3.1 and Windows 10. 
`MiniZinc to FlatZinc converter, version 2.3.1, build 70205949`
`Copyright (C) 2014-2019 Monash University, NICTA, Data61`

**Comment by indrajitsg** [comment]
@glebbelov @guidotack , I have checked in Linux also. I downloaded the archive in Ubuntu and checked. This option "--readParam" is not available and is throwing an error.

**Comment by glebbelov** [comment]
I haven't downloaded the distro but checked out the github (tag 2.3.1 or develop) and compiled. All works. Try this too please.

Exact command line: minizinc --readParam ../mzn-gurobi.log --solver Gurobi ../test_mult.mzn

**Comment by indrajitsg** [comment]
Yep, that's exactly what I had been trying.

**Comment by glebbelov** [comment]
Linux and g++ version? Make sure you use the correct minizinc executable (check with `which minizinc`)

**Comment by indrajitsg** [comment]
I am using Windows 10 and I had downloaded the latest 64-bit version 2.3.1. I haven't tried compiling it myself.

**Comment by glebbelov** [comment]
Giving this option after --solver works:

`"c:\Program Files\MiniZinc\minizinc.exe" --solver gurobi test_mzn_dummy_01_1var.mzn -v -s --readParam gurobi_params.prm.txt`

Strangely, when compiled from source on Linux, it works both ways. Haven't tried on Windows.

**Comment by indrajitsg** [comment]
Hi @glebbelov , I have tried the exact same thing in windows 10. It is not accepting "--readParam". I have tried various combinations. Can you try installing a Windows binary version and trying it out?

**Comment by indrajitsg** [comment]
I also did a compilation right now using **develop** branch in an Ubuntu 18.04 virtual machine with g++ 7.4.0. There also, I am getting exactly the same error.

**Comment by glebbelov** [comment]
As you can read in my post, that's exactly what I did on Windows. I have Win 10 Enterprise. For Linux, I have Kubuntu 19.04 with g++ 8.3.0.

**Comment by indrajitsg** [comment]
Ok will attempt on Kubuntu 19.04 with g++ 8.3.0.

**Comment by indrajitsg** [comment]
@glebbelov Which branch of MiniZinc did you use "develop" or "master"?

**Comment by glebbelov** [comment]
Both

**Comment by indrajitsg** [comment]
I compiled in Kubuntu with g++ 8.3.0 and still I am facing that same error

![screenshot](https://i.ibb.co/K7PhRmt/minizinc2.jpg)

**Comment by glebbelov** [comment]
Ah. You have Gurobi via msc. First, this should be unnecessary when Gurobi is installed in standard location, just run minizinc -h and it should show you available backends. Second, if you stay with msc, put --readParam in the extraFlags section.

**Comment by indrajitsg** [comment]
This works! Thanks a lot.
