### ISSUE TITLE
json parsing of anonymous decision variables

### ISSUE THREAD

**Issue by montanier** [MiniZinc/libminizinc#267]
When trying to write an array in a json with anonymous decision variables like this:
```
"parts_in_hu":[[5,5,4,4,_],
                      [5,5,5,5,_]],
```

I obtain the following error:
```
MiniZinc: JSON parsing error: unexpected token `_'
```

When taking a look at the source code of the json parser, it seems that indeed the parsing of anonymous variables is not planned.

**Comment by Dekker1** [comment]
Hi @montanier,

I've had a look at the problem at it seems that using "_" syntax, like in the DZN files, would cause inconsistencies with the JSON format. Using _ in JSON would be invalid according to the standard and using "\_", as a string, could be inconsistent when the actual string should be used.

To resolve this issue I found that using *null* in accordance with the JSON standard would be the best option. So for example the following model:
```
array[1..5] of var -100..100: arr;
output["\(arr)"];
```
Can now be supplied the following data file:
```
{
	"arr": [1,null,3,4,null]
}
```
Which will could output the following solution: `[1, -100, 3, 4, -100]`.

I've added the code to the develop branch, which should be visible shortly.

**Comment by montanier** [comment]
Hi @Dekker1 ,

So I could compile the develop branch without problem and the feature is working nicely. Thanks :-)

**Comment by Dekker1** [comment]
After some discussion we decided to slightly change the JSON parser to better match the MiniZinc semantics. Instead of `null` being used an anonymous variable, it semantically should mean `absent` in MiniZinc. This means that your code now once again will fail; however there is an easy workaround:
We add optional parameters specifically for input of the variables and fix them using an array comprehension.  So you're example will be turned into:

```
array[int] of opt int: input;
array[int] of var -100..100: arr = [if absent(x) then _ else deopt(x) endif | x in input];
output["\(arr)"];
```
```
{
	"input": [1,null,3,4,null]
}
```

Sorry for the inconvenience

**Comment by montanier** [comment]
Hi, no problem. I will make the necessary modifications in the model.

Thank you for your update on this !

**Comment by montanier** [comment]
Hello,

While making the modifications I realized that the mode we have is slightly more complex: the input array has two dimensions. 

I tried without success to rewrite the second line of the model. The only solution that I have for now is the following, but it seems unelegant and generates a Segmentation Fault on more complex models :
```
array[int,int] of opt int: input;
array[1..1,1..5] of var -100..100: arr;

constraint
  forall(i in 1..1, j in 1..5) (
      if not absent(input[i,j]) then 
        arr[i,j] = deopt(input[i,j]) 
      endif
  )
;

output["\(arr)"];
```

**Comment by Dekker1** [comment]
Having to use constraint items is indeed a little less elegant. Although you comprehensions on 2d-arrays become a little more complicated, there are some builtins to help in the process. The following should work again:
```
array[int,int] of opt int: input;
array[int,int] of var -100..100: arr = array2d(index_set_1of2(input), index_set_2of2(input), [if absent(x) then _ else deopt(x) endif | x in array1d(input)]);

output["\(arr)"];
```

I'm surprised about the possible segmentation fault, those are actually a problem. Feel free to post those as a seperate issue if you can come up with a minimal example.
