### ISSUE TITLE
Specific filenames (e.g. count.mzn) are treated as empty

### ISSUE THREAD

**Issue by dbdr** [MiniZinc/libminizinc#276]
```
$  cat count.mzn 
var 0..1: X;
solve satisfy;
output ["X is \(X)"];
$ /opt/MiniZincIDE-2.2.3-bundle-linux/bin/minizinc --all-solutions count.mzn 
----------
==========
```
I expected to see "X is 0" and "X is 1" as solutions.
It turns out that the same file under a different name works as expected:
```
$  cp count.mzn count2.mzn
$  /opt/MiniZincIDE-2.2.3-bundle-linux/bin/minizinc --all-solutions count2.mzn 
X is 0
----------
X is 1
----------
==========
```
Using strace, I found the following suspicious entry when using the original file name:
```
open("/opt/MiniZincIDE-2.2.3-bundle-linux/share/minizinc/gecode//count.mzn", O_RDONLY) = 3
```
It appears that a file count.mzn exists in the library, and apparently is used over the supplied command line argument (even ./count.mzn does not work). This probably happens for other file names as well, and obviously this is very confusing.

**Comment by a1880** [comment]
The same happens when I use the 2.2.3 IDE under Windows.

Syntax `output ["X is \(X)"];` is new to me. Is this documented anywhere?

**Comment by guidotack** [comment]
That's right, user models can't have the same names as files in the standard library. This should probably be documented somewhere, and there should be a proper error message, so I'll mark this issue as a possible enhancement.
@a1880 the string interpolation syntax is documented here: https://www.minizinc.org/doc-2.2.3/en/spec.html#spec-string-interpolation-expressions

**Comment by guidotack** [comment]
This has now been fixed (the fix will be part of the upcoming release).

**Comment by dbdr** [comment]
Thanks @guidotack !
