### ISSUE TITLE
Solve item optional?

### ISSUE THREAD

**Issue by a1880** [MiniZinc/libminizinc#279]
Today, I've noticed by chance that "solve satisfy;" can be omitted. It appears to be the default.
Is this behaviour intended?
It is convenient, but the MiniZinc tutorial still states, that a valid MiniZinc model has to contain exactly one solve item.

**Comment by Dekker1** [comment]
This is indeed intended behaviour. It has been changed to allow more minimal models. When no solve-item is used MiniZinc assumes that it is a satisfaction problem and the "solve satisfy;" statement will be provided to the solver.
