### ISSUE TITLE
CMakeLists.txt defines too low minimum version

### ISSUE THREAD

**Issue by einarjohan** [MiniZinc/libminizinc#282]
CMakeLists.txt currently defines a minimum version of 3.0.0, but the call to FindBISON references DEFINES_FILE, which seems to have been added in 3.4.0:

https://cmake.org/cmake/help/v3.3/module/FindBISON.html

vs

https://cmake.org/cmake/help/v3.4/module/FindBISON.html

**Comment by Dekker1** [comment]
The issue has already been solved on the development branch. The fix will be released with the next MiniZinc release. Until then a newer version of CMake will already be able to compile the project
