### ISSUE TITLE
Tag 2.2.3 disappeared from the repository

### ISSUE THREAD

**Issue by Moisan** [MiniZinc/libminizinc#283]
This seems to be a recurring issue (see #257). Note that this also breaks the "More..." links from the [current doc on global constraint](https://www.minizinc.org/doc-2.2.3/en/lib-globals.html#).

**Comment by guidotack** [comment]
Yes, this is a recurring issue. We still haven't been able to track down the problem, it appears to always affect the same tags (2.2.0-2.2.3). I've pushed them again now.

**Comment by informarte** [comment]
The tags are gone again.

**Comment by guidotack** [comment]
I think I may have found the culprit. Hopefully this is fixed now and won't occur again.
