### ISSUE TITLE
Minizinc/findMUS command line doesn't work

### ISSUE THREAD

**Issue by ceandrade** [MiniZinc/libminizinc#285]
Hi guys,

I know this is not a libminizinc issue and both "globalizer" and "findMUS" codes are not opened yet. However, I need to use these tools from command line / bash scripts, and I have no success. I tried both on Mac OS X Mojave and Ubuntu 19.04.

This issue follows issue #284 that describes a fail/bug when using `findMUS` alone. In light of that issue, I tried to use `minizinc` command line directly, but it keeps saying that I'm using the wrong arguments:

```bash
[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc --solver findmus latin.mzn
FznSubProblem:	hard cons: 0	soft cons: 10	leaves: 10	branches: 5	Built tree in 0.01658 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
Error: Cannot prove UNSAT within solver timelimit. Set a larger timeout with the
'--solver-timelimit' argument or use '--ignore-sat-model' flag to run MUS enumeration anyway.

=====ERROR=====

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc --solver findmus --solver-timelimit 10000 latin.mzn
minizinc: Unrecognized option or bad format `--solver-timelimit'
minizinc: MiniZinc driver.
Usage: minizinc  [<options>] [-I <include path>] <model>.mzn [<data>.dzn ...] or just <flat>.fzn
More info with "/home/cea/MiniZincIDE-2.2.3/bin/minizinc --help"

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc --solver findmus --solver-timelimit=10000 latin.mzn
minizinc: Unrecognized option or bad format `--solver-timelimit=10000'
minizinc: MiniZinc driver.
Usage: minizinc  [<options>] [-I <include path>] <model>.mzn [<data>.dzn ...] or just <flat>.fzn
More info with "/home/cea/MiniZincIDE-2.2.3/bin/minizinc --help"

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc --solver findmus --time-limit 10000 latin.mzn
FznSubProblem:	hard cons: 0	soft cons: 10	leaves: 10	branches: 5	Built tree in 0.01683 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
Error: Cannot prove UNSAT within solver timelimit. Set a larger timeout with the
'--solver-timelimit' argument or use '--ignore-sat-model' flag to run MUS enumeration anyway.

=====ERROR=====

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc --solver findmus --ignore-sat-model latin.mzn
minizinc: Unrecognized option or bad format `--ignore-sat-model'
minizinc: MiniZinc driver.
Usage: minizinc  [<options>] [-I <include path>] <model>.mzn [<data>.dzn ...] or just <flat>.fzn
More info with "/home/cea/MiniZincIDE-2.2.3/bin/minizinc --help"

```

So, the solver asks us to use the option `--solver-timelimit` but `minizinc` actually does not recognize it. Now, using option `--time-limit` set to 10 seconds, `minizinc` just aborts immediately, ignoring the time limit.

Also note that `--ignore-sat-model` is not recognized.

**Comment by lokdlok** [comment]
Hi,

The minizinc driver doesn't know about the '--solver-timelimit' option because it is not in the config file for findmus that comes with the MiniZinc IDE bundle.

Until we release an update you have two ways around this:

1. You can pass arguments to the solver through the minizinc driver using `--fzn-flag` and `--fzn-flags`: `minizinc --solver findmus --fzn-flags "--solver-timelimit 10000" ...`
2. You can modify the `findmus.msc` (`share/minizinc/solvers/findmus.msc`) file that comes with the bundle to include the option by adding the following to the "extraFlags" section:
`["--solver-timelimit", "Timelimit for sub-solver in ms", "int"],`

The `--ignore-sat-model` option shouldn't be exposed. It will be removed in later versions.
FindMUS should not be executed on a satisfiable model.

There are a few other options missing from this file.
We'll make sure they are included in later releases.

Thanks for letting us know.

**Comment by ceandrade** [comment]
Option 1 doesn't work for me:

```bash
$ /Applications/MiniZincIDE.app/Contents/Resources/minizinc --solver findmus --fzn-flags "--solver-timelimit 10000"  latin.mzn
FznSubProblem:	hard cons: 0	soft cons: 10	leaves: 10	branches: 5	Built tree in 0.02329 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
Error: Cannot prove UNSAT within solver timelimit. Set a larger timeout with the
'--solver-timelimit' argument or use '--ignore-sat-model' flag to run MUS enumeration anyway.

=====ERROR=====
```

neither Option 2:

```bash
[~/temp]
$ vim /Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/solvers/findmus.msc 
# Adding line ["--solver-timelimit", "Timelimit for sub-solver in ms", "int"]

[~/temp]
$ tail -n5 /Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/solvers/findmus.msc 
      ["--qx", "Use QuickXplain as shrink method (StackMUS does not call external shrink method)", "bool"],
      ["--help", "Extra help information", "bool"],
       ["--solver-timelimit", "Timelimit for sub-solver in ms", "int"],
    ]
}

[~/temp]
$ /Applications/MiniZincIDE.app/Contents/Resources/minizinc --solver findmus --fzn-flags "--solver-timelimit 10000"  latin.mzn
FznSubProblem:	hard cons: 0	soft cons: 10	leaves: 10	branches: 5	Built tree in 0.01811 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
Error: Cannot prove UNSAT within solver timelimit. Set a larger timeout with the
'--solver-timelimit' argument or use '--ignore-sat-model' flag to run MUS enumeration anyway.

=====ERROR=====

[~/temp]
$ /Applications/MiniZincIDE.app/Contents/Resources/minizinc --solver findmus latin.mzn
FznSubProblem:	hard cons: 0	soft cons: 10	leaves: 10	branches: 5	Built tree in 0.02035 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
Error: Cannot prove UNSAT within solver timelimit. Set a larger timeout with the
'--solver-timelimit' argument or use '--ignore-sat-model' flag to run MUS enumeration anyway.

=====ERROR=====
```

Should I reopen this ticket?

**Comment by lokdlok** [comment]
Hey,

I think findMUS is receiving the --solver-timelimit option but it's just not being very useful.
It might be useful to add the "--verbose-subsolve 1" argument. This should show you how much time is spent on each subset of constraints.

1. `findMUS latin.fzn --verbose-subsolve 1`
2. `findMUS latin.fzn --solver-timelimit 10000 --verbose-subsolve 1`

On a side note, in the previous issue, you used osicbc as the solver when compiling the model to `latin.fzn`. This produces a linearised model. By default `findMUS` uses gecode as its sat checker. I compiled my version of the faulty latin squares problem and while the gecode can prove unsat for the full model quite quickly there are certain subsets that findMUS explores that gecode really takes a long time with.

You might have more luck adding `--solver osicbc` to findMUS. If you try to use the minizinc driver you will have to use `--fzn-flags "--solver osicbc"` to pass this option through.

I hope this gets you a little further.

**Comment by ceandrade** [comment]
Thanks Kevin for your help. Indeed, I have compiled the model with `osicbc` driver, but yet not too much success:

```bash
[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc -c --solver OSICBC --output-paths latin.mzn --fzn latin.fzn 

[ubuntu-vm:~/temp]
$ ls
latin.fzn  latin.mzn  latin.ozn  latin.paths

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/findMUS latin.fzn --verbose-subsolve 1
FznSubProblem:	hard cons: 9	soft cons: 119	leaves: 119	branches: 101	Built tree in 0.03881 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
FznSubProblem:	Solve: 6(E:S) ncons:      119	took: 0.02652 seconds
Error: Cannot prove UNSAT within solver timelimit. Set a larger timeout with the
'--solver-timelimit' argument or use '--ignore-sat-model' flag to run MUS enumeration anyway.

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/findMUS latin.fzn --solver-timelimit 10000 --verbose-subsolve 1
FznSubProblem:	hard cons: 9	soft cons: 119	leaves: 119	branches: 101	Built tree in 0.02303 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
FznSubProblem:	Solve: 6(E:S) ncons:      119	took: 0.00447 seconds
Error: Cannot prove UNSAT within solver timelimit. Set a larger timeout with the
'--solver-timelimit' argument or use '--ignore-sat-model' flag to run MUS enumeration anyway.
```

Even though I used `findMUS` as `minizinc` driver as you suggested:

```bash
[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc  --solver findmus  --fzn-flags "--solver osicbc" latin.mzn 
terminate called after throwing an instance of 'MiniZinc::InternalError'
  what():  MiniZinc: internal error

=====ERROR=====
```

I did some more tests using the GUI both on Ubuntu and Mac OS X. Surprisingly, on MacOS IDE, findmus works fine.

![Screen Shot 2019-05-15 at 10 28 46](https://user-images.githubusercontent.com/722355/57783869-e6f28380-76fc-11e9-9f08-f2cff1a91017.png)

But on Ubuntu version, I got the same errors I see on command line:

![screen1](https://user-images.githubusercontent.com/722355/57783938-0ab5c980-76fd-11e9-9027-e44eed945115.png)

Note that on MacOS we have `findMUS 0.1.0` but on Ubuntu we have `findMUS 0.1.1`. So, it looks like 0.1.1 add some bug on Linux version, at least.

Either way, both versions do not work for me from command line.

**Comment by lokdlok** [comment]
In the output from `--verbose-subsolve 1` the 6(E:S) indicates that the sub-solver or the attempt to call the sub-solver failed in some way.

Could you try running the following commands. They output the minizinc driver's internal configuration. Please verify that the `extraInfo/executable` field for Gecode points to the correct `fzn-gecode` in both cases. findMUS might not be providing the correct environment when calling the sub-solver.

1. `minizinc --solvers-json`
2. `findMUS --solvers-json` ( if this does not work, try `findMUS latin.fzn --solver-flags "--solvers-json"`)

Have you tried using `findMUS --solver osicbc latin.fzn` does it appear to work?

**Comment by ceandrade** [comment]
From my Ubuntu VM (19.04), using `minizinc`:

```bash
[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/minizinc --solvers-json
...
    "extraInfo": {
      "isDefault": true,
      "mznlib": "-Ggecode",
      "executable": "/home/<user>/MiniZincIDE-2.2.3/bin/fzn-gecode",
      "configFile": "/home/<user>/MiniZincIDE-2.2.3/share/minizinc/solvers/gecode.msc"
    },
    "id": "org.gecode.gecode",
    "name": "Gecode",
    "version": "6.1.0",
...

[ubuntu-vm:~/temp]
$ ~/MiniZincIDE-2.2.3/bin/findMUS --solvers-json
...
    "extraInfo": {
      "isDefault": true,
      "mznlib": "-Ggecode",
      "executable": "/home/cea/MiniZincIDE-2.2.3/bin/fzn-gecode",
      "configFile": "/home/cea/MiniZincIDE-2.2.3/share/minizinc/solvers/gecode.msc"
    },
    "id": "org.gecode.gecode",
    "name": "Gecode",
    "version": "6.1.0",
...
```

Then, there is the problem:
```bash
[ubuntu-vm:~/temp]
$ /home/<user>/MiniZincIDE-2.2.3/bin/fzn-gecode
/home/<user>/MiniZincIDE-2.2.3/bin/fzn-gecode: error while loading shared libraries: libQt5PrintSupport.so.5: cannot open shared object file: No such file or directory
```

So, Gecode doesn't find a lib. But this is very weird. Why does Gecode need a QT library? AFAU, QT is used to build GUIs, and `fzn-gecode` is meant to be used on the backend, isn't?

Ok, let's try to solve it:

```bash
[~/temp]
$ sudo apt-get install libqt5printsupport5
...

[ubuntu-vm:~/temp]
$ /home/<user>/MiniZincIDE-2.2.3/bin/fzn-gecode
Usage: /home/<user>/MiniZincIDE-2.2.3/bin/fzn-gecode [options] <file>
       /home/<user>/MiniZincIDE-2.2.3/bin/fzn-gecode -help for more information

[ubuntu-vm:~/temp]
$ /home/<user>/MiniZincIDE-2.2.3/bin/findMUS latin.fzn 
FznSubProblem:	hard cons: 0	soft cons: 10	leaves: 10	branches: 5	Built tree in 0.04483 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
%%%mzn-progress 0.0
MUS: 7 1 2 6 0 8 9
Brief: all_different_int;@{ADRows@AD(row 1)}:()
all_different_int;@{ADRows@AD(row 2)}:()
all_different_int;@{ADRows@AD(row 3)}:()
array_int_lt;@{LGCols@LG(cols 1 2}:()
array_int_lt;@{LGCols@LG(cols 2 3}:()
array_int_lt;@{LLRows@LL(rows 1 2)}:()
array_int_lt;@{LLRows@LL(rows 2 3)}:()

Traces:
./latin.mzn|9|5|10|51|ca|forall
./latin.mzn|19|5|20|70|ca|forall
./latin.mzn|16|5|17|68|ca|forall
%%%mzn-progress 100.00000
%%%mzn-progress 100.0
Total Time: 0.15230	nmuses: 1	map: 6	sat: 5	total: 11
```

There we go. In the end, the problem is a weird dependency. I understand that this is a Gecode issue, not Minizinc. But It will be nice that those dependencies be included on the bundle. Another solution to this is to link `libQt5PrintSupport` and cia, statically. Yes, the final executable will be huge, but we would have such problems.

Let's see for Mac OS:

```bash
[~/temp]
$ /Applications/MiniZincIDE.app/Contents/Resources/minizinc --solvers-json
...
    "extraInfo": {
      "isDefault": true,
      "mznlib": "-Ggecode",
      "executable": "/Users/<user>/tools/gecode-6.0.1/bin/fzn-gecode",
      "configFile": "/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/solvers/gecode.msc"
    },
    "id": "org.gecode.gecode",
    "name": "Gecode",
    "version": "6.0.1",
...
```

Here, it looks like the new installation found an old/custom version of Gecode. This version looks fine:

```bash
[~/temp]
$ /Users/<user>/tools/gecode-6.0.1/bin/fzn-gecode
Usage: /Users/<user>/tools/gecode-6.0.1/bin/fzn-gecode [options] <file>
       /Users/<user>/tools/gecode-6.0.1/bin/fzn-gecode -help for more information
```

But obviously, it is not meant to be used by the new tools. So, I change my path, and remove any reference to "/Users/<user>/tools", and tried again:

[~/temp]
$ /Applications/MiniZincIDE.app/Contents/Resources/minizinc --solvers-json
...
    "extraInfo": {
      "isDefault": true,
      "mznlib": "-Ggecode",
      "executable": "/Applications/MiniZincIDE.app/Contents/Resources/fzn-gecode",
      "configFile": "/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/solvers/gecode.msc"
    },
    "id": "org.gecode.gecode",
    "name": "Gecode",
    "version": "6.0.1",
...

[~/temp]
$ /Applications/MiniZincIDE.app/Contents/Resources/fzn-gecode
Usage: /Applications/MiniZincIDE.app/Contents/Resources/fzn-gecode [options] <file>
       /Applications/MiniZincIDE.app/Contents/Resources/fzn-gecode -help for more information
```

No library problems here. It makes sense since in most cases, Mac OS apps are self-contained, and therefore, should contain `libQt5PrintSupport`. Now, let's try `findMUS` again:

```bash
[~/temp]
$ /Applications/MiniZincIDE.app/Contents/Resources/findMUS latin.fzn 
FznSubProblem:	hard cons: 9	soft cons: 119	leaves: 119	branches: 101	Built tree in 0.07263 seconds.
SubsetMap:	nleaves:	4	nbranches:	1
%%%mzn-progress 0.0
MUS: 0 100 101 102 103 104 105 106 107 108 109 11 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 13 15 16 17 18 2 20 22 24 25 26 36 37 38 39 4 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 6 60 61 62 63 64 65 66 67 68 69 7 70 71 72 73 74 75 76 77 78 79 8 80 81 82 83 84 85 86 87 88 89 9 90 91 92 93 94 95 96 97 98 99 Brief: int_lin_eq;:() int_lin_le;:() int_lin_le;@{AD(row 1)@ADRows}:() int_lin_le;@{AD(row 2)@ADRows}:() int_lin_le;@{AD(row 3)@ADRows}:() int_lin_le;@{LG(cols 1 2@LGCols}:() int_lin_le;@{LG(cols 2 3@LGCols}:() int_lin_le;@{LL(rows 1 2)@LLRows}:() int_lin_le;@{LL(rows 2 3)@LLRows}:()

Traces:
latin.mzn|16|5|17|68|ca|forall
latin.mzn|19|5|20|70|ca|forall
latin.mzn|9|5|10|51|ca|forall
====================

%%%mzn-progress 100.00000
%%%mzn-progress 100.0
Total Time: 2.16485	nmuses: 1	map: 6	sat: 5	total: 11
```

Oh, there we go. Using Gecode that comes with the bundle, we can use `findMUS`.

So, we have two problems here:

1) On Linux version, we have library problems. For production environments, this is really painful. I would recommend to static compile all to distributed as a single self-contained bundle, or create packages for package managers, such that those are aware of the correct dependencies;

2) On Mac OS, note that both custom and bundle Gecode versions are the same (6.0.1). Why do we have different behaviors for the same version?

**Comment by Dekker1** [comment]
@ceandrade The issue regarding Qt on linux might just be a bit of an inconvenience. The MiniZinc bundle already contains the version of Qt that is necessary to run Gecode, which requires it for Gist, and the IDE, which is fully written using Qt. The difference is that when you use the IDE, you will start it using the provided script. This script ensures that the libraries that are shipped with the bundle are on the library path at runtime (i.e., `export LD_LIBRARY_PATH="$DIR"/lib:$LD_LIBRARY_PATH`). When you run fzn-gecode manually, the included libraries are not automatically visible to system. You need to either put them in the standard library directories, like `/usr/local/lib`, or add them to the library path like the IDE script does. Note that the bundle doesn't really install any software. It mainly allows use of the IDE and provides compiled binaries that can be installed on the system manually. We already provide a Snap package which does install the software on a linux system and will ship AppImage files and Docker images for future versions to make this even easier.

Note that your suggested solution (of compiling statically linked executables with Qt) is generally seen as prohibited by the LGPL license.

Regarding the different versions of Gecode being used on your Mac. The current release had a small problem in the configuration file provided for Gecode. Instead of only using the version of Gecode in the bundle, it would look both on the PATH and in the bundle, which might be very unexpected. This issue has been solved on the development branches and should disappear in future releases.

**Comment by ceandrade** [comment]
Thank you @Dekker1 for the explanation. So, I would recommend making this info explicit in the documentation. Indeed, it would be nice to have a short section talking about how to use Minizinc from command line, with all requirements and details. I understand that, in some sense, the developers want that the users use `minizinc` with the proper drivers. But in some cases, such my company, we have to use each part separetely, for several reasons including licensing.

Thank you @lokdlok for your help too.
