### ISSUE TITLE
[] as an Empty Multi-dimensional Array (Inconsistently Handled in Functions)

### ISSUE THREAD

**Issue by aekh** [MiniZinc/libminizinc#287]
Basically, sometimes `[]` is valid as an empty multi-dimensional array, and sometimes it is not.
This seems to be a problem with functions (see examples below). I get the same behaviour with 3d arrays (and probably higher dimensions as well) and with predicates.

(Present in both `main` and `develop`.)

### Inputs (arguments) of Functions

When running the following code

```
function int: f (array [int, int] of int: a) = length(a);
output [ show( f([]) ) ];
```

we get the error

```
MiniZinc: type error: no function or predicate with this signature found: `f(array[int] of bot)'
```

We need to use the 2d-specific empty array `[||]` int the call to `f` to get the code to compile. However, using a declared parameter, we can use `[]` without problem as follows

``` 
function int: f (array [int, int] of int: a) = length(a);
array [int, int] of int: b = [];
output [ show( f(b) ) ];
```

### Output (return value) of Functions

When running the code

```
function array [int, int] of int: g () = [];
output [ show( g() ) ];
```

we get the error

```
MiniZinc: type error: return type of function does not match body, declared type is `array[int,int] of int', body type is `array[int] of bot'
```

Again we need to use the 2d-specific empty array `[||]` in the body of `g` (I note also that `[]` is printed by the output statement, not `[||]`, when doing this). But, using a declared parameter, we can use `[]` without problems as follows

```
function array [int, int] of int: g () = c;
array [int, int] of int: c = [];
output [ show( g() ) ];
```

**Comment by guidotack** [comment]
This is a special case - we allow automatic coercion from the empty array for assignment items and right hand sides of declarations only, in order to be compatible with empty JSON arrays (which don't carry information about dimensionality). We will have to completely change the type checker at some point to change this.
