### ISSUE TITLE
Circular definition not detected, gives segmentation fault

### ISSUE THREAD

**Issue by aekh** [MiniZinc/libminizinc#288]
Compiling the code

```
function array [int] of int: f() = array1d(index_set(a), [1,2,3]);
array [int] of int: a = f();
```

should give an error pointing out the circular definition of `a`. This is because the index set of `a` is defined by the index set of `f()`, which in turn is defined by the index set of `a` (hence, circular).

Currently, this is undetected and results in a segmentation fault when compiling. (Both in `main` and `develop`.)

**Comment by Dekker1** [comment]
In recent versions of MiniZinc a stacktrace and error message are provided for infinite recursions.
