### ISSUE TITLE
Minizinc type error when solving a 2016 challenge problem using osicbc.

### ISSUE THREAD

**Issue by nobodyczcz** [MiniZinc/libminizinc#293]
I meet a Minizinc type error when solving diameterc-mst (MIN) model using Osicbc. 

Minizinc reports "MiniZinc: type error: no function or predicate with this signature found: `pwl(var float,var float,array[int] of float,array[int] of float)". 

Detials are shown as follow.
`chen0213@smallmachine2:~/cbcTuning$ minizinc --output-mode json --output-objective --solver osicbc -p 1 /home/zhechen0213/cbcTuning/models/dcmst/dcmst.mzn /home/zhechen0213/cbcTuning/models/dcmst/s_v20_a50_d4.dzn -v
MiniZinc to FlatZinc converter, version 2.2.3, build 66361443
Copyright (C) 2014-2019 Monash University, NICTA, Data61
Parsing file(s) /home/zhechen0213/cbcTuning/models/dcmst/dcmst.mzn', '/home/zhechen0213/cbcTuning/models/dcmst/s_v20_a50_d4.dzn' ...
processing file '/snap/minizinc/174/usr/share/minizinc/std//stdlib.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//builtins.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_partiality.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_opt.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_var_set.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_set.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_var_float.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_float.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_var_bool.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_bool.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_var_int.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//fzn_if_then_else_int.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefinitions-2.2.1.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//redefinitions-2.1.1.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//redefinitions-2.1.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefinitions-2.0.2.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefinitions-2.0.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefinitions.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//nosets.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefs_lin_halfreifs.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefs_lin_imp.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefs_lin_reifs.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//domain_encodings.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefs_bool_imp.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//redefs_bool_reifs.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/linear//options.mzn'
processing file '/snap/minizinc/174/usr/share/minizinc/std//flatzinc_builtins.mzn'
processing file '/home/zhechen0213/cbcTuning/models/dcmst/dcmst.mzn'
processing data file '/home/zhechen0213/cbcTuning/models/dcmst/s_v20_a50_d4.dzn'
 done parsing (0.02 s)
Flattening ...
        CompilePass: Flatten with '/snap/minizinc/174/usr/share/minizinc/linear/' library ...

/snap/minizinc/174/usr/share/minizinc/std//builtins.mzn:453.16-31:
MiniZinc: type error: no function or predicate with this signature found: `pwl(var float,var float,array[int] of float,array[int] of float)'
   Done (overall time 0.03 s).`

**Comment by glebbelov** [comment]
Please update
