### ISSUE TITLE
Bug in mdd

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#299]
The `mdd` constraint does not behave according to the spec if the outgoing edges from a given node overlap. Example:

```
include "globals.mzn";
array[1..2] of var 1..2: X;
constraint
    mdd(X,
        3,
        [1, 2, 2],
	4,
	[1, 1, 2, 3],
	[{1}, {1}, {1}, {2}],
	[2, 3, 0, 0]);
solve satisfy;
output ["\(X)\n"];
```

The standard expansion says UNSAT, but IMHO there are two solutions: `[1, 1]` and `[1, 2]`.

**Comment by glebbelov** [comment]
Try develop branch

**Comment by guidotack** [comment]
The documentation wasn't clear enough. The mdd constraint assumes that the mdd is deterministic(i.e., a node cannot have two outgoing edges with the same label). We will add a nondeterministic version of mdd for the next release.
