### ISSUE TITLE
v.2.0.4: "internal error: undeclared function or predicate var_dom"

### ISSUE THREAD

**Issue by stian-svedenborg** [MiniZinc/libminizinc#30]
The following model cause mzn2fzn to panic with error:
 "MiniZinc: internal error: undeclared function or predicate var_dom"

```
set of int: smallset = 0..10;
array[1..2, 1..4] of var smallset: X;
constraint forall( i in 1..2 ) (
let {
  array[int] of var smallset: Y = row(X, i);
} in
  Y[1] == 3 % Any use of Y triggers the issue.
);
solve satisfy;
```

There was an old issue with the same symptom: http://www.minizinc.org/trac/ticket/91 .

I have reproduced the issue on mzn2fzn v2.0.2  and v2.0.4.

**Comment by guidotack** [comment]
Thanks for the report, I can reproduce the behaviour.  The old bug was due to var_dom actually not being defined, but this problem is a little different. I'll have to investigate.
If you need a workaround, you can change

    array[int] of var smallset: Y = row(X, i);

into

    array[int] of var int: Y = row(X, i);

which should be equivalent in this case.

Cheers,
Guido
