### ISSUE TITLE
minizinc 2.3.x does not compile cryptanalysis

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#301]
The MiniZinc benchmarks library contains the cryptanalysis problem, which was part of the 2016 MiniZinc challenge.

Starting from MiniZinc 2.3.0, this problem does not compile any more. For example:

```
minizinc step1_aes.mzn kb128_n5_obj16.dzn 
MiniZinc: flattening error: 
  /home/informarte/Workspaces/remote/minizinc-benchmarks/cryptanalysis/step1_aes.mzn:44:
  in call 'SR'
  array index set 1 of argument 2 does not match declared index set
```

**Comment by a1880** [comment]
This looks like an error in the cryptoanalysis problem. The flattening error message is correct, as the index set of the second argument in call 'SR' does not match the declaration of 'SR'. Probably, MiniZinc 2.3.0 has an improved diagnostic to actually detect such errors.

**Comment by guidotack** [comment]
That's right, previous versions of MiniZinc didn't check the declared index sets of function/predicate arguments. I have fixed the declaration of the SR predicate in the benchmarks repository.
