### ISSUE TITLE
Error in geost decomposition

### ISSUE THREAD

**Issue by krzku** [MiniZinc/libminizinc#308]
It seems that geost decomposition is incorrect in minizinc v. 2.3.1. The following model (I have simplified it as much as possible).

include "globals.mzn";

int: k = 2;
int: n = 2;
array[1..n, 1..k] of var 0..1: origin;
array[1..1, 1..k] of int: length = [| 1, 1
				    |];

constraint
     let {
       array[1..1, 1..k] of int: offset = array2d(1..1, 1..k, [0 | i in 1..1, j in 1..k]),
       array[1..n] of set of int: shape = [{1} | i in 1..n],
       array[1..n] of int: kind = [1 | i in 1..n],
     } in
       geost(k, length, offset, shape, origin, kind)
;

solve satisfy;

output["origin = \(origin)"]

generates flatzinc model

var 0..1: X_INTRODUCED_0_;
var 0..1: X_INTRODUCED_1_;
var 0..1: X_INTRODUCED_2_;
var 0..1: X_INTRODUCED_3_;
array [1..4] of var int: origin:: output_array([1..2,1..2]) = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_,X_INTRODUCED_3_];
solve  satisfy;

while in version 2.2.3 generated a correct set of constraints, as follows

array [1..2] of int: X_INTRODUCED_11_ = [1,-1];
var 0..1: X_INTRODUCED_0_;
var 0..1: X_INTRODUCED_1_;
var 0..1: X_INTRODUCED_2_;
var 0..1: X_INTRODUCED_3_;
var bool: X_INTRODUCED_12_ ::var_is_introduced :: is_defined_var;
var bool: X_INTRODUCED_14_ ::var_is_introduced :: is_defined_var;
var bool: X_INTRODUCED_17_ ::var_is_introduced :: is_defined_var;
var bool: X_INTRODUCED_19_ ::var_is_introduced :: is_defined_var;
array [1..4] of var int: origin:: output_array([1..2,1..2]) = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_,X_INTRODUCED_3_];
constraint array_bool_or([X_INTRODUCED_12_,X_INTRODUCED_14_,X_INTRODUCED_17_,X_INTRODUCED_19_],true);
constraint int_lin_le_reif(X_INTRODUCED_11_,[X_INTRODUCED_2_,X_INTRODUCED_0_],-1,X_INTRODUCED_12_):: defines_var(X_INTRODUCED_12_);
constraint int_lin_le_reif(X_INTRODUCED_11_,[X_INTRODUCED_0_,X_INTRODUCED_2_],-1,X_INTRODUCED_14_):: defines_var(X_INTRODUCED_14_);
constraint int_lin_le_reif(X_INTRODUCED_11_,[X_INTRODUCED_3_,X_INTRODUCED_1_],-1,X_INTRODUCED_17_):: defines_var(X_INTRODUCED_17_);
constraint int_lin_le_reif(X_INTRODUCED_11_,[X_INTRODUCED_1_,X_INTRODUCED_3_],-1,X_INTRODUCED_19_):: defines_var(X_INTRODUCED_19_);
solve  satisfy;

The new version does not generate any constraints on rectangle overlapping and it accepts all combinations of values for origin. The old version was correct, generated overlapping constraints and did not allow solutions where rectangles overlap.

BTW, changing domain of origin tp 0..0 gives solution in minizinc 2.3.1 while v. 2.2.3 generates correctly unsatisfied solution.

/Kris

**Comment by guidotack** [comment]
This appears to be fixed in 2.3.2.
