### ISSUE TITLE
regular expressions no longer supported for extensional constraints?

### ISSUE THREAD

**Issue by pierfle** [MiniZinc/libminizinc#311]
Why are regular expressions no longer supported for extensional constraints?  It was so nice to have them, and my course slides have examples using them...

**Comment by Dekker1** [comment]
Hi Pierre,

It seems that we didn't check the regexp version of regular when we merged in the new standard library. The connection with the built in function was lost. 982e22649ca116f7e83e25223476081935d2cc16 should solve this problem.
