### ISSUE TITLE
Piecewise linear constraint

### ISSUE THREAD

**Issue by marcovc** [MiniZinc/libminizinc#319]
Hi,

I think I'm misunderstanding the piecewise_linear constraint. I'm trying to have a piecewise linear approximation of x^2. I created two arrays, xx and yy as:

xx1 = array1d(0..3, [0.0, 2.0, 4.0, 6.0]);
yy1 = array1d(0..3, [0.0, 4.0, 16.0, 36.0]);

and constrained x to be in 4..6.  I was expecting that

x_2 = piecewise_linear(x,xx1,yy1);

would give some x and x_2 where x is close to x_2. Instead it gives x=4, x_2=4.

What is going on? 

The full code is below. Thanks!
 
```
include "piecewise_linear.mzn";

int: piecewiseDivs = 3;

array[0..piecewiseDivs] of float: xx1::add_to_output = array1d(0..piecewiseDivs,[ub(x)*d/piecewiseDivs| d in 0..piecewiseDivs]);
array[0..piecewiseDivs] of float: yy1::add_to_output = array1d(0..piecewiseDivs,[x^2| x in xx1]);

var 4.0..4.0+piecewiseDivs-1: x::add_to_output;
var float: x_2::add_to_output = piecewise_linear(x,xx1,yy1);
```

**Comment by glebbelov** [comment]
Fixed on develop, thanks

**Comment by marcovc** [comment]
Thank you!
