### ISSUE TITLE
Lower bound of array of optional float variables 

### ISSUE THREAD

**Issue by marcovc** [MiniZinc/libminizinc#324]
Hi,

I cannot find the corresponding 

`function int: lb_array(array[$U] of var opt int: x);`

but for

`function float: lb_array(array[$U] of var opt float: x);`

Is this something I can add myself easily?

Thanks!
Marco

**Comment by guidotack** [comment]
There is currently no support for the `var opt float` type in the library. You could have a look at the file `stdlib.mzn` and implement all the required functionality by copying e.g. the definitions of `occurs`, `deopt`, `var_dom`, and all the primitive constraints. It's on our todo list, but not the highest priority - if you're interested, we'd be happy to get a pull request.

**Comment by marcovc** [comment]
Thanks. But where are the definitions of the builtins, for example of

lb_array(array[$U] of var opt int: x);

I can find the declaration but not the definition. Is it written in c++?

**Comment by guidotack** [comment]
Yes, lb_array is defined in c++. But all you will have to do is change the type signature in builtins.mzn (from var float to var opt float) and make a small change in builtins.cpp; basically just add `t[0].ot(Type::OT_OPTIONAL);` before `rb(env, m, ASTString("lb_array"), t, b_array_lb_float);`, same for `ub_array`.

**Comment by marcovc** [comment]
Great, thanks!

**Comment by marcovc** [comment]
Quick question:

In builtins.cpp I see two "entries" for the same ASTString:

{
std::vector<Type> t(1);
t[0] = Type::varint();
t[0].ot(Type::OT_OPTIONAL);
rb(env, m, ASTString("ub"), t, b_ub_varoptint);
}
{
std::vector<Type> t(1);
t[0] = Type::varint();
rb(env, m, ASTString("ub"), t, b_ub_varoptint);
}

I can replicate this for floats, just making sure that this is not a
mistake (not that the last parameter of rb in the second "entry" is also of
varoptint and not varint).

Thanks

**Comment by marcovc** [comment]
Created a PR: 

https://github.com/MiniZinc/libminizinc/pull/327

**Comment by guidotack** [comment]
The `ub` function is overloaded for both `var int` and `var opt int`, and the two entries attach to those two overloaded versions. In this case, we could probably just remove the `var int` declaration in `builtins.mzn` (and the corresponding `rb` call in `builtins.cpp`) because they point to the same function anyway, but I'd prefer to keep both of them in the library so that users don't get confused. So long answer short, just replicating this for floats should be fine.

**Comment by marcovc** [comment]
Ooops I think I broke something with my PR.

This works in the commit before my PR:

```
var 0.0..1.0: x;
var 0.0..1.0: y;
constraint max(x,y)=0.0;
```

but fails now with:

```
MiniZinc: evaluation error: 
  test.mzn:39:
  in binary '=' operator expression
  in call 'max'
  /home/marco/tmp/libminizinc-myfork/share/minizinc/std//builtins.mzn:402:
  in if-then-else expression
  /home/marco/tmp/libminizinc-myfork/share/minizinc/std//builtins.mzn:403:
  in let expression
  /home/marco/tmp/libminizinc-myfork/share/minizinc/std//builtins.mzn:404:
  in call 'float_max'
  /home/marco/tmp/libminizinc-myfork/share/minizinc/linear//redefinitions.mzn:111:
  in call 'array_float_maximum'
  /home/marco/tmp/libminizinc-myfork/share/minizinc/linear//redefinitions-2.0.mzn:16:
  in if-then-else expression
  /home/marco/tmp/libminizinc-myfork/share/minizinc/linear//redefinitions-2.0.mzn:19:
  in call 'array_float_minimum_I'
  /home/marco/tmp/libminizinc-myfork/share/minizinc/linear//redefinitions.mzn:114:
  in let expression
  /home/marco/tmp/libminizinc-myfork/share/minizinc/linear//redefinitions.mzn:118:
    with i = 1
  in binary '<' operator expression
  in binary '<' operator expression
  in call 'lb'
  in call 'lb'
  cannot determine bounds
```

I imagine that the bug should be in the ComputeFloatBounds code that I adapted from the integer case, but not really knowing what I was doing.

Sorry about this.

Marco

**Comment by guidotack** [comment]
Should already be fixed in e0b0f533476990864bf8cb97b96bd90510b0ec1d.

**Comment by marcovc** [comment]
Thanks Guido. Unfortunately I found another issue.

In builtins.cpp, I found added the 2 commented lines below:

```
    {
      std::vector<Type> t(1);
      t[0] = Type::varfloat(-1);
      //t[0].ot(Type::OT_OPTIONAL);
      rb(env, m, ASTString("lb_array"), t, b_array_lb_float);
    }
    {
      std::vector<Type> t(1);
      t[0] = Type::varfloat(-1);
      //t[0].ot(Type::OT_OPTIONAL);
      rb(env, m, ASTString("ub_array"), t, b_array_ub_float);
    }
```

but this seems to break the "non optional" float arrays. I copied this from the integer case where it seems you only have one version of lb_array. This is asymmetrical with the "lb" primitive, for which there are two versions (an opt and a non-opt).

**Comment by guidotack** [comment]
Right - we should probably make it the same for lb and lb_array. For now, I've removed the non-opt version of the array functions from `builtins.mzn`, that fixes the problem. I'll think about whether to introduce both for the array versions or remove the non-opt lb/ub (perhaps it's better for documentation purposes to have both).

**Comment by marcovc** [comment]
Thanks. I have found one more issue but I will try to fix it myself. I'll let you know in case I give up  :)

**Comment by marcovc** [comment]
Actually I need to ask you something before about optionals. 

This code (note: they are int's):

```
array[1..2] of var opt 1..2: x;
var int: f = deopt(max(x));
```

produces this answer:

```
x = array1d(1..2, [<>, <>]);
```

The issue is that is that I have a compiler error if I swap the domains 1..2 to 1.0..2.0, but my question is whether the int solution is correct. If deopt "assumes" that the values are not "undefined", I was expecting that it would give a solution with values from the domain, such as 2 (if "assumes" = constrains).

**Comment by guidotack** [comment]
No, `deopt` doesn't constrain its argument to be non-absent. The idea is that you are only allowed to use `deopt` in contexts where the variable is guaranteed to occur, i.e., under a "guard" of `occurs`. However, if you use an optional variable with an operator that forces it to occur, you can get the behaviour you want, e.g.

```
var int: f;
constraint f = max(x);
```

Note that the operator `=` in a constraint is different from the definition of a variable (this is one of the few places where that difference in semantics is observable). Not sure this is ideal - we could think about making
```
var int: f = max(x);
```
valid and behave the same way.

**Comment by marcovc** [comment]
I see. So the functional version is currently undefined behaviour?

I think I see why, if you make it like the 'constraint' case then it would loose the functional appeal as that declaration would make at least one value of x defined. That would be unexpected as well.

**Comment by guidotack** [comment]
The functional version (which doesn’t contain its argument to be
non-optional) is required to write all the decompositions of var opt
constraints. Without it you couldn’t express them at all. And deopt is
basically an “unsafe” function that should only be used if you know what
you’re doing (i.e., it shouldn’t occur in users’ models, just in
definitions of decompositions).

If you want a constraining version for use in normal models it could be
defined simply as

function var int: force(var opt int: x) = let {
constraint occurs(x); } in deopt(x);

Cheers
Guido
-- 
*GUIDO TACK*
Senior Lecturer

*Information Technology*
Monash University
Level 6, Room 6.40, Building H, Caulfield Campus
900 Dandenong Road
Caulfield East VIC 3145
Australia
T: +61 3 9903 1214
E: guido.tack@monash.edu
http://users.monash.edu/~guidot/

**Comment by marcovc** [comment]
Thanks for the clarifications. One point in favour of making the functional case like the constraint case would be to keep it consistent with what says in the docs:

```
Assignment items assign a value to a variable. They have the form:

<variable> = <expression>;
Values can be assigned to decision variables in which case the assignment is equivalent to writing constraint <variable> = <expression>.
```

which, if I understood correctly, currently is not true if variable is an optional variable.

Anyway, I think this might explain the other issues I am seeing. I will run some more tests tomorrow.

Thanks!
