### ISSUE TITLE
Visibility of non-namespaced symbols in libminizinc

### ISSUE THREAD

**Issue by marcovc** [MiniZinc/libminizinc#325]
Hi,

I am trying to link against libmzn and libgecodeflatzinc at the same time. The goal is to do mzn->fzn with the former, and then get a C++ model that I can fiddle some more with.

However, since both libraries export a non-namespaced symbol, namely 

```c++
yy_input_proc(char*, int, void*)
```

I'm getting linking issues.

I'm guessing lex doesn't like namespaces which prevents namespacing those, but apparently I was able to get around the problem by changing the visibility of the function:

https://github.com/marcovc/libminizinc/commit/1fe54881ec63a98f9f7f4fa5900319f32768b894

Would you like me to open a PR for this, or is there a better idea.

(the same problem exists in the gecodeflatzinc lib, but I'm guessing Guido does both :)

Thanks!

**Comment by guidotack** [comment]
Actually it's not that difficult to put everything inside a namespace, I think that's the cleaner solution. I'll fix this on the develop branch (should be there soon).
