### ISSUE TITLE
mzn2fzn introduces unconstrained search variables

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#333]
For all instances of `median_string`, the MiniZinc compiler (I tried version 2.3.1 and 2.3.2) introduces unconstrained search variables. For example, the Yuck model for the instance `p2_10_8-3` contains

```
var int: X_INTRODUCED_105_ ::var_is_introduced ;
constraint int_eq_reif(X_INTRODUCED_105_,1,X_INTRODUCED_117_):: defines_var(X_INTRODUCED_117_);
constraint int_eq_reif(X_INTRODUCED_105_,2,X_INTRODUCED_119_):: defines_var(X_INTRODUCED_119_);
constraint int_eq_reif(X_INTRODUCED_103_,X_INTRODUCED_105_,X_INTRODUCED_128_):: defines_var(X_INTRODUCED_128_);
```
[median_string_median_p2_10_8_3.fzn.gz](https://github.com/MiniZinc/libminizinc/files/3761897/median_string_median_p2_10_8_3.fzn.gz)

Why are these variables introduced? They seem to be useless. Is this a compiler bug?

The Gecode model looks a bit different but it contains unconstrained search variables, too.

**Comment by guidotack** [comment]
These variables are not in fact unconstrained (but 2.3.1 and 2.3.2 didn't propagate the domains properly, in 2.4.0 you get `var 1..2: X_INTRODUCED_105_`). The variables are introduced as part of the decomposition of an if-then-else expression (as far as I can see, X_INTRODUCED_105_ is the result of the if-then-else in line 46 in the model).
