### ISSUE TITLE
minizinc does not kill child processes

### ISSUE THREAD

**Issue by jim-carciofini** [MiniZinc/libminizinc#337]
Minizinc often starts child processes (eg fzn-gecode).  When you kill (eg SIGTERM on Unix) the minizinc process it should also kill any child processes that are still running.  But it does not, it leaves them running.  This has been observed on Windows and macOS. I suspect it also happened on Linux.

**Comment by jim-carciofini** [comment]
Any opinions on this?  Is this something that is likely to get attention, or do I need to find a work around?

**Comment by cyderize** [comment]
This will be fixed in the next telease so that sending a SIGTERM to minizinc will make it kill child processes on Mac/Linux. On Windows, terminating a process does not give any chance of cleanup, so child processes will always remain (you would have to generate a Ctrl+C for the console minizinc is running in)

**Comment by jim-carciofini** [comment]
We are staring Minizinc from a program so Minizinc is not running in a console.  I am by no means a Windows systems programmer, but I think this is the mechanism Windows provides for this situation:  https://docs.microsoft.com/en-us/windows/win32/procthread/job-objects

**Comment by jim-carciofini** [comment]
Thanks for the pointer.  We are starting minizinc from another process, not a console.  I will look at using a JobObject on Windows.

**Comment by adamgoldfeld** [comment]
Is there any solution to this issue?

My use case:
1. In python, create an asycn task that calls minizinc.
2. Run task with asyncio.wait_for and use timeout
3. Wait for task to timeout while minizinc is still running.
4. After task is killed notice that minizinc process is killed but not the solver (i.e fzn-gecode).

**Comment by guidotack** [comment]
How is the MiniZinc task killed? If it's with a SIGKILL signal, there is no way for MiniZinc to terminate its child processes. You would have to use SIGINT or SIGTERM.

**Comment by glebbelov** [comment]
Or, put everything into a process group and then kill the group
