### ISSUE TITLE
arithmetic operation on infinite value

### ISSUE THREAD

**Issue by cottonty** [MiniZinc/libminizinc#341]
I'm trying to run cutting stock problem with COIN-BC solver but it gives the following error:

MiniZinc: evaluation error: 
/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/linear//redefinitions.mzn:205:
  in if-then-else expression
/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/linear//redefinitions.mzn:210:
  in if-then-else expression
  arithmetic operation on infinite value

there is no problem running with gecode solver (though it takes infinite time)

the model is modified from the example model found in the repository, the model and the original model and the data file are in the attachment

[Archive.zip](https://github.com/MiniZinc/libminizinc/files/3883401/Archive.zip)

**Comment by guidotack** [comment]
In order to use the linearisation library (for solver like CBC), you usually need to specify bounds for the variables. In this case, the items array doesn't have bounds, which causes this error. If you add suitable bounds (e.g. I think in your model_with_problem.mzn, L is a suitable upper bound for all items), it seems to be working.

**Comment by cottonty** [comment]
> In order to use the linearisation library (for solver like CBC), you usually need to specify bounds for the variables. In this case, the items array doesn't have bounds, which causes this error. If you add suitable bounds (e.g. I think in your model_with_problem.mzn, L is a suitable upper bound for all items), it seems to be working.

Thanks! But why does "cutstock.mzn" model work? It seems also do not have bounds on the "items" array?

**Comment by guidotack** [comment]
Because it doesn't contain the non-linear multiplication `items[k,i] * pieces[k]`. The compiler requires bounds to linearise this expression. All the constraints in cutstock.mzn are already linear.

**Comment by cottonty** [comment]
Thank you so much!
