### ISSUE TITLE
Where is mzn2fzn? Please revive it!

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#342]
Past releases of MiniZinc provided a `mzn2fzn` executable but recent releases do not provide it any more. That's a pity because it provides functionality `minizinc` does not have: `mzn2fzn` allows to generate models based on the standard library only while `minizinc` generates models for a given solver. Moreover, `mzn2fzn` and `minizinc` differ in the sematics of the `-I` command-line option: While `mzn2fzn` takes everything from the given include path and only falls back to the standard library for stuff not available on the given include path, `minizinc` behaves the other way around.

`mzn2fzn` is important for me because I use it in integration testing for my solver Yuck. Fortunately, `minizinc` still behaves like `mzn2fzn` when renamed to `mzn2fzn` or executed via a symbolic link named `mzn2fzn`. However, I am worried that the functionality might go away in the future.

Please revive `mzn2fzn` or make its functionality available via the command line of `minizinc`!

**Comment by guidotack** [comment]
You can use `minizinc -c --solver org.minizinc.mzn-fzn`

**Comment by informarte** [comment]
This works, thanks!
