### ISSUE TITLE
exp(X)

### ISSUE THREAD

**Issue by markwallacemonash** [MiniZinc/libminizinc#343]
I've written a model eliciting the error message "internal error: missing builtin 'exp'"

This is the model which led to the error:
var float: Obj;
constraint Obj in { exp(-F[i])  | i in 1..100} ;
array [1..1000] of float: F =  [(j  / 1000) | j in 0..999] ;
    solve     satisfy ;

...but this works:
var float: Obj;
constraint exists(i in 1..100)(Obj = exp(-F[i]));
%constraint Obj in { exp(-F[i]) | i in 1..100 } ;
array [1..1000] of float: F =  [(j  / 1000) | j in 0..999] ;
    solve     satisfy ;

**Comment by guidotack** [comment]
I've just added a few fixes on the develop branch to make this work (f37bbe2372493be6fe667aac1eb6e2bd7b3f16c2), should be part of the next release.
