### ISSUE TITLE
"Global functions" do neither mark defined variable nor defining constraint

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#345]
This issue is about the following functions defined by the MiniZinc library:

```
among_fn.mzn
bin_packing_load_fn.mzn
count_fn.mzn
distribute_fn.mzn
global_cardinality_closed_fn.mzn
global_cardinality_fn.mzn
inverse_fn.mzn
nvalue_fn.mzn
range_fn.mzn
roots_fn.mzn
sort_fn.mzn
```

These functions neither mark the defined variable nor the defining constraint. For example:

```
function var int: count(array[int] of var int: x, var int: y) ::promise_total =
  let { var 0..length(x): c; constraint count(x,y,c); } in c;
```

should be changed to:

```
function var int: count(array[int] of var int: x, var int: y) ::promise_total =
  let { var 0..length(x): c :: is_defined_var; constraint count(x,y,c) :: defines_var(c); } in c;
```
The bin_packing and global_cardinality functions are not that straight-forward because they define several variables at once. I guess for them one needs to introduce a new annotation, e.g. defines_vars, which takes an array of variables.

**Comment by guidotack** [comment]
I have added the annotations for the simple functions. For functions that return arrays, this is not possible in the current compiler (the defines_var annotations get some special treatment, which can't be replicated easily for array arguments).

**Comment by informarte** [comment]
Good enough for me!
