### ISSUE TITLE
Core dump for the model with -O3

### ISSUE THREAD

**Issue by krzku** [MiniZinc/libminizinc#352]
The following code triggers "Segmentation fault (core dumped)" of minizinc compiler.

array[1..5] of set of 1..20: x = [{}, {1}, {2,3}, {1,3}, {1,14}];
var set of min(ub_array(x))..max(ub_array(x)): r;

constraint
   card(r) = 2;

solve satisfy;
output["r = \(r)"]

This code is a simplified version of the code fragment from builtins.mzn at line 2388 that has similar effect on my bigger model.

/Kris

**Comment by a1880** [comment]
A similar error happens for the Windows binary of release 2.4.0 during compile.
Optimisation levels -O1 and -O2 work OK.

**Comment by guidotack** [comment]
There seem to be some issues with -O3 and set variables. I've pushed some fixes for this particular problem, but our test suite currently doesn't have enough coverage for either -O3 or set variables, so there may be other issues with more complex models.

**Comment by Dekker1** [comment]
This seems to work in MiniZinc 2.5.5
