### ISSUE TITLE
-O<n> with n > 1 is broken

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#357]
I tried minizinc -O2 on the old MiniZinc examples. I obtained a lot of internal errors and some complaints from Gecode about undefined variables.

`for f in *.mzn; do echo $f; minizinc -O2 $f; done &> gecode.log`

[gecode.log](https://github.com/MiniZinc/libminizinc/files/3975381/gecode.log)

**Comment by guidotack** [comment]
It looks like at least some of these issues have been there for quite a while (not just in the latest 2.4.0 release). At least for -O2 it should be working now (with a bug fix release coming soon).

**Comment by informarte** [comment]
I tried the develop branch and -O2 seems to work now.

However, I am now experiencing a weird problem that only occurs when I call minizinc from the JVM and when I use both -v and -O2 like this:

```
minizinc -v -O2 -c --solver org.minizinc.mzn-fzn -I resources/mzn/lib/yuck --no-output-ozn --output-fzn-to-file tmp/examples/alpha/problem.fzn resources/mzn/examples/problems/alpha.mzn
```
Then minzinc does nothing and just goes into sleep state:

```
> ps -el  |grep minizinc
0 S  1000 13458 13432  0  80   0 -  6932 pipe_w pts/3    00:00:00 minizinc
```

The problem does not occur
- when I execute the above command from bash,
- or when I omit -O2,
- or when I omit -v.

Any idea? Might it be a problem on my side?

**Comment by guidotack** [comment]
Any chance you could compile minizinc as a debug build, attach a debugger to the running process, interrupt it and see where it's waiting? It's a bit strange, I could only imagine that it's somehow waiting for input from STDIN, but with the arguments you give it shouldn't be doing that.

**Comment by informarte** [comment]
I understood the problem; it was a deadlock caused by consuming minizinc's stdout before its stderr: While the Java process was waiting for EOF on minizinc's stdout, minizinc -v -O2 printed more lines to stderr than the buffer could hold and so minizinc got blocked.

https://stackoverflow.com/questions/16983372/why-does-process-hang-if-the-parent-does-not-consume-stdout-stderr-in-java/16983563#16983563
