### ISSUE TITLE
-O2 sometimes renames output variables

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#360]
```
cd minizinc-benchmarks/project-planning
minizinc -c -O2 ProjectPlannertest_12_7.mzn
```
minizinc introduces a new output variable:
```
var 0..1: X_INTRODUCED_138_:: is_defined_var:: output_var;
```
The .ozn file uses its value to print the value of the problem variable `ite2`:
```
int: X_INTRODUCED_138_;
int: ite2 = X_INTRODUCED_138_;
```
`ite2` itself does not occur in the FlatZinc model.

This is not really a bug but unexpected and it breaks my tooling for verifying the solutions of Yuck.

Please avoid renaming of output variables!

**Comment by informarte** [comment]
The above problem even occurs with `--no-output-ozn`.

**Comment by informarte** [comment]
I recently started to think about how to combine two or more FlatZinc solvers into one, at the same time competing but also exchanging solutions and bounds. The idea is to generate solver-specific FlatZinc models for the same instance and to pass the FlatZinc models to the meta solver which then runs the solvers in different threads and facilitates the communication between them. To make this approach work, the FlatZinc models must share the output variables.

**Comment by guidotack** [comment]
In the current architecture of the compiler it is not possible to avoid introducing renamed variables. The entire architecture assumes that the compiler is allowed to perform arbitrary model transformations as long as it also produces the corresponding reverse transformations in the ozn model.

If you need to identify variables across compilations, you may want to use path information, which can uniquely identify a variable, independent of the concrete solver library used etc. That's how multi-pass (e.g. -O2) flattening is implemented. Have a look at the output generated when compiling with `--keep-paths`.

**Comment by glebbelov** [comment]
It's not only renaming, it's also redefining. Some CP solvers use std/nosets.mzn to channel set variables and constraints into booleans. MIP solver go further - normally all booleans become ints.

To keep track of this relatively easy one can use search or warmstart annotations: https://www.minizinc.org/doc-2.4.2/en/mzn_search.html#sec-warm-starts. Such an annotation, added to the solve item, will be converted according to the actual solver, keeping the order of the variables. Then care must be taken with boolean and set variables.
