### ISSUE TITLE
"no minizinc executable" under macOS 10.13.6

### ISSUE THREAD

**Issue by pierfle** [MiniZinc/libminizinc#363]
First, thanks for all the nice new features & corrections on v2.4.*!

Alas, I cannot install the binary bundles for v2.4.* (declared to work under macOS 10.9 or later) on my old laptop, which cannot be upgraded beyond macOS High Sierra 10.13.6.   I get "Could not find the minizinc executable. Do you want to open the settings dialog?"  and then the following (here comes a screenshot as the text is not selectable):
![no-minizinc-executable](https://user-images.githubusercontent.com/14176941/72129824-e4bdf300-3377-11ea-879b-4a60e4483a13.png)
Should I install by compilation, or do you easily see how to fix this?

**Comment by Dekker1** [comment]
Hi Pierre,

I'm afraid that the claim that MiniZinc works for macOS 10.9+ not correct anymore and should be updated. The MiniZinc executables are linked using the newest version of XCode / macOS and the error message that you showed seemed to suggest that this requires a newer version of macOS to execute. I'm surprised, though, that a reasonably current version of macOS is no longer compatible and I will look into it. I don't have any quick solution I'm afraid, so compiling the executable yourself will be the quickest option.

**Comment by Dekker1** [comment]
I just went through the CMake configuration and it turns out we are setting the `CMAKE_OSX_DEPLOYMENT_TARGET` at the wrong time. I've created a fix which will hopefully solve the problem. Maybe we will rerelease the macOS package for 2.4.2 if it solves the problem.

**Comment by Dekker1** [comment]
A new version of the MiniZinc bundle for macOS has been uploaded that should solve this issue: https://github.com/MiniZinc/MiniZincIDE/releases/tag/2.4.2
