### ISSUE TITLE
Declaring arrays with unknown length

### ISSUE THREAD

**Issue by jarble** [MiniZinc/libminizinc#368]
It seems that the MiniZinc compiler is sometimes unable to infer the lengths of arrays, even if they are specified in a constraint. Here, there are two arrays that should have the same length:

```
array[int] of var int:A0;
array[int] of var int:A1;
constraint (length(A1) == 3 /\ A0 == A1);
solve satisfy;

% Compiling untitled_model.mzn
% MiniZinc: flattening error: 
%   array dimensions unknown
```

This error also occurs when I try to initialize an array in a constraint:

```
array[int] of var int:A0;
array[int] of var int:A1;
constraint (A1 == [1,2,3] /\ A0 == A1);
solve satisfy;
```

It seems that this model won't compile unless the lengths are specified in each variable's declaration, like this:

```
array[1..3] of var int:A0;
array[1..3] of var int:A1;
constraint  (A1 == [1,2,3] /\ A0 == A1);
solve satisfy;
```

Is it possible to declare arrays so that the compiler can infer their lengths, instead of specifying the length in each variable declaration?

**Comment by guidotack** [comment]
This would be a fundamental change to the language, making arrays variable length. Most solvers would not be able to handle variable length arrays directly, and I can't see a translation into fixed-length arrays and "standard" constraints without having at least bounds on the array length. An additional complication is that while in your first example you constrain the length, you don't constrain the index set.
The design choice that was made in MiniZinc was that array index sets need to be par expressions, and initialised at compile time. Your second example would almost work, if you replaced the constraint by two assignments:
```
A1 = [1,2,3];
A0 = A1;
```
An assignment is different from a constraint in that it provides a syntactic guarantee that it can be evaluated at compile time. Constraints can't provide that guarantee (e.g. an expression like `A1=[1,2,3] \/ A0=A1` would be a completely different thing).

**Comment by jarble** [comment]
It seems that the compiler would need to transform a constraint into a series of variable assignments to solve this problem. This only works if the constraint is a conjunction of comparisons, so the example above could be re-written in this way:
```
array[int] of var int:A0;
array[int] of var int:A1;
A1 == [1,2,3];
A0 == A1;
solve satisfy;
```

**Comment by jarble** [comment]
@guidotack: Although MiniZinc doesn't support variable-length arrays, they can easily be simulated using constraints like this one:

```
function var int: infinite_array(var int:ID, var int:index) = let {var int: result;} in result;

var int: array_ID; % associate each "array"

%define some values at each "index" of the array
constraint infinite_array(array_ID,0) == 1;
constraint infinite_array(array_ID,1) == 2;

%retrieve some values from the "array"
var int: result = infinite_array(array_ID,0) + infinite_array(array_ID,1);

solve satisfy;

output [show(result),"\n"];
```

**Comment by Dekker1** [comment]
This is actually not correct. Although it is not checked, the results of functions in MiniZinc must be defined by their arguments for the function to have the correct behaviour. When you allow the `var int` as the identifier or index, this is not the case. As such you can have two variables that resolve to the same identifier value (or the same index value), but they will have unconnected results. This is illustrated by the following model:

```
function var int: infinite_array_length(var int:ID) = let {var int: result;} in result;

var 1..10: a;
var 1..10: b;

any: lenA ::output = infinite_array_length(a);
any: lenB ::output = infinite_array_length(b);

constraint lenA != lenB;
constraint a < 2;
constraint b < 2;
```

**Comment by jarble** [comment]
@Dekker1 I don't see any incorrect behaviour in the model above: since `a` and `b` would represent two different "arrays", I would expect `infinite_array_length(a)` to be different from `infinite_array_length(b)`.

If I try to set a value at an index that is greater than the array's maximum length, MiniZinc (correctly) detects an inconsistency here:
```
function var int: infinite_array(var int:ID, var int:index) = let {var int: result; constraint index >= 0 /\ index < infinite_array_length(ID);} in result;
function var int: infinite_array_length(var int:ID) = let {var int: result;} in result;

var int: array_ID;

constraint infinite_array(array_ID,3) == 1;

constraint infinite_array_length(array_ID) < 2;
var int: L = infinite_array_length(array_ID);

solve satisfy;

output [show(L),"\n"];```

**Comment by Dekker1** [comment]
The point is that normally `a` and `b` are expected to represent the same value when they take the same `ID` value, but that this is not guaranteed by the function definition in MiniZinc. As such, this is not actually a "function" in the mathematical sense.

This then also means that the behaviour is dependent on the order in which it is evaluated, and this can lead to many unexpected behaviour. For example a slight variation of my original model is unsatisfiable:

```
function var int: infinite_array_length(var int:ID) = let {var int: result;} in result;

var 1..10: a;
var 1..10: b;

constraint a < 2;
constraint b < 2;

constraint infinite_array_length(a) != infinite_array_length(b);
```
