### ISSUE TITLE
set_lt seems to implement subset relation

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#369]
From the MiniZinc handbook:

```
predicate set_lt(var set of int: x, var set of int: y)
```

_Constrains x < y (lexicographic order of the sorted lists of elements)_

However, it seems that `set_lt` implements the subset relation:

- `set_lt({}, {0, 1})`
- `set_lt({0}, {0, 1})`
- `set_lt({1}, {0, 1})`

are satisfiable but

- `set_lt({0, 1}, {1})`
- `set_lt({0, 1}, {1, 2})`
- `set_lt({0, 1}, {0, 2})`

are unsatisfiable.

These results were obtained with MiniZinc 2.4.2 and Gecode. (Chuffed often died due to an assertion from nosets.mzn.)

**Comment by guidotack** [comment]
You are right, however this is a bug in Gecode, not in MiniZinc.

**Comment by cyderize** [comment]
The issue with `nosets.mzn` is a bug in that library and will be fixed on the develop branch soon, which should fix the problem for Chuffed.

**Comment by informarte** [comment]
This issue also affects `lex_less` and `lex_lesseq` for sets.
