### ISSUE TITLE
Increasing & decreasing constraints give incorrect result on set variables when solved with Gecode

### ISSUE THREAD

**Issue by toanphan19** [MiniZinc/libminizinc#373]
Applying the `increasing` global constraint on an array of set variables makes the array have a decreasing order when using the Gecode solver, and the inverse is true with the `decreasing` constraint. The program
```
array[1..3] of var set of 1..3: Set;

constraint forall(i in 1..3) (card(Set[i]) = 2);
constraint alldifferent(Set);
constraint increasing(Set);
```
gives the incorrect result of `[2..3, {1,3}, 1..2]` when solved with either Gecode 6.1.1 or Gecode 6.2, whereas both the Chuffed solver and Google's OR-Tools give a result of `[1..2, {1,3}, 2..3]`.

**Comment by cyderize** [comment]
This is the same problem as #369. Gecode's implementation of set inequality does not match the current specification (although it is a total ordering, so you can still use this for symmetry breaking purposes).

You can get the correct behaviour if you add `include "nosets.mzn";` which won't use Gecode's built-in set predicates - however this could potentially make solving much slower.
