### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [MiniZinc/libminizinc#376]
I would like to point out that identifiers like “[`__MINIZINC_PLUGIN_HH__`](https://github.com/MiniZinc/libminizinc/blob/44bdb9bfc7e51e1206edd7d2f37a048d40197e5b/include/minizinc/plugin.hh#L11 "Update candidate")” and “[`__MZN_PRINT_SRCLOC`](https://github.com/MiniZinc/libminizinc/blob/879e7958f5fc9c05e2a3a9b20fa2b0de44077183/include/minizinc/utils.hh#L48 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Dekker1** [comment]
Thank you for the feedback @elfring. I've switched the code-base to use `#pragma once` instead. It seems the more modern approach

**Comment by elfring** [comment]
>I've switched the code-base to use `#pragma once` instead.

[This construct is also not standard compliant](https://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#answer-23699893 "Is #pragma once part of the C++11 standard?").


>It seems the more modern approach

Are you going to [use C++ modules](https://en.cppreference.com/w/cpp/language/modules "Supporting C++ modules")?

**Comment by guidotack** [comment]
We will not move to C++20 any time soon.
