### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [MiniZinc/libminizinc#378]
Would you like to [wrap any pointer data members](https://github.com/MiniZinc/libminizinc/blob/44bdb9bfc7e51e1206edd7d2f37a048d40197e5b/lib/flatten.cpp#L567 "Update candidate: EnvI class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by Dekker1** [comment]
Although I am all for the usage of the modern smart pointers. For MiniZinc it is not as simple as just replacing pointers with `std::unique_ptr`. Pointer members in the driving structures are often passed around and replaced and part of the library is garbage collected. Using unique ptr would require refactoring so only references are passed around, replacements need to be handled correctly, and we need to have a good look where it would make sense.
