### ISSUE TITLE
Wrong version numbers in 2.04 and 2.06?

### ISSUE THREAD

**Issue by jorgengz** [MiniZinc/libminizinc#38]
After downloading and installing the 2.04 and 2.06 distributions for OSX from
http://www.minizinc.org/
and
http://www.minizinc.org/2.0/install-mac.html
and running
$ minizinc --version
the output is
G12 MiniZinc evaluation driver, version 2.0.3

**Comment by guidotack** [comment]
This is only the version of the evaluation driver, not of MiniZinc itself.  I agree it's confusing, and I'll upload new packages that display the current MiniZinc version instead for the next release.  To check the actual version of the MiniZinc installation you're using, you can use mzn2fzn --version instead.

**Comment by jorgengz** [comment]
Aha, thanks for clarifying!
