### ISSUE TITLE
Missing annotations in FZN when compiled for MIP solvers

### ISSUE THREAD

**Issue by ilansen** [MiniZinc/libminizinc#381]
In some cases, annotations disappear from the FZN file when compiled with linear libraries. Two simple models of such cases are given below:
(1)
array[1..2,1..2] of var 0..1: nPos;
array[1..2,1..2] of var 0..1: bSep;
constraint ::"test" 
forall(i in 1..2, j in 1..2)(
  (bSep[i,j]==1 -> nPos[i,j]==1) ::"\(i);\(j)"
);

(2)
array[1..2,1..2] of var 0..1: nPos;
array[1..2,1..2] of var 0..1: bSep = array2d(1..2,1..2,[
  (let {
    array[int] of var int: bSep = [
      let {var 0..1: bk,
      constraint :: "in_constraint" (bk==1 -> nPos[iEZ,k]==1) :: "in_test"} in bk
    | k in 1..2],
    constraint :: "out_constraint" (1 == sum(bSep)) :: "out_test"
  }
  in
   bSep)[k]
| iEZ in 1..2, k in 1..2]);

**Comment by Dekker1** [comment]
This issue seems to have been resolved in recent versions of MiniZinc
