### ISSUE TITLE
MZN 2.4.3: still bug with logical ops

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#391]
This model:
```
var 0..1: D;
constraint
    not((false /\ D=0) \/ false);
solve satisfy;
```
should have two solutions: `D=0` and `D=1`; MiniZinc finds only `D=1`.

**Comment by zayenz** [comment]
Using MiniZinc IDE 2.4.3 on macOS Catalina and the Gecode solver configured for finding all solutions, both solutions are found.

![Screenshot 2020-05-18 at 11 46 57](https://user-images.githubusercontent.com/245350/82199070-809ad500-98fd-11ea-8ba8-2dd6033b7fab.png)

Similar result with Chuffed.

**Comment by matsc-at-sics-se** [comment]
By bad, I have too many versions installed at once. Will try to close.
