### ISSUE TITLE
adding constraints improves optimal objective

### ISSUE THREAD

**Issue by samiller25** [MiniZinc/libminizinc#393]
The attached school.zip file contains a model and data file which has the behavior that when I add constraints, the reported **optimal** solution improves.  That's clearly a bug, but I don't know whether it's a bug in the MiniZinc compiler or in the OR-Tools solver.

I am using MiniZinc IDE version 2.4.3 and OR-Tools Flatzinc version 7.6.7691 on Windows 10 -- both of these are the latest version as of this report.  I run the solver with 8 threads.

The constraints in question are on lines 140-162 of school.mzn.  Those lines comprise five constraints.  If all the constraints are commented out, the optimal solution has objective value 100 (the objective is being maximized).
- Uncommenting the first constraint does not change the solution.
- Uncommenting the first two constraints, the problem is reported as unsatisfiable.
- Uncommenting the first three constraints, the optimal value is 300.
- Uncommenting the first four constraints, the optimal value is again 300.
- Uncommenting all constraints, the optimal value is 500.

How can I tell whether this is the fault of MiniZinc or OR-Tools?

By the way, I've tried solving this with Gecode, but it does not produce any solutions in a reasonable amount of time.

[school.zip](https://github.com/MiniZinc/libminizinc/files/4672769/school.zip)

**Comment by Dekker1** [comment]
To diagnose if the problem is located in the solver or in MiniZinc it is indeed a good plan to check how other solvers behave. If Gecode is not solving the problem fast enough, then try Chuffed or CBC. Generally if OR-Tools is performing well, I would expect Chuffed to perform similarly.

**Comment by samiller25** [comment]
I tried both Chuffed and COIN-BC, and neither returned any result in 8 hours.  Also, I tried OR-Tools single-threaded, and it didn't return any result in 5 1/2 hours.  That's baffling, because OR-Tools running in 8 threads reaches "optimality" in a few minutes.

Since the default COIN-BC configuration in the IDE allows for multiple threads, I tried setting it to 8 threads, but the option was not recognized by the solver.

Are there any other suggestions for how to proceed?

**Comment by krzku** [comment]
You can try to copy the results obtained from or-tools (the original results, not formated) and add them to your dzn file. Then you can try to compile it and possibly run it with Gecode to check if either minizinc compiler or Gecode will report unsatisfiability.

**Comment by glebbelov** [comment]
This is facilitated by the option --output-mode dzn which automatically outputs all variables without a rhs

**Comment by samiller25** [comment]
There is no question that the problem is satisfiable.  The solutions returned by or-tools are indeed feasible (I can tell just by inspection) -- the problem is that they are not optimal.  Either the solver is stopping prematurely, erroneously declaring optimality or unsatisfiability, or the flatzinc model is incorrect.

**Comment by krzku** [comment]
OK, if the results are correct you can try to define your own search strategy by adding a search annotation based on your knowledge of the problem and try other solvers. Default strategy for your problem might be very inefficient for your problem.

**Comment by samiller25** [comment]
I have tried adding search annotations, but I don't really know what I'm doing with those, and I haven't had much success with them in improving runtime dramatically.

I did manage to save the solution with objective value 500 (from the model with the 5 constraints uncommented) in a dzn file as @glebbelov suggested.  Then I fed that as a data file to the model with the 5 constraints commented out (which claimed to have a worse optimal value of 100).  Using the gecode solver it returned the same solution immediately.  Using the or-tools solver, it crashed:

```Check failed: Argument::INT_VAR_REF == (yyvsp[0].arg).type (4 vs. 0)
*** Check failure stack trace: ***
    @   00007FF7B73C36EB  (unknown)
    @   00007FF7B73C2B89  (unknown)
    @   00007FF7B7459B46  (unknown)
    @   00007FF7B73DF387  (unknown)
    @   00007FF7B73B6C84  (unknown)
    @   00007FF7B73B7F60  (unknown)
    @   00007FF7B79CA830  (unknown)
    @   00007FF9BA907BD4  BaseThreadInitThunk
    @   00007FF9BC2ECE51  RtlUserThreadStart
=====ERROR=====
```

I don't know if it's conclusive, but evidence seems to point to or-tools as the source of the problem.  Is the same FlatZinc file passed to or-tools and to gecode, or is the model compiled differently for different solvers?

**Comment by glebbelov** [comment]
The FlatZinc is in general different because every solver can provide its own redefinitions library and Gecode and or-tools do. You get different FZN when the model uses global constraints, such as alldifferent, which are redefined by a library.

Yes this points to or-tools. You can submit a bug report to them.
