### ISSUE TITLE
Running minzinc with timeout will not show intermediate solutions

### ISSUE THREAD

**Issue by telebog** [MiniZinc/libminizinc#397]
![image](https://user-images.githubusercontent.com/7736319/84694355-5b73a380-af49-11ea-8370-cbe7ffccdd49.png)

There are a few intermediate solutions that are displayed when I use -a option. Without this option I get =====UNKNOWN=====

**Comment by reubenkaiser** [comment]
I'm having a issue that seems to be identical to this. Running my instance in the IDE gives the optimal solution within the time limit. Running the same instance, using the same param file leads to no solution.

**Comment by Dekker1** [comment]
@reubenkaiser This sounds like a different issue. Could you open a different issue with the model instance and the parameter file so we can try and reproduce the problem?
