### ISSUE TITLE
Output sum over set var gives "invalid set literal type" (Gurobi solver)

### ISSUE THREAD

**Issue by fbrandt** [MiniZinc/libminizinc#398]
Hi there,

I just ran into an issue when upgrading from MiniZinc 2.3.1 to 2.4.3. In the output section, summing over a set var does not work anymore. At least for Gurobi - with the default solver it works on 2.4.3 and with Gurobi it also worked on 2.3.1.

Example model:
```
enum ITEM = {'A', 'B', 'C'};
array[ITEM] of int: value = [1, 2, 3];
var set of ITEM: loaded;
var int: total_value = sum(i in loaded)(value[i]);
constraint card(loaded) <= 2;
solve maximize total_value;
output [ show(total_value) ];
```

Using Gurobi solver, I get the following error message:
```
> minizinc.exe --solver org.minizinc.mip.gurobi test.mzn
Error when evaluating an intermediate solution:
MiniZinc: internal error: invalid set literal type
```

Using the default solver works. Also just printing ```show(loaded)``` works.

Is there a mistake on my side? I did not find anything in the changelog.

Thanks & Cheers,
Felix

**Comment by fbrandt** [comment]
FYI: found a work-around (not nice, but at least running):
```
output [ show(sum(i in fix(loaded))(value[i])) ];
```

**Comment by a1880** [comment]
The same error is shown for `CPLEX` and `COIN-BC`. But other solvers do not complain.
