### ISSUE TITLE
subset constraint lost when using nosets redefinitions

### ISSUE THREAD

**Issue by kfranc** [MiniZinc/libminizinc#4]
When I compile the following using mzn2fzn 2.0.1 and the 'nosets' redefinitions.mzn file provided with this version, the subset constraint is lost (if I run it I get an answer of 10).

    var set of 1..10: s1;
    constraint s1 subset {1,4,10};
    var bool: fourin = 4 in s1;
    solve :: set_search([s1],input_order,indomain_min,complete)
     maximize card(s1);

Note that if I remove the third line, where ``fourin`` is declared, then it works (gives answer 3).

**Comment by guidotack** [comment]
Thanks for the report. The bug seems to be already fixed in the current develop branch (although I can't say which change actually fixed this problem). We will release a bugfix update soon.
