### ISSUE TITLE
No function `var set of int: array_union(array[int] of var int)`

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/libminizinc#410]
As far as I can see, there is no function `var set of int: array_union(array [int] of var int: x)`, which I would have expected to be available.

Consider the following simple model

```
int: n = 4;
array[1..n] of var 1..n: x;
var set of 1..n: values;

constraint values = array_union([{x[i]} | i in 1..n]);

solve :: int_search(x, input_order, indomain_random) satisfy;
```

I would have expected to be able to write the constraint as `constraint values = array_union(x);`.

Perhaps there is another name for that constriant? Otherwise, while the re-write above is fully doable, it feels like the suggested constraint should be available.

**Comment by guidotack** [comment]
In the very soon to be released 2.5.0 you can write

`constraint values = { s | s in x};`

(or equivalently `{ x[i] | i in 1..n }`)

**Comment by zayenz** [comment]
Thanks, and that is a very nice construction. 

I would like to note though that I think it is not very discoverable for a new user, and I think that a named function could be a good idea as well.

**Comment by Dekker1** [comment]
The new syntax seems to make the proposed `array_union` version unnecessary. I'll close this issue.
