### ISSUE TITLE
minizinc 2.5.0 classifies satisfiable carpet-cutting instances as unsatisfiable

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#412]
I noticed an issue with a couple of carpet-cutting instances from the minizinc-benchmarks library:

```
minizinc cc_base.mzn mzn_rnd_test.02.dzn 

  WARNING: model inconsistency detected: domain is empty
  cc_base.mzn:256:
  in call 'cumulative'
  cc_base.mzn:259:
  in binary '++' operator expression
  cc_base.mzn:100:
  in variable declaration for 'st_rec_wid'
=====UNSATISFIABLE=====
```

This issue affects the instances 02, 11, and 12, which are all solvable with earlier MiniZinc versions.

**Comment by guidotack** [comment]
This seems to be already fixed by a6f676b9. Update coming soon.
