### ISSUE TITLE
Missing documentation for annotations in reference

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/libminizinc#417]
At https://www.minizinc.org/doc-2.5.0/en/lib-annotations.html there are no annotation documentation, as compared with https://www.minizinc.org/doc-2.4.3/en/lib-annotations.html.

Unsure if this is the right place to report this issue.

**Comment by guidotack** [comment]
Thanks, will be fixed in 2.5.1.

**Comment by pierfle** [comment]
This was independently reported as https://github.com/MiniZinc/minizinc.github.io/issues/26 : is that tracker not monitored (frequently), and do you prefer documentation issues to be reported in this libminizinc one?
