### ISSUE TITLE
Error when compiling tower.mzn

### ISSUE THREAD

**Issue by krzku** [MiniZinc/libminizinc#420]

**Comment by krzku** [comment]
MiniZinc version 2.5.1 it does not compile tower.mzn model from MiniZinc challenge 2020. It worked perfectly with the previous version... The error message is

MiniZinc: evaluation error: 
  tower.mzn:16:
  in variable declaration power
  cannot evaluate expression 'power'

/Kris

**Comment by zayenz** [comment]
Same issue as #418

**Comment by Dekker1** [comment]
Thank you @zayenz. I'll close this issue, so we can track it just in #418
