### ISSUE TITLE
"Config exception: no solver selected" when running a basic example from the tutorial

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#422]
I installed 2.5.1 and it fails on a simple example:
```
$ minizinc test.mzn 
Config exception: no solver selected
minizinc: MiniZinc driver.
```

The example from the tutorial (https://www.minizinc.org/doc-2.5.1/en/basic_steps.html) doesn't work without specifying a solver.

Perhaps the tutorial should mention this, or the ```minizinc``` should choose some solver as default.

**Comment by Dekker1** [comment]
It seems like your version of MiniZinc is misconfigured. MiniZinc sets a default solver in `share/minizinc/Preferences.json`. If correctly installed, then the solver should correctly be set when executing the given command.
