### ISSUE TITLE
Model that tries to compare arrays gets internal error without reference to where/what is wrong

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/libminizinc#428]
Given the model
```
array[1..2, 1..2] of var bool: x;
constraint x[1, ..] < x[2, ..];
solve satisfy;
```
the minizinc compiler outputs
```
running untitled_model.mzn
MiniZinc: internal error: Operator not yet implemented
Process finished with non-zero exit code 1
Finished in 54msec
```
In a larger model, it is quite hard to know what operator is not implemented, and where it is used.

**Comment by guidotack** [comment]
Right, the comparison operators on arrays are defined in the library as built-ins, but they're not actually implemented.
