### ISSUE TITLE
MiniZinc 2.5.2 reports an error when applied to a ground sdn-chain instance

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#436]
When applied to a ground sdn-chain instance, Gecode from MiniZinc 2.5.2 reports an error.

[d10n780-1.tar.gz](https://github.com/MiniZinc/libminizinc/files/5578006/d10n780-1.tar.gz) contains everything to reproduce the issue.

Reproduction steps:

```
tar xzf d10n780-1.tar.gz
cd d10n780-1
minizinc -I . solution.mzn d10n780-1.dzn
```

Expected output and what Gecode from MiniZinc 2.5.0 as well as Chuffed from MiniZinc 2.5.2 produce:

```
vnf_match = array1d(1..5, [57, 470, 524, 413, 537]);
domain_path = array2d(1..10, 1..10, [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1]);
selected_domain = array1d(1..10, [1, 1, 1, 1, 1, 1, 1, 1, 0, 1]);
selected_nodes = array1d(1..750, [...]);
link_selection = array1d(1..1570, [...]);
n_fun_nodes = 5;
objective = 173;
----------
==========
```

Actual output:

```
=====ERROR=====
```

I am reporting this as a MiniZinc issue because it seems that MiniZinc 2.5.0, 2.5.1, and 2.5.2 all use Gecode 6.3.0 under the hood.

(MiniZinc 2.5.1 cannot flatten this problem because of an issue that has already been fixed.)

**Comment by guidotack** [comment]
This was indeed a bug in Gecode (the version number should have been reported as Gecode 6.3.0beta, since the 6.3.0 release is not final yet but we decided to include it in MiniZinc because it had quite a few fixes compared to the previous version). I have pushed a fix to the Gecode repository, and the fix will be included in MiniZinc 2.5.3.
