### ISSUE TITLE
Enum constructors must have single identifier error for JSON parameters

### ISSUE THREAD

**Issue by philzook58** [MiniZinc/libminizinc#441]
I'm trying to use json to load in parameters. The params file and model works in 2.4.3 but are now throwing the following error for 2.5.3. I haven't been able to figure out what this error means or how to fix it. Perhaps the format has changed?

https://gist.github.com/philzook58/93d2b7c53ba2ac5fbb0b7cb1e3c0b6c4 

```
$ minizinc  resources/exparam.json resources/model.mzn 
unknown file:0.0:
MiniZinc: type error: enum constructors must have a single identifier as argument
```

Any help would be appreciated.

Thanks,
Phil

**Comment by cyderize** [comment]
It looks like there might be a bug with the automatic coercion of JSON list types.

Using sets for the the enum definitions fixes the problem for now:

```json
    ...
    "reg_t": {"set": [
        {
            "e": "r0"
        },
        {
            "e": "r1"
        },
        {
            "e": "r2"
        },
        {
            "e": "r3"
        },
        {
            "e": "r4"
        },
        {
            "e": "r5"
        }
    ]},
    ...etc
```

**Comment by philzook58** [comment]
Thanks, that adjustment worked for me
