### ISSUE TITLE
Chuffed error with optimization levels -O4 and -O5 

### ISSUE THREAD

**Issue by markwallacemonash** [MiniZinc/libminizinc#445]
MiniZinc IDE 2.5.3
Chuffed 0.10.4*
=====ERROR=====
Process finished with non-zero exit code 1
Finished in 54m 42s
Files
[Wyndham full - Copy.mzn.txt](https://github.com/MiniZinc/libminizinc/files/5726319/Wyndham.full.-.Copy.mzn.txt)
[6 routes data_separate RT  - Copy.dzn.txt](https://github.com/MiniZinc/libminizinc/files/5726322/6.routes.data_separate.RT.-.Copy.dzn.txt)

**Comment by Dekker1** [comment]
This error seems to occur in Chuffed, not in MiniZinc. I've opened a new issue in the Chuffed repository with the information to track it and will close this one.
