### ISSUE TITLE
Minizinc error on linux installed from source code

### ISSUE THREAD

**Issue by jam7** [MiniZinc/libminizinc#447]
Hi,

Thank you for releasing Minizinc.

I have a problem if I compile minizinc from source code on ubuntu.  I appreciate if someone let me know a direction to inspect my problem.

Problem is that the minizinc shows compile error in following simple example taken from handbook.
```
include "alldifferent.mzn";

var 1..9: S;
var 0..9: E;
var 0..9: N;
var 0..9: D;
var 1..9: M;
var 0..9: O;
var 0..9: R;
var 0..9: Y;

constraint           1000 * S + 100 * E + 10 * N + D
                   + 1000 * M + 100 * O + 10 * R + E
       = 10000 * M + 1000 * O + 100 * N + 10 * E + Y;

constraint alldifferent([S,E,N,D,M,O,R,Y]);

solve satisfy;

output ["   \(S)\(E)\(N)\(D)\n",
        "+  \(M)\(O)\(R)\(E)\n",
        "= \(M)\(O)\(N)\(E)\(Y)\n"];
```
https://www.minizinc.org/doc-2.5.3/en/modelling2.html?highlight=alldifferent#ex-smm

Minizinc shows following error message:
```
$ minizinc tp1.mzn
/home/jam/.local/share/minizinc/std//at_most.mzn:23.5-44:
MiniZinc: type error: no function or predicate with this signature found: `fzn_at_most_set_reif(int,array[$_] of var set of int,array[int] of int,var bool)'
Cannot use the following functions or predicates with the same identifier:
predicate fzn_at_most_set_reif(int: n,array[int] of var set of int: x,set of int: v,var bool: b);
    (argument 2 expects type array[int] of var set of int, but type array[$_] of var set of int given)
    (argument 3 expects type set of int, but type array[int] of int given)
```

This problems happens only on ubuntu.  It works fine if I compile everything on e.g. macos.  Even on ubuntu, it works fine before 0d0b72e which reworks std library.  0d0b72e changes nvalue.mzn changes like below:
```
diff --git a/share/minizinc/std/nvalue.mzn b/share/minizinc/std/nvalue.mzn
index 2094a434..5e7c54a6 100644
--- a/share/minizinc/std/nvalue.mzn
+++ b/share/minizinc/std/nvalue.mzn
@@ -4,5 +4,5 @@ include "fzn_nvalue_reif.mzn";
 /** @group globals.alldifferent
   Requires that the number of distinct values in \a x is \a n.
 */
-predicate nvalue(var int: n, array[int] of var int: x) =
-       fzn_nvalue(n, x);
+predicate nvalue(var int: n, array[$X] of var int: x) =
+       fzn_nvalue(n, array1d(x));
```

So, it looks like minizinc parser doesn't run correctly with `array[$X]` styled source code on ubuntu.  I guess some differences on compiler and other tools I used to compile minizinc are causing this error.  So, I try to update bison and flex on ubuntu, but it doesn't help.  Any suggestions are appreciated.

**Comment by glebbelov** [comment]
Perhaps similar: when running `minizinc -v -s --solver gecode` on Kubuntu 20.04 wiht Gecode 6.2.0 and MZN @d807428bafe4bc7cd5b3cf8700ff7a82018433fa and a model just saying `include "globals.mzn"`; I get

```
Flattening ...
        CompilePass: Flatten with '/home/bg25/Documents/prj/minizinc/share/minizinc//' library ...

/home/bg25/Documents/prj/minizinc/share/minizinc/std//nvalue_fn.mzn:7.57-67:
MiniZinc: type error: no function or predicate with this signature found: `nvalue(var int,array[$_] of var int)'
Cannot use the following functions or predicates with the same identifier:
function var int : nvalue(array[$_] of var int: x);
    (requires 1 argument, but 2 given)
predicate nvalue(var int: n,array[int] of var int: x);
    (argument 2 expects type array[int] of var int, but type array[$_] of var int given)
```

**Comment by jam7** [comment]
Hi, I've checked this issue with the latest 2.5.5.  And, I've found that this problem is fixed.  Moreover, this problem is fixed not only on 2.5.5 but also on 2.5.3 which I had this problem before.  So, I guess compiler tools or something on ubuntu are fixed.  Sorry for not pointing it out.  I'm closing this issue since it is fixed at my side.  @glebbelov, please check it at your side also.

**Comment by xgillard** [comment]
I've got this exact same issue :-/ on arch linux.

I compiled gecode (6.2.0) and libminizinc (2.5.5). Added a config file to use gecode as a solver but I end up with the following error:
```
~/xgi/minizinc/share/minizinc/std/nvalue_fn.mzn:7.57-67:
MiniZinc: type error: no function or predicate with this signature found: `nvalue(var int,array[$_] of var int)'
Cannot use the following functions or predicates with the same identifier:
function var int : nvalue(array[$_] of var int: x);
    (requires 1 argument, but 2 given)
predicate nvalue(var int: n,array[int] of var int: x);
    (argument 2 expects type array[int] of var int, but type array[$_] of var int given)
```

**Comment by cyderize** [comment]
Gecode 6.2.0 uses an old library format which is no longer compatible. Try compiling Gecode using the `develop` (or the `release/6.3.0`) branch and see if the problem goes away (also remove the old Gecode mznlib library files or they'll probably still cause the same issue).
