### ISSUE TITLE
Time limit and statistic computation

### ISSUE THREAD

**Issue by jjocram** [MiniZinc/libminizinc#452]
I'm working with MiniZinc 2.5.0 (the problem can be reproduced in 2.5.3 and 2.4.3) and I encountered a strange behavior. 

When I launch MiniZinc from terminal with the following command
```bash
minizinc --solver Gecode -s -a --time-limit 60000 model.mzn instance.dzn
```
and when the instance is big enough I obtain the following output:
```
% Generated FlatZinc statistics:
%%%mzn-stat: paths=0
%%%mzn-stat: flatBoolVars=44582
%%%mzn-stat: flatIntVars=31693
%%%mzn-stat: flatBoolConstraints=4057
%%%mzn-stat: flatIntConstraints=49272
%%%mzn-stat: evaluatedReifiedConstraints=40511
%%%mzn-stat: evaluatedHalfReifiedConstraints=8102
%%%mzn-stat: eliminatedImplications=4031
%%%mzn-stat: method="minimize"
%%%mzn-stat: flatTime=2.57685
%%%mzn-stat-end

=====UNKNOWN=====
%%%mzn-stat: nSolutions=0
%%%mzn-stat-end
```

Ignoring my request to print the statistics. 

What I understand is that the statistics computation is included in the time limit because when a solution is found near the end of the time window the statistics do not get printed and increasing the time limit of 5-10 seconds most of the times work. 

A workaround I found is to use the `timeout` command to stop the execution with a SIGINT signal (the same as pressing Ctrl-c). This causes the stop of the solver and allows MiniZinc to compute the statistics at its pace.

**Comment by Dekker1** [comment]
Hi @jjocram,

We are not quite sure which problem you are running into. The first thing to realise is that  `--timeout` flag sets a timeout for the full MiniZinc process, this means that this is the combined time that can be used for the MiniZinc compilation process to arrive at the solver model, and the individual solving time. This means that if the MiniZinc compiler already uses all the time during compilation, then the solver doesn't get started and you will thus find a limited set of statistics. (Currently the compiler itself never correctly times out, this is a missing feature). The first this that just came to mind is that you are just running into the limit of the compilation time, and are unaware that this was included in the timeout time set. You can instead use `--solver-time-limit <ms>` which will only set a time limit for the FlatZinc solver that you are calling.

However, in your issue you mention that the solver still gets called, finds a solution, but then doesn't print any statistical information, and this is something that we are currently unable to recreate. This would be an issue in the way MiniZinc communicates with the solver you are using. If this is indeed the case, could you provide us with more information to recreate the problem:
 - The solver used
 - The MiniZinc instance used
