### ISSUE TITLE
strictly_decreasing global constrain is not documented

### ISSUE THREAD

**Issue by amamory** [MiniZinc/libminizinc#454]
I have seen that [strictly_decreasing](https://github.com/MiniZinc/libminizinc/blob/master/share/minizinc/std/strictly_decreasing.mzn) global constraint is not documented as [strictly_increasing](https://github.com/MiniZinc/libminizinc/blob/master/share/minizinc/std/strictly_increasing.mzn) is. Thus, strictly_decreasing does not appear in the [docs](https://www.minizinc.org/doc-2.5.3/en/lib-globals.html?highlight=strictly_increasing).

**Comment by Dekker1** [comment]
Thank you for reporting the issue. I've fixed it in 7ad7cec506e378d5e7333d3272a3c8e18d0216d0
