### ISSUE TITLE
function already defined in between bin_packing_load and bin_packing_capa?

### ISSUE THREAD

**Issue by paeadin** [MiniZinc/libminizinc#455]
Hi, 
  this minimal example reproduce the problem if I select solver Chuffed 0.10.4 :

```
var 1..10: z;
constraint z > 0;
include "bin_packing_load.mzn";                                                                                                                                                                                  
include "bin_packing_capa.mzn";                             
solve minimize z;
```

This is what happens:
```
MiniZinc to FlatZinc converter, version 2.5.3, build 220798393
[...]
processing file '/tmp/.mount_MiniZiivgVvQ/usr/share/minizinc/std//stdlib.mzn'
processing file '/tmp/.mount_MiniZiivgVvQ/usr/share/minizinc/std//solver_redefinitions.mzn'
/tmp/.mount_MiniZiivgVvQ/usr/share/minizinc/std//bin_packing_load.mzn:16.1-24.6:
MiniZinc: type error: function with the same type already defined in /tmp/.mount_MiniZiivgVvQ/usr/share/minizinc/std//bin_packing_load.mzn:16.1
Process finished with non-zero exit code 1
```

If I keep only one include the problem seems to vanish.

If I change solver the problem vanish.

I used my model some until 2 years ago (to make shifts for the entire year) and this is the first time I face this problem.

Is that a way to workaround this problem?

Thank you very much,

  Federico

**Comment by Dekker1** [comment]
This model seems to work for me on version 2.5.3. Can you please check you are using the current version of the MiniZinc bundle?

**Comment by Dekker1** [comment]
Hi Federico,

Could you please share how you installed MiniZinc. Running this model on my Mac seems to work fine with the newest version of MiniZinc.

**Comment by paeadin** [comment]
Il 22/02/21 05:26, Jip J. Dekker ha scritto:

> Hi Federico,
>
> Could you please share how you installed MiniZinc? Running this model 
> on my Mac seems to work fine with the newest version of MiniZinc.
>

Hy Jip,

   thank you for your reply.

I'm using Ubuntu 18.04 and installed MinizincIde 2.5.3 with snap.

When I saw the problem, I also downloaded and tried with the last app 
image for linux: MiniZincIDE-2.5.3-x86_64.AppImage: same result.


Anyway, I think that you will step into the problem only if you set 
optimization level greater or equal to:

*) -O3 with Chuffed 0.10.4, or

*) -O2 with Gecode 6.3.0


I realized that playing around with the model (after I posted the 
issue), the optimization level was set in the project I tried to re-use, 
so I didn't notice in the first place.


Can you confirm that you also have the problem with the optimization 
flag specified?


Thank you very much,

--
Federico Paladin

**Comment by Dekker1** [comment]
Yes, I can recreate the problem with -3
