### ISSUE TITLE
Uncontrolled allocation of memory with var set in function let statement

### ISSUE THREAD

**Issue by colbec** [MiniZinc/libminizinc#46]
FWIW I have a crash in Minizinc under the following circumstances using openSUSE Linux fully updated:
With configuration set to 1 cpu and print all solutions, I focus on a let{} inside a function where I have a "var set of int" statement.
If I assign a set to this token with a "x = y" plain assignment, all is well and Minizinc produces a solution.
However if I convert the plain assignment to a "var set of int: x, constraint x == blah" then all memory on machine is consumed, system becomes sluggish, eventually I can kill the process and system returns to normal.
Using the more restrictive "var set of [defined set in here]: x" produces a solution correctly with the constraint version.
So there appears to be uncontrolled allocation of memory with the "var set of int" version.
I won't post the code here since it relates to a Coursera course assignment.

**Comment by guidotack** [comment]
Please send me a copy of the code by email (guido.tack@monash.edu).

**Comment by colbeck** [comment]
Code sent to Guido as requested.
