### ISSUE TITLE
libmzn.so is installed without a suffix

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#461]
When other packages would depend on it and ```libmzn.so``` is updated it wouldn't be clear if other packages need to be updated.

Please add the suffix and maintain it according to future API changes.

**Comment by Dekker1** [comment]
We currently don't distribute MiniZinc as a library as we currently don't have a stable API into the library. If you do intend to use MiniZinc in this way, then it's currently at your own prerogative.

We'd be happy to look at any PRs that might improve the CMake configuration for library distribution, but currently we are not looking to adjust it ourselves for this purpose.
