### ISSUE TITLE
Temporary files not deleted on interrupt

### ISSUE THREAD

**Issue by MaxOstrowski** [MiniZinc/libminizinc#468]
After calling `minizinc foo.mzn --solver mysolver` minizinc leaves some files like 
`mznfileGGAQWr.fzn `
in the `/tmp` directory of my system in case the run is interrupted (e.g. hitting `ctrl+c`, memout, etc...).

This can periodically crash our cluster when the `/tmp` is full.
Could you remove these temporary files in the signal handler ?

Is there an environment variable that you are using to determine the `/tmp` folder, such that I could change it and delete it from outside ?

**Comment by cyderize** [comment]
46ce5528bd37885a3907bba89f5bfafe7b01a41e will let you set `TMPDIR` to somewhere that you can clean up from outside. It will be available in the next release.

I'll see if I can add something to just clean up correctly on a signal.

**Comment by MaxOstrowski** [comment]
Awesome, thanks a lot! I'll keep this open for the signal handler thingy.
Also maybe [this](https://en.cppreference.com/w/cpp/io/c/tmpfile) is helpful.
