### ISSUE TITLE
MiniZinc used question，please help！Thanks！

### ISSUE THREAD

**Issue by niuzhi** [MiniZinc/libminizinc#470]
I have two arrays，They all P1= ["get","list","create","update","patch","watch","delete","deletecollection"] and P2=["get","list"],
How to judge that the intersection of P1 and P2 is empty?
Can you help me write a complete example, because I just started to use the MiniZinc

**Comment by Dekker1** [comment]
MiniZinc currently does not have built-in definitions to intersect arrays of strings, but you can easily define them:

```
array[int] of string: P1 = ["get","list","create","update","patch","watch","delete","deletecollection"];
array[int] of string: P2 = ["get","list"];

function bool: 'in'(string: x, array[int] of string: y) =
  exists (z in array1d(y)) (z=x);
  
function array[int] of string: 'intersect'(array[int] of string: x, array[int] of string: y) = 
  [s | s in x where s in y];

constraint trace("\(P1 intersect P2)\n");
```
which gives output:
```
["get", "list"]
----------
```

General questions about MiniZinc usage are better fit for either:
- StackOverflow: https://stackoverflow.com/questions/tagged/minizinc
- The MiniZinc google group: https://groups.google.com/g/minizinc
