### ISSUE TITLE
bool_lin_le accepts variables

### ISSUE THREAD

**Issue by MaxOstrowski** [MiniZinc/libminizinc#477]
According to:
https://www.minizinc.org/doc-2.5.5/en/lib-flatzinc.html?highlight=bool_lin_le
```
predicate bool_lin_le(array [int] of int: as,
                      array [int] of var bool: bs,
                      int: c)
```
accepts only a constant 'c' but
```
var bool: a1;                                                                                
var bool: a2;                                                                                
var bool: a3;                                                                                
var bool: a4;                                                                                
var -10..12: c;                                                                                
constraint bool_lin_le([3,-2,-5,8],[a1,a2,a3,a4],c);                                                                   
solve satisfy;  
```
produces the predicate with a variable 'c'. 
`predicate bool_lin_le(array [int] of int: a,array [int] of var bool: x,var int: c);`
So, probably a typo in the handbook ?

**Comment by Dekker1** [comment]
Only the version where `c` is a `par int` is declared as one of the FlatZinc builtins and will be generated by the solver. There is no definition for `bool_lin_le` with `c` `var int` in the standard library. It does seem like Gecode has a definition for it.
If you were to try and compile you model with Chuffed for example, then it would fail.

I did however note that creating a boolean linear expression without using the FlatZinc builtin directly currently seems to result in its integer equivalent, which is probably not a good idea:
```
array[1..3] of var bool: bs;

constraint sum(i in 1..3) ( i * bs[i] ) < 5;
```

**Comment by Dekker1** [comment]
I've opened a new issue for the creation of boolean linear constraints (#478) and will close this one.

**Comment by MaxOstrowski** [comment]
That actually explains a lot, as I manually introduced boolean linear constraints (PB-constraints are often supported by SAT based solvers) for `count` and other globals.

So just for clarification:
1. `bool_lin_eq` can be used with `var int: c` ?
2. `bool_lin_le` can be used with `int: c` ?
3. The boolean linear constraints can be solved much faster with many SAT solvers than integer linear constraints. But currently the std redefinitions like `fzn_bin_packing_capa.mzn`
```
predicate fzn_bin_packing_capa(array[int] of int: c,
                           array[int] of var int: bin,
                           array[int] of int: w) =
      forall( i in index_set(bin) ) (
            min(index_set(c)) <= bin[i] /\ bin[i] <= max(index_set(c))
      )
    /\
      forall( b in index_set(c) ) (
            c[b] >= sum ( i in index_set(bin) ) (
                w[i] * bool2int( bin[i] = b )
            )
      );
```
manually convert these to linear constraints.
 - should I keep my translation which removes the bool2int and replaces the sum with my boolean linear constraint or is the boolean linear constraint automatically chosen after your change?
 - will this feature be available for the competition 2021?

**Comment by Dekker1** [comment]
1. Yes
2. Yes
3. I'd be happy to accept a PR request that removes usages of `bool2int` in places where they aren't necessary. I agree that we should be creating boolean linear expressions when possible. CP and MIP solvers that do not use Boolean variables can always create 0..1 variables when necessary.

I cannot guarantee that these changes will be in place before the MiniZinc Challenge though. The preparations for the challenge are already underway, and I'm not sure if we will see another MiniZinc release before the Challenge Docker image is released.

**Comment by MaxOstrowski** [comment]
I checked with:
`grep -r bool2int fzn*.mzn`
and there is only a limited amount of these cases.
And I just found that you have a great collection of unit tests (that could also test my solver), so I'll give it a try next week.
