### ISSUE TITLE
zebra_inverse.mzn problem is solved as UNSATISFIABLE by Gecode 6.3.0 and as satisfiable by other solvers

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#479]
What could be wrong?

minizinc-2.5.5
Gecode rev. 9428cd8 which is a tail of the 6.3.0 branch
FreeBSD 12.2

**Comment by Dekker1** [comment]
Without more specific information, this is not an issue or problem in the MiniZinc compiler.

For general discussion on MiniZinc solvers feel free to post on the MiniZinc Google Group. If you think this is an issue in Gecode or its MiniZinc library, then please report it there.
