### ISSUE TITLE
Testing libminizinc with different solvers

### ISSUE THREAD

**Issue by MaxOstrowski** [MiniZinc/libminizinc#481]
Hi, I want to test my flatzinc solver against the unit tests provided by libminizinc.
I therefore cloned the libminizinc repository and changed to the `tests` directory.
I also downloaded the latest minzinc for my linux 64 system: https://github.com/MiniZinc/MiniZincIDE/releases/download/2.5.5/MiniZincIDE-2.5.5-bundle-linux-x86_64.tgz

`pytest --driver=../../MiniZincIDE-2.5.5-bundle-linux-x86_64/bin`
works like a charm and all tests are passed (`947 passed, 13 skipped`)

Now I want to use my own solver to run the same tests:
`pytest --driver=../../MiniZincIDE-2.5.5-bundle-linux-x86_64/bin --solvers flatzingo`
And I do get 1 million times the python error:
```
conftest.py:142: in collect
    yield SolveItem.from_parent(
/home/ostrowsk/.conda/envs/clingcon/lib/python3.9/site-packages/_pytest/nodes.py:190: in from_parent
    return cls._create(parent=parent, **kw)
/home/ostrowsk/.conda/envs/clingcon/lib/python3.9/site-packages/_pytest/nodes.py:94: in _create
    return super().__call__(*k, **kw)
conftest.py:208: in __init__
    super().__init__(name, parent, solver, markers, suite)
conftest.py:174: in __init__
    self.allowed = [x for x in self.allowed if x in suite.solvers]
conftest.py:174: in <listcomp>
    self.allowed = [x for x in self.allowed if x in suite.solvers]
E   TypeError: argument of type 'NoneType' is not iterable
```

I do get the same errors when calling:
`pytest --driver=../../MiniZincIDE-2.5.5-bundle-linux-x86_64/bin --solvers gecode,chuffed`

Do I use the solvers option wrong ?
```
minizinc --solvers
MiniZinc driver.
Available solver configurations:
  Chuffed 0.10.4 (org.chuffed.chuffed, cp, lcg, int)
  COIN-BC 2.10.5/1.17.5 (org.minizinc.mip.coin-bc, mip, float, api, osicbc, coinbc, cbc)
  CPLEX <unknown version> (org.minizinc.mip.cplex, mip, float, api)
  findMUS 0.6.0 (org.minizinc.findmus)
  Flatzingo 1.6.0 (org.potassco.flatzingo, cp, lcg, int)
  Gecode 6.3.0 (org.gecode.gecode, default solver, cp, int, float, set, restart)
  Gecode Gist 6.3.0 (org.gecode.gist, cp, int, float, set, restart)
  Globalizer 0.1.7.0 (org.minizinc.globalizer, experimental, tool)
  Gurobi <unknown version> (org.minizinc.mip.gurobi, mip, float, api)
  SCIP <unknown version> (org.minizinc.mip.scip, mip, float, api)
  Xpress <unknown version> (org.minizinc.mip.xpress, mip, float, api)
```

**Comment by cyderize** [comment]
I think there's a bug in https://github.com/MiniZinc/libminizinc/blob/80ff66630d0525694d995e76c366028b2f48f4bc/tests/conftest.py#L174

It should probably be something like

```python
self.allowed = [x for x in self.allowed if suite.solvers is None or x in suite.solvers]
```

(That section should probably use set intersection really, I'll push a fix for it tomorrow)

The test cases mainly test the compiler itself and might not be that useful for testing solvers (although we have found a few solver bugs in the past). It's not currently designed for use with other solvers (although I'd like to make that easier in the future) and unless you add your own test cases that specify flatzingo as the solver (or edit the test cases to add flatzingo), it probably won't run anything.

You'll probably have to add flatzingo to https://github.com/MiniZinc/libminizinc/blob/80ff66630d0525694d995e76c366028b2f48f4bc/tests/minizinc_testing/spec.py#L19
so that more of the test cases will actually run, and edit the test cases that say `solvers: [gecode]` or similar to also include flatzingo. If I have some time tomorrow I'll see if I can make that a bit better.

**Comment by MaxOstrowski** [comment]
@cyderize I've seen that you did work on this in the develop branch and I tested it out immediately.
Extending
`self.solvers = ["gecode", "cbc", "chuffed"] `
with flatzingo helped a lot.
I do need to rewrite some of my stats and maybe other things to be compliant with the testing framework
(after `%%%mzn-stat: time=`) you actually expect a float while my timing information is different etc...
Also some of the examples seem to run endlessly and some others provide errors mainly with checking more than one solution, mainly things like:

| expected | actual |
| --- | --- | 
|   !Result  |!Result|
|   solution: !Solution | solution: null|
|  sokPosns:       |  status: OPTIMAL_SOLUTION
|   - 14   
|   - 13            
|   - 8             
|   - 7             
|   - 8   
|   - 9             
|     - 4               
|     - 5               
|     - 10     
|     - 1               
|     - 1               
|     - 1               
|     stime: 9     

I will get back to you once I get this more streamline and provide some experience of things that could be made easier for other solver developers to have some quick unit tests. Thanks a lot!

**Comment by MaxOstrowski** [comment]
Things I needed to change such that my solver can actually run tests (minizinc 2.5.5):
1. `self.solvers = ["gecode", "cbc", "chuffed"]`  -> `self.solvers = ["flatzingo"] ` (will be possible using the command line in the next version)
2. `%%%mzn-stat: time=` expects a pure float (I had additional information after the time (times of different parts of search, preprocessing etc...)) which results in a python error
3. `pytest -k "not test_var_set_element"` to exclude a benchmark as I do not support set variables

Still open problems:

1. `spec/unit/regression/bug269.mzn`
Gives output "OK" for my solver and gecode, but  testing scripts says:
```
...
E     but got
E
E     !Result
E     solution: !Solution
E       _output_item: 'Ok
E
E         '
E       queens:
E       - 1
E       - 5
E       - 8
E       - 6
E       - 3
E       - 7
E       - 2
E       - 4
E     status: SATISFIED
E
E
E     but passed check against gecode.
E   assert False
```
Is this testing the correct order of solutions ? As I freely ignore annotations.
 2. same error `spec/unit/regression/bug347.mzn`:
```
...
E     but got
E
E     !Result
E     solution: !Solution
E       _output_item: 'uav1 = 0;
E
E         uav2 = 1;
E
E         uav3 = 2;
E
E         uav4 = 3;
E
E         '
E       execution_unit_1000_3: 0
E       execution_unit_1000_4: 0
E       uav1: 0
E       uav2: 1
E       uav3: 2
E       uav4: 3
E     status: SATISFIED
E
E
E     but passed check against gecode.
E   assert False

```


I also actually found one corner case bug with an empty optimization statement, thanks a lot.
