### ISSUE TITLE
Including file with annotation declaration throws "not in root context" error

### ISSUE THREAD

**Issue by hbierlee** [MiniZinc/libminizinc#485]
Hi!

I've come across the following bug on b07cdda4d:

```
% /home/hbierlee/Projects/libminizinc/tests/spec/unit/sat/bugs/10_annotation_in_std_not_in_root_context_error.mzn
include "/home/hbierlee/Projects/libminizinc/tests/spec/unit/sat/bugs/10_annotation_in_std_not_in_root_context_error_inc.mzn";

var 2..4: x;
array[int] of var bool: y = func(x);
function array[int] of var bool: func(var int: x)=
    let {
      constraint has_ann_func(x, some_annotation);
    } in [true];

function bool: has_ann_func(var int: x, ann: a) =
  has_ann(x, a)
```

```
% /home/hbierlee/Projects/libminizinc/tests/spec/unit/sat/bugs/10_annotation_in_std_not_in_root_context_error_inc.mzn;
ann: some_annotation;
```

```
% > minizinc --solver gecode bug.mzn
% || MiniZinc: flattening error: 
% ||   /home/hbierlee/Projects/libminizinc/tests/spec/unit/sat/bugs/10_annotation_in_std_not_in_root_context_error_inc.mzn:1:
% ||   in variable declaration for 'some_annotation'
% ||   not in root context
% || 
```

Cheers,

Henk

**Comment by Dekker1** [comment]
The problem here is that `has_ann` is used is using in a reified context. Meaning that is trying to reify the fact if the `x` has the annotation `a`. This is just not allowed.

The error message should probably point at the `has_ann` usage and not at the annotation used though.

**Comment by hbierlee** [comment]
I'm probably missing something, but I don't really see the reified context here. Isn't it all just root and should it not just be a model inconsistency? Which is what I get if I add the `ann: some_annotation` to the top of the first file instead of including it.

**Comment by Dekker1** [comment]
I'm not sure, we should probably discuss the right semantics. It is definitely strange that it behaves differently when using a different file.

In essence the constraint that you write has similar properties to something like
```constraint lb(x) > 0```
which you should probably never write. Instead assertions would be the way to go.

**Comment by hbierlee** [comment]
I agree, but I get this issue (since the last merge) in many other cases that ran fine before. This model posted here is minimization of one of those.

**Comment by hbierlee** [comment]
Hi!

Commit 2d3567f did fix that one, but conveniently the issue is not closed yet as I found another instance of the same error on the current develop (0a1fc0a5e) that must be very related:
```
% bug.mzn
include "bug_inc.mzn";

var bool: x;
var 0..2: xi = func(x);

function var int: func(var bool: b)::promise_total =
  let {
    var 0..1: x;
    constraint order_encode_test(x) = array1d(0..1, [true, b]);
  } in x;

function array[int] of var bool: order_encode_test(var int: x)::promise_total =
  let {
    array[int] of var bool: x_enc;
    constraint if has_ann_test(x, unary_encoded) then true endif;
  } in x_enc;

function bool: has_ann_test(var int: x, ann: encoding) =
  has_ann(x, encoding);
```
```
% bug_inc.mzn
ann: unary_encoded;
```
Again, this code does not make much sense by itself, but isolates the bug:
```
> minizinc --solver gecode bug.mzn
|| MiniZinc: flattening error: 
||   [..]/bug_inc.mzn:1:
||   in variable declaration for 'unary_encoded'
||   not in root context
```

Cheers,

Henk

**Comment by hbierlee** [comment]
Thank you! This fixed the last ~20 unit test cases on my branch that were failing due to this issue.
