### ISSUE TITLE
System crash on attempt stop compile of large fzn

### ISSUE THREAD

**Issue by colbec** [MiniZinc/libminizinc#49]
On openSUSE 13.2 minizinc 0.9.9, attempting to stop the compile generation using the stop button in the IDE of a large fzn results in a system crash. Might be advisable to deactivate the Stop button during compile process unless there is a trap to ensure a clean stop. In many cases the compile happens really fast, so not a problem.

**Comment by guidotack** [comment]
That's now fixed, thanks for the report.
