### ISSUE TITLE
FindGecode.cmake fails to add -pthread when Gecode is built with the --enable-static option

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#491]
Static Gecode libraries require the ```-pthread``` flag:
```
ld: error: undefined symbol: pthread_create
>>> referenced by pthreads.cpp:54 (gecode/support/thread/pthreads.cpp:54)
>>>               pthreads.o:(Gecode::Support::Thread::Run::Run(Gecode::Support::Runnable*)) in archive /usr/local/lib/libgecodesupport.a
```

```-pthread``` should be added by ```FindGecode.cmake```

Version 6.3.0

**Comment by Dekker1** [comment]
In the official MiniZinc pipeline we also use a static build of Gecode, so I'm not sure if this issue actually related to that.

`Threads` is already required (https://github.com/MiniZinc/libminizinc/blob/master/CMakeLists.txt#L85) and linked (https://github.com/MiniZinc/libminizinc/blob/master/cmake/targets/libmzn.cmake#L122) into the MiniZinc library. This should add `pthreads` on UNIX environments.

**Comment by yurivict** [comment]
I found this issue when I tried to use ```FindGecode.cmake``` in a separate project, so the problem is that it isn't self-sufficient.

**Comment by Dekker1** [comment]
Fair enough. We don't really distribute this FindModule as is, so it is not an issue for us. If you would like to send in a PR, I'd be happy to merge it.

When I created the `FindGecode` module, there were no good ways of having one module depend on another. (Different from packages, where there are at least assumptions that that is possible). I'm not sure if that has changed. The idea would be that Gecode should depend on Threads and include `${CMAKE_THREAD_LIBS_INIT}` as part of its dependent libraries.
