### ISSUE TITLE
Model inconsistency with empty set and set comprehension

### ISSUE THREAD

**Issue by elKei24** [MiniZinc/libminizinc#493]
Doing a set comprehension with an empty set as generator leads to the detection of a model inconsistency.

### Minimal example
```minizinc
set of int: S = { };
function var set of S: asVar() = { val | val in S };
var set of S: asVar = asVar();
output [show(asVar)];
```

### Expected behavior
As `S` is empty, the set comprehension also evaluates to an empty set and MiniZinc outputs `{}`.

### Actual behavior
MiniZinc detects a model inconsistency in call `asVar` and states that the problem is unsatisfiable.

**Comment by Dekker1** [comment]
The issue seems to be with the return type of the function. The same example using a wider return type seems to work just fine:
```
set of int: S = { };
function var set of int: asVar() = { val | val in S };
var set of S: asVar = { val | val in S };
output [show(asVar)];
```

**Comment by guidotack** [comment]
I've pushed a fix to the develop branch, which will be included in the next release. For the time being, @Dekker1 's workaround is the best option.
