### ISSUE TITLE
Segmentation fault and failing to finding trivial solution

### ISSUE THREAD

**Issue by elKei24** [MiniZinc/libminizinc#495]
Hi, I just stumbled over another segmentation fault when compiling the following code:
```minizinc
array[1..1] of var float: arr;
var set of 1..1: one_or_none;
var float: prod = product(ti in one_or_none)(arr[ti]);
```

### Variations
Fixing the value of `arr` or `one_and_none` or changing the element type of `arr` to `int` makes the compilation work again. Replacing `product` with `min` or `max` still leads to an segmentation fault, but `sum` leads to a "cannot find matching declaration" error.

### Possibly related error
Moreover I noticed that Gecode does not halt (or takes very long) when using the first line only:
```
array[1..1] of var float: arr;
```
I am not sure if this is related to the segmentation fault. CBC instantly comes up with the solution `[0.0]`, Gurobi also does but then prints the following error message:
```
MIPGurobiWrapper runtime error:  Unable to retrieve attribute 'ObjBoundC'
Message from caller: Failed to get the best bound.
Gurobi error code: 10005
```

**Comment by guidotack** [comment]
I've pushed a fix for the compiler crash, which will be included in the next release. The problem with the unconstrained `var float` is that Gecode will pick a very large domain for the variable (it can't deal with infinite domains), and then start bisecting that domain during the search. That will most likely run out of memory. CBC and Gurobi use completely different search strategies, so the outcomes will vary.
As far as i can see, the error message from Gurobi has already been fixed on the develop branch of MiniZinc (the fix will be included in the next release).
