### ISSUE TITLE
Inconsistent naming: all_different vs alldifferent_except and alldifferent_except_0

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/libminizinc#500]
The constraints `all_different`, `alldifferent_except`, and `alldifferent_except_0` are inconsistently named. Either all should have the underscore after `all`, or none should have it.

The case for underscore is strengthened by it being used also for `all_equal` and `all_disjoint`.

**Comment by Dekker1** [comment]
I've added `all_` versions of these globals to the library to be included in the next release. I think these versions are the most consistent with the rest of the library and hopefully we can at some point remove the other versions. For now, it will be possible to use both.
