### ISSUE TITLE
show2d crashes on empty array

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/libminizinc#501]
When calling show2d on an empty matrix it crashes.

Consider the following program
```
set of int: Index = {};
array[Index, Index] of int: matrix = [| |];
output [show2d(matrix)];
```
which gives this output
```
Running untitled_model.mzn
/private/var/folders/m_/gb3wycb17b169222h13sdftr0000gn/T/AppTranslocation/A510967C-D3ED-48E2-8143-1F561741339F/d/MiniZincIDE 2.app/Contents/Resources/share/minizinc/std/stdlib/stdlib_string.mzn:42.31-71:
MiniZinc: result of evaluation is undefined: maximum of empty array is undefined
Process finished with non-zero exit code 1
Finished in 113msec
```

**Comment by zayenz** [comment]
Cool with a fast fix. Just as a heads up, when I looked at the code now show3d seems to have the same issue.

**Comment by Dekker1** [comment]
Ah, I had forgotten we even had a `show3d` function. I will correct that one as well.

**Comment by zayenz** [comment]
> Ah, I had forgotten we even had a `show3d` function. I will correct that one as well.

And I didn't know about it until I happened to see it in the code 😄
