### ISSUE TITLE
Minizinc IDE and `minizinc -c` do not output the same file

### ISSUE THREAD

**Issue by cprudhom** [MiniZinc/libminizinc#508]
Hi,

I'm encountering a strange behaviour while using `minzinc -c` command.
It seems that not all defined constraints are taken into account.
On the other hand, using Minizinc IDE (with the same settings) works.

## Model 
```mzn
include "globals.mzn";

array[1..4] of var 1..4: c1 :: add_to_output;
array[2..5] of var -100..100: c2 :: add_to_output;

constraint circuit(c1);
constraint circuit(c2);

solve satisfy;
```

## With CLI

```bash
minizinc -c -I "/Users/kyzrsoze/Sources/CHOCO/continuous-branch/parsers/src/main/minizinc/mzn_lib" /Users/kyzrsoze/Downloads/choco-solver-4.10.7/test_globals/circuit.mzn
```

gives:

```fzn
predicate gecode_circuit(int: offset,array [int] of var int: x);
var 1..4: X_INTRODUCED_0_;
var 1..4: X_INTRODUCED_1_;
var 1..4: X_INTRODUCED_2_;
var 1..4: X_INTRODUCED_3_;
var -100..100: X_INTRODUCED_4_;
var -100..100: X_INTRODUCED_5_;
var -100..100: X_INTRODUCED_6_;
var -100..100: X_INTRODUCED_7_;
array [1..4] of var int: c1:: output_array([1..4]):: add_to_output = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_,X_INTRODUCED_3_];
array [1..4] of var int: c2:: output_array([2..5]) = [X_INTRODUCED_4_,X_INTRODUCED_5_,X_INTRODUCED_6_,X_INTRODUCED_7_];
constraint gecode_circuit(1,c1);
constraint gecode_circuit(2,c2);
solve  satisfy;
```

It defines `gecode_circuit` which is not supported by choco.

## With Minizinc IDE
![Capture d’écran 2021-10-01 à 10 25 03](https://user-images.githubusercontent.com/1171872/135589196-8381bd28-3d19-43c9-ac79-04c83fdc9ef0.png)
`Compile` gives:
```fzn
predicate fzn_circuit(int: offset,array [int] of var int: x);
var 1..4: X_INTRODUCED_0_;
var 1..4: X_INTRODUCED_1_;
var 1..4: X_INTRODUCED_2_;
var 1..4: X_INTRODUCED_3_;
var -100..100: X_INTRODUCED_4_;
var -100..100: X_INTRODUCED_5_;
var -100..100: X_INTRODUCED_6_;
var -100..100: X_INTRODUCED_7_;
array [1..4] of var int: c1:: output_array([1..4]):: add_to_output = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_,X_INTRODUCED_3_];
array [1..4] of var int: c2:: output_array([2..5]) = [X_INTRODUCED_4_,X_INTRODUCED_5_,X_INTRODUCED_6_,X_INTRODUCED_7_];
constraint fzn_circuit(1,c1);
constraint fzn_circuit(2,c2);
solve  satisfy;
```

I suspect that I didn't chose the right name for redefinitions in `*.fzn` files, but I can't figure out what are forbidden (or recommended).

Thank you for your helps

**Comment by Dekker1** [comment]
Hi,

It seems your file has the same name as the library filename. Do you have the same problem when you rename the file to something other than `circuit.mzn`?

**Comment by cprudhom** [comment]
The file is named `fzn_circuit.mzn`
and contains:

```fzn
predicate fzn_circuit(int: offset, array[int] of var int: x);

predicate fzn_circuit(array[int] of var int: x) =
  if min(index_set(x)) >= 0 then
    fzn_circuit(min(index_set(x)),x)
  else
    fzn_circuit(0,[x[i]-min(index_set(x)) | i in index_set(x)])
  endif;
```

**Comment by cprudhom** [comment]
Just in case: [mzn_lib](https://github.com/chocoteam/choco-solver/tree/master/parsers/src/main/minizinc/mzn_lib)

**Comment by Dekker1** [comment]
What I was referring to was not the library file, but rather that the the model file in test globals has the same name as the global definition in the standard library. 

Renaming the file `test_globals/test_circuit.mzn` might solve the problem

**Comment by cprudhom** [comment]
I just tried to rename the file and execute the command once again, but it led to the issue.
adding `-v` outputs that:
```
...
processing file '/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/std/circuit.mzn'
processing file '/Users/kyzrsoze/Sources/CHOCO/continuous-branch/parsers/src/main/minizinc/mzn_lib/fzn_circuit_reif.mzn'
processing file '/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/gecode/fzn_circuit.mzn'
...
```
even though there is a file named `minizinc/mzn_lib/fzn_circuit.mzn`.

**Comment by cyderize** [comment]
I think adding `--solver org.minizinc.mzn-fzn` should fix the problem - the default solver is Gecode when you don't specify any `--solver` option, and its globals library takes precedence over the `-I` flag.

**Comment by cprudhom** [comment]
That fixes the issue, thank you for your help.
