### ISSUE TITLE
Two running processes in IDE, one uncontrolled

### ISSUE THREAD

**Issue by colbec** [MiniZinc/libminizinc#52]
It is possible to run one model and then a second. Stopping one process is easy, but the other is uncontrolled. Steps to reproduce:
1. open a model in the editor and run it; run button is greyed out and stop button activated
2. make an edit to the model and save it; run button is now activated along with stop button
3. click run; run button is now greyed out, stop is active, two runs now running
4. click stop; stop is now greyed, one process stops, but the other keeps running
5. close IDE to stop the run and reset the IDE.

**Comment by guidotack** [comment]
Thanks for the bug report. I'll put in a quick fix (disabling any edits while a process is running), but I'll have to think about a more robust and convenient solution.

**Comment by colbec** [comment]
2.0.7 certainly does as you suggest, but is is clearly a temp. fix. For example, while running a model you can double click another mzn from the project explorer, this is added into the work area, the Run button lights up again. If possible it would be helpful to be able to scroll the model while it is running. I find myself wanting to use the time while compile and run is happening to review the model details.

Would it be possible to have only one button for both Run and Stop? When the run is launched, the label on the button changes to stop and its functionality becomes to halt the currently running process. That way you have only one option given the current state.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
