### ISSUE TITLE
Inline var constraint is treated as an assignment

### ISSUE THREAD

**Issue by mslazynski** [MiniZinc/libminizinc#522]
I'm teaching MiniZinc at my university ([url](https://gitlab.com/agh-courses/2021-2022/constraint-programming) for interested, the course is very introductory, and there will be only 6 classes in total, shamelessly reuses materials from various sources — obviously with copyright notice) and I'm writing some automated tests to grade students' submissions. Today I've been surprised by the minizinc compiler.

Let's say that we have a very basic model:

```minizinc 
1..2: a;
var 1..2: b;
var bool: c;
constraint c = (a = b);
```
In the tests, I want to be able to control (fix) all three variables `a`, `b` and `c` and observe the model's behavior. It's quite easy and works well, so I'm a happy teacher.

However... a smart student writes an equivalent model:

```minizinc 
1..2: a;
var 1..2: b;
var bool: c = (a = b);
```

and suddenly I can't fix the `c` variable in the datafile because of the error:

`multiple assignment to the same variable`

AFAIK both model are equivalent and should be treated by the compiler in the same way. In fact, they produce the same flatzinc files. 

I know this is a minor issue, but every small inconsistency makes teaching a tad bit more difficult ;)

**Comment by Dekker1** [comment]
Hi @mslazynski,

Great to learn that there is more MiniZinc teaching out there!

In MiniZinc, assignments are different from equality constraints. For variable declarations we see this for example in the way that output is generated and processing order.

The solution that you are likely looking for is using the `--allow-multiple-assignments` flag. This will allow you to assign `c` both in the data file and in the model. If these assignments are inconsistent, then the model will be declared unsatisfiable.

However, when writing automated tests for MiniZinc models, I would encourage you to consider the usage of [checker models](https://www.minizinc.org/doc-2.5.5/en/checkers.html), which is the recommended MiniZinc solution to solve these sort of problems and would likely avoid these types of problems.

**Comment by mslazynski** [comment]
Thanks for the prompt answer. `--allow-multiple-assignments` looks like a quick solution for my use case.

I am aware of the checker models. However, due to my limited resources, I've decided to follow an easier (even if worse) path, namely: I run the students' models against my own "correct" models in a set of small "unit-tests". This way I am able to quickly provide useful feedback for both sat and optimization problems. Obviously, my feedback is not always as good as the one provided by a well-written checker, but it's sufficient for my purposes. Also, in my homebrew grading system, I do some naive analysis of the model structure, profile the search process and run basic model competitions. Hopefully, this year I'll finish all the assignments/competitions/etc. and maybe next year I will find some extra time to introduce more elegant solutions, like the checker models.

Again, thanks for your great work!
