### ISSUE TITLE
Can't build. Crash on [ 97%] Linking CXX executable minizinc

### ISSUE THREAD

**Issue by maxim317** [MiniZinc/libminizinc#528]
Hello!

A make dockerfile:
``FROM ubuntu:20.04
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt install -y cmake build-essential liblapack3 libgfortran4 clang gfortran libtbb2 libcliquer1 libopenb>
#gcc g++ -> clang
ENV \
    CC="/usr/bin/clang" \
    CXX="/usr/bin/clang++"

COPY SCIPOptSuite-8.0.0-Linux-ubuntu.deb /src/
RUN mkdir /home/SCIP
ENV SCIPOPTDIR /home/SCIP
RUN dpkg -i /src/SCIPOptSuite-8.0.0-Linux-ubuntu.deb
RUN rm /src/SCIPOptSuite-8.0.0-Linux-ubuntu.deb
RUN export SCIPOPTDIR=/home/SCIP

COPY libminizinc-2.5.5/ /src/
WORKDIR /src/libminizinc-2.5.5/
RUN cmake -DCMAKE_BUILD_TYPE=Release -DSCIP_ROOT="/home/SCIP/" ..
RUN cmake --build .
RUN cmake --build . --target install
RUN pip install minizinc

WORKDIR /home/SCIP

RUN pip install --upgrade pip
#RUN pip install pyscipopt
RUN pip install jupyter

CMD ["sh", "-c" ,"jupyter notebook --ip=0.0.0.0 --allow-root"]``

and when trying to build it, I get the error:

``...
[ 95%] Building CXX object CMakeFiles/minizinc.dir/minizinc.cpp.o
[ 97%] Linking CXX executable minizinc
/usr/bin/ld: libmzn.a(MIP_scip_wrap.cpp.o): in function `ScipPlugin::ScipPlugin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
MIP_scip_wrap.cpp:(.text+0x23): undefined reference to `dlclose'
/usr/bin/ld: libmzn.a(MIP_scip_wrap.cpp.o): in function `ScipPlugin::ScipPlugin()':
MIP_scip_wrap.cpp:(.text+0x7a2): undefined reference to `dlclose'
/usr/bin/ld: libmzn.a(MIP_scip_wrap.cpp.o): in function `MIPScipWrapper::getVersion[abi:cxx11](MIPScipWrapper::FactoryOptions&, MiniZinc::SolverInstanceBase::Options*)':
MIP_scip_wrap.cpp:(.text+0xacb): undefined reference to `dlclose'
/usr/bin/ld: MIP_scip_wrap.cpp:(.text+0xbd5): undefined reference to `dlclose'
/usr/bin/ld: libmzn.a(MIP_scip_wrap.cpp.o): in function `MIPScipWrapper::getRequiredFlags[abi:cxx11](MIPScipWrapper::FactoryOptions&)':
MIP_scip_wrap.cpp:(.text+0xd3f): undefined reference to `dlclose'
/usr/bin/ld: libmzn.a(MIP_scip_wrap.cpp.o):MIP_scip_wrap.cpp:(.text+0x1e85): more undefined references to `dlclose' follow
/usr/bin/ld: libmzn.a(MIP_scip_wrap.cpp.o): in function `MiniZinc::Plugin::symbol(char const*)':
MIP_scip_wrap.cpp:(.text._ZN8MiniZinc6Plugin6symbolEPKc[_ZN8MiniZinc6Plugin6symbolEPKc]+0x15): undefined reference to `dlsym'
/usr/bin/ld: libmzn.a(MIP_scip_wrap.cpp.o): in function `MIPScipWrapper::~MIPScipWrapper()':
MIP_scip_wrap.cpp:(.text._ZN14MIPScipWrapperD2Ev[_ZN14MIPScipWrapperD2Ev]+0x78): undefined reference to `dlclose'
/usr/bin/ld: libmzn.a(MIP_scip_wrap.cpp.o): in function `MiniZinc::Plugin::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
MIP_scip_wrap.cpp:(.text._ZN8MiniZinc6Plugin4openERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN8MiniZinc6Plugin4openERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xf3): undefined reference to `dlopen'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/minizinc.dir/build.make:85: minizinc] Error 1
make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/minizinc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
The command '/bin/sh -c cmake --build .' returned a non-zero code: 2``

Please, what am I doing wrong?

**Comment by Dekker1** [comment]
It seems like when linking your compiler cannot find cannot find the `dlopen` functionality. This should be part of `glibc` and should not require any additional information for the compilation process.

CMake still seems to provide [`CMAKE_DL_LIBS`](https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html), so you could try and add this to the `target_link_libraries` for the MiniZinc library to try and see if that makes any difference.

**Comment by maxim317** [comment]
ok.
i add string 

```
if(CMAKE_DL_LIBS)
   target_link_libraries(ExtremeCUnit dl)
endif()
```
or 

`target_link_libraries(ExtremeCUnit dl)`

in 

_CMakeLists.txt_

and got a response from build:

```
Step 14/21 : RUN cmake -DCMAKE_BUILD_TYPE=Release -DSCIP_ROOT="/home/SCIP/" ..
 ---> Running in edbc9659247b
-- The CXX compiler identification is Clang 10.0.0
-- The C compiler identification is Clang 10.0.0
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
**CMake Error at CMakeLists.txt:18 (target_link_libraries):
  Cannot specify link libraries for target "ExtremeCUnit" which is not built
  by this project.**


-- Configuring incomplete, errors occurred!
See also "/src/libminizinc-2.5.5/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c cmake -DCMAKE_BUILD_TYPE=Release -DSCIP_ROOT="/home/SCIP/" ..' returned a non-zero code: 1
```

**Comment by Dekker1** [comment]
I don't really understand your fix. There is no `ExtremeCUnit` in the MiniZinc repository, so the error is clear. Instead you should add it to the `mzn` target, which is the MiniZinc library that is compiled into the executable. I'm actually seeing that the change was already made on the `develop` branch, so you could just try to build that instead: https://github.com/MiniZinc/libminizinc/blob/develop/cmake/targets/libmzn.cmake#L129

**Comment by maxim317** [comment]
Yes!
it worked
