### ISSUE TITLE
annotation functions

### ISSUE THREAD

**Issue by jnmonette** [MiniZinc/libminizinc#53]
Hi,

I am trying to use annotation functions but I ran accross some problem. Here is my code:

```
annotation simpleann;
annotation composeann(ann: s);
function ann: annfunc(ann: s) = composeann(s);
solve :: annfunc(composeann(simpleann)) satisfy;
```

The annotation function works fine if the passed annotation does not take any argument but it crashes if the passed annotation takes an argument as in the example above. The error message is:

    mzn2fzn: /home/janho/programs/libminizinc/include/minizinc/ast.hh:198: T* MiniZinc::Expression::cast() [with T = MiniZinc::VarDecl]: Assertion `isa<T>()' failed.
    Aborted

Is this a bug or am I simply hitting the limits of mzn2fzn?

**Comment by guidotack** [comment]
That's a bug (just fixed it).

**Comment by jnmonette** [comment]
Bug fixed over the week-end... That's great, thank you!
