### ISSUE TITLE
Confusing error message for array of float/int mismatches

### ISSUE THREAD

**Issue by sbronson** [MiniZinc/libminizinc#533]
```
enum E = {E1};
function float: f(array [E] of float:a) = 0.0;
array [E] of int: A = [50];
0.0..0.0: B = f(A);
```
```
Error: type error: array index must be `E', but is `int'
stdlib_array.mzn:115.13-17
```

The code does have an error, but it's hard to find it from that error message.  A stacktrace or a line number from the model file would help.

Changing A from array of int to array of float gets me:
```
f.mzn:3.1-21
  in variable declaration for 'A'
MiniZinc: evaluation error: Index set mismatch. Declared index set of `A' is [1..1], but is assigned to array with index set [50..50]. You may need to coerce the index sets using the array1d function.
```
but `index set [50..50]` seems wrong, and I think it should compile at this point, coercing the 50 to a float.

Changing A from `50` to `50.0` works.

On develop.

**Comment by cyderize** [comment]
This appears to now be fixed in `develop`
