### ISSUE TITLE
"Cannot initialise vals in unbounded IntVar" when using table constraint with Chuffed

### ISSUE THREAD

**Issue by jonadsimon** [MiniZinc/libminizinc#539]
I have a pair of integer variable arrays `word_delta_y` and `word_delta_x` whose values I was previously constraining like this:
```
constraint forall(i in 1..m)(word_delta_y[i] >= -1 /\ word_delta_y[i] <= 1); % dy values are one of {-1, 0, 1}
constraint forall(i in 1..m)(word_delta_x[i] >= -1 /\ word_delta_x[i] <= 1); % dx values are one of {-1, 0, 1}
constraint forall(i in 1..m)(word_delta_y[i] != 0 \/ word_delta_x[i] != 0); % at least one of dy,dx must be nonzero
```

I then updated to code to more directly constrain them using a `table` constraint like this:
```
constraint forall(i in 1..m)(table([word_delta_y[i],word_delta_x[i]], [| 1, 0 | 0, 1 | -1, 0 | 0, -1 | 1, 1 | -1, 1 | -1, -1 | 1, -1 |]));
```

When I try to run the program containing the first piece of code, it completes fine with both Geocode and Chuffed backends.

However when I try to run the second piece of code, it completes fine with Geocode but returns the following error with Chuffed:
`int-var.cpp:116: Cannot initialise vals in unbounded IntVar`

What is the problem here? Is this a bug with MiniZinc and/or Chuffed?

**Comment by Dekker1** [comment]
Can you share the definitions of the variables (i.e., a minimal example that gives this problem)? That would probably make it a lot easier to find the problem. Thanks in advance

**Comment by jonadsimon** [comment]
Sure, he's an extremely simple script exhibiting the same issue. Works with Geocode, throws a `Cannot initialise vals in unbounded IntVar` error with Chuffed
```
include "table.mzn";
array [1..2] of var int: tup;
constraint table(tup, [|0,0|0,1|1,0|1,1|]);
```

**Comment by Dekker1** [comment]
The issue seems to be that Chuffed crashes when it sees any unbounded variables, in this case `tup`. A workaround in this case is to actually assign bounds to `tup`:

```
include "table.mzn";
array [1..2] of var 0..1: tup;
constraint table(tup, [|0,0|0,1|1,0|1,1|]);
```

The question is if MiniZinc should maybe infer the bounds for variables when they are used in a table constraint. I'll have a look at this later.

**Comment by jonadsimon** [comment]
Ah very cool, I didn't know you could add bounds like that. That fixes it, thanks
