### ISSUE TITLE
Issue with optimized compilation for partially defined mydiv function

### ISSUE THREAD

**Issue by Alexander-Schiendorfer** [MiniZinc/libminizinc#54]
When trying the user-defined partial function example mydiv from the Coursera class, I noticed some problems with compiler optimizations (also here [Gist](https://gist.github.com/Alexander-Schiendorfer/d0c395b59404ccbc414c)) :

```MiniZinc
function var int:mydiv(var int: x, var int: y) = 
  assert(lb(x) >= 0 /\ lb(y) >= 0,
         "Mydiv got wrong arguments",
         let {constraint y != 0 } in 
         safediv(x, y)
);

function var int: safediv(var int: x, var int: y)   :: promise_total = 
  let {
    var 0..ub(x): q;
    var 0..ub(y)-1: r;
    constraint q*y + r = x;
    constraint r < y;
  }  in q;

var int: x;
var int: y; 
var int: z;

constraint x = 7;
constraint y = 1;
constraint z = mydiv(x,y);

% should return z = 7
solve satisfy;
```
which returns `{ (7,1,i) | i in 0..7}` as solution set when producing optimized FlatZinc.

*. When declaring `var 0..ub(y)-1: r;`  as `var int: r;' with optimized FlatZinc, the correct (only) solution `(7,1,7)` is returned. Then, the constraints
``` 
array [1..3] of int: X_INTRODUCED_5 = [1,-1,-1];
array [1..2] of int: X_INTRODUCED_6 = [1,-1];
``` 
are present, whereas they weren't in the original version. The original FlatZinc is obscurely small:
```
var 0..7: z:: output_var;
solve  satisfy;
```

* When compiling the model without the flag for optimized FlatZinc, I get the correct solution set. 

I'm using the bundled MiniZinc IDE, Version 0.9.9.

**Comment by guidotack** [comment]
Thanks a lot, that was a bug in the optimisation phase of the compiler (completely unrelated to partial functions, but triggered by this example).  It will be fixed in the next release (which should have happened today, but there were a few showstoppers like this one).
