### ISSUE TITLE
Internal error "unexpected type in array access expression" solving model with 2D var array

### ISSUE THREAD

**Issue by sbronson** [MiniZinc/libminizinc#542]
```
array [0..0, 1..1] of var bool: A;
```
```
$ minizinc f.mzn
Error: evaluation error: Internal error: unexpected type in array access expression
unknown file:0.0
```

On develop.

**Comment by Dekker1** [comment]
Hi @sbronson,

Thank you for reporting the issue. It seems something was going wrong in the generation of the new indexed 2d literals introduced in the upcoming version of MiniZinc. The fix for this issue should hopefully arrive on the `develop` branch once it passes the CI.
