### ISSUE TITLE
Dag constraint

### ISSUE THREAD

**Issue by fcpereira97** [MiniZinc/libminizinc#543]
In dag.mzn file, at line 17, we have

`assert(dom_array(from) subset index_set(ns),"dreachable: nodes in to must be in index set of ns") /\`

but we probably should have 

`assert(dom_array(to) subset index_set(ns),"dreachable: nodes in to must be in index set of ns") /\`

instead.

**Comment by Dekker1** [comment]
Thank you for raising this issue. It seems the issue was already found recently and has been fixed on the `develop` branch: fd2b1fc178742e9648d18561f6a4b62e3f45226e

**Comment by fcpereira97** [comment]
Thank you.
