### ISSUE TITLE
Increase memory and/or stack depth?

### ISSUE THREAD

**Issue by jonadsimon** [MiniZinc/libminizinc#545]
When I run Minizinc in the command line I see it print out metadata like
```
Converting to old FlatZinc ... done (0.10 s)
 done (0.10 s)
 done (0.15 s), max stack depth 25
Maximum memory 5 Mbytes.
```

I don't really understand what the memory or stack depth refers to here, but I assume that more is better, so is there some way for me to allot more memory or allow a deeper stack when solving?

Thanks, and apologies for the naive/silly question.

**Comment by cyderize** [comment]
The stack depth and memory are referring to how much memory was used during compilation, not how much is available.

These values don't relate to solving. The solver decides itself how to use memory (some solvers may have options which allow you to configure certain things, but generally they will just consume as much memory as they need).
