### ISSUE TITLE
Stack smashing detected.

### ISSUE THREAD

**Issue by BogdanD02** [MiniZinc/libminizinc#548]
Hello,
I just installed MiniZinc via Snap on Ubuntu 20.04 LTS and when I tried running it in the command line it gave an error:
> minizinc --version
*** stack smashing detected ***: terminated
Aborted (core dumped)

Could you please help me fix this ?
Thanks,
Bogdan

**Comment by cyderize** [comment]
Hi, I haven't been able to reproduce this on any of our Ubuntu machines. Are you able to try one of the other installation methods (AppImage or the `.tgz` archive) and see if there's any difference?

**Comment by BogdanD02** [comment]
Hi,
I downloaded the bundle from your website (the .tgz one) and after setting the path, that appears to be working just fine.

**Comment by BogdanD02** [comment]
However when I try to install it with `snap install` or `sudo apt install minizinc` the issue is there.

**Comment by BogdanD02** [comment]
However it appears to be a problem with my system, as after i export the path and close the terminal, the path resets to its former value for some reason...

**Comment by BogdanD02** [comment]
I don't know if this helps, but after switching to Windows and using those installers everything worked fine. :))) so I believe I can close this now :)
