### ISSUE TITLE
MIP compiler error - reported by MiniZinc

### ISSUE THREAD

**Issue by markwallacemonash** [MiniZinc/libminizinc#550]
Here's the error report:
" MIPD: LIN_EQ with 1 variable::: int_lin_eq(X_INTRODUCED_436007_,[X_INTRODUCED_38_],0):: defines_var(0)
  MIPD: LIN_EQ with 1 variable::: int_lin_eq(X_INTRODUCED_436007_,[X_INTRODUCED_38_],0):: defines_var(0)
MiniZinc has encountered an internal error. This is a bug.
Please file a bug report using the MiniZinc bug tracker.
The internal error message was: 
"std::fabs(it2->second.first - A) < 1e-6 * std::max(std::fabs(it2->second.first), std::fabs(A))"
Process finished with non-zero exit code 1."

The same bug was reported by the MiniZinc IDE version 2.5.6, running solver Gurobi 9.1.0 and COIN 2.10.7/1
The model and data are attached as text files
[match2Kall.dzn.txt](https://github.com/MiniZinc/libminizinc/files/8149725/match2Kall.dzn.txt)
[match_best_func_like_non_func.mzn.txt](https://github.com/MiniZinc/libminizinc/files/8149726/match_best_func_like_non_func.mzn.txt)
.

**Comment by glebbelov** [comment]
Adding a workaround on develop. For the current release, add -DfMPdomains=false in the command-line options, the IDE might have a dedicated flag.

Basically this finds contradicting constraints. But removing this check (what I did) leads to a seemingly feasible model. Weird, I haven't checked further.
