### ISSUE TITLE
Compilation to flatzinc from minizinc with search annotations using -O2...5

### ISSUE THREAD

**Issue by forceoffire** [MiniZinc/libminizinc#554]
Attempting to compile a mzn file (using optimisations -O2...5) with the following search annotation:

ann : search_sequence = seq_search([ 
int_search([ total_demand_deviation ], first_fail, indomain_min),
int_search([ total_mass_buyin ], first_fail, indomain_min),
int_search([ total_mass_unused ], first_fail, indomain_min),
int_search([ total_deviations_in_final ], first_fail, indomain_min)]);
solve :: search_sequence minimize objective_function_value;

Results in an fzn file as follows:
solve :: seq_search(['\22@int_search'([total_demand_deviation],first_fail,indomain_min),'\22@int_search'([total_mass_buyin],first_fail,indomain_min),'\22@int_search'([total_mass_unused],first_fail,indomain_min),'\22@int_search'([total_deviations_in_final],first_fail,indomain_min)]) minimize objective_function_value;

It appears the strings here in single-quotes are unexpected for fzn solvers?

Compiling with -O1 yields:

solve :: seq_search([int_search(X_INTRODUCED_1291_,first_fail,indomain_min,complete),int_search(X_INTRODUCED_1291_,first_fail,indomain_min,complete),int_search(X_INTRODUCED_1290_,first_fail,indomain_min,complete),int_search(X_INTRODUCED_1289_,first_fail,indomain_min,complete),int_search(X_INTRODUCED_1288_,first_fail,indomain_max,complete)]) minimize objective_function_value;

And this version succeeds in when passed to flatzinc backends.

I've tested this with Gecode & OR-Tools.  Both fzn backends crash with different errors.

Regards.

**Comment by cyderize** [comment]
I believe this has been fixed and will work in 2.6.1.
