### ISSUE TITLE
Remaining Option Types Error?

### ISSUE THREAD

**Issue by markmanser** [MiniZinc/libminizinc#56]
The following code from the paper "Modelling with Option Types in MiniZinc" ran for 48 hours on 2 cores without reaching an optimal solution.  I then switched it to satisfy and ran it for 2 minutes and didn't achieve any satisfiable solution.  Do you have a copy of the dataset that was used with the paper (to confirm the code will actually return the correct solution, as the embedded dataset may not be sensical)?  I haven't yet been able to get a model to solve correctly using option types.

```
include "globals.mzn";

% Example 11. A MINIZINC model for flexible job shop scheduling as discussed in Example
% 1 is shown below. Note that the optional variables are used to give start times for
% the version of the tasks starting on each machine. The disjunctive constraint is the
% version lifted for option types. The alternative constraints are directly defined on
% option types; they enforce the span constraint (see Example 10) as well as ensuring at
% most one optional task actually occurs. The redundant cumulative constraint ensures
% no more than k tasks run at one time. The aim is to minimize the latest end time.

int: horizon = 300; % time horizon
set of int: Time = 0..horizon;
int: n = 10; % number of tasks
set of int: Task = 1..n;
int: k = 10; % number of machines
set of int: Machine = 1..k;
array[Task,Machine] of int: d = [| 
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10,|
1,2,3,4,5,6,7,8,9,10 |];
int: maxd = max([ d[t,m] | t in Task, m in Machine ]);
int: mind = min([ d[t,m] | t in Task, m in Machine ]);
array[Task] of var Time: S;
array[Task] of var mind..maxd: D;
array[Task,Machine] of var opt Time: O;

constraint 
forall(m in Machine)
(
  disjunctive([O[t,m] | t in Task], [d[t,m] | t in Task])
);

constraint 
forall(t in Task)(
    alternative(S[t], 
                D[t], 
                [O[t,m] | m in Machine], 
                [d[t,m] | m in Machine])
);

constraint cumulative(S, D, [1 | i in Task], k);

solve minimize max(t in Task)(S[t] + D[t]);
```

I also ran the following 2 examples from the same paper "Modelling with Option Types in MiniZinc":

Example1:

```
include "globals.mzn";

int: n = 10; % number of tasks
int: m = 15; % number of workers
array[1..m] of var opt 1..n: w; % task for each worker
constraint alldifferent(w);
solve satisfy;
```

Returns the following error:

```
MiniZinc: type error: no function or predicate with this signature found: `alldifferent(array[int] of var opt int)'
```

Example2:

```
include "globals.mzn";

int: n = 15; % number of tasks
int: m = 10; % number of workers
array[1..m,1..m] of bool: compatible;
array[1..m] of var 1..n: w; % task for each worker
array[1..n] of var opt 1..m: t; % worker for each task
constraint inverse(w,t);
constraint forall(j in 1..n-1)(compatible[t[j],t[j+1]]);
solve satisfy;
```

Returns the following error (yes, I realize the "compatible" param still needs to be populated) :

```
MiniZinc: type error: no function or predicate with this signature found: `inverse(array[int] of var int,array[int] of var opt int)'
```

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.

**Comment by Zero3** [comment]
@Dekker1 I see that this issue was closed, but I'm seeing the same error as @markmanser using the latest version of MiniZinc IDE (2.3.2):

> MiniZinc: type error: no function or predicate with this signature found: `alldifferent(array[int] of var opt int)'

(I also tried `all_different` without any luck.)

According to the documentation at https://www.minizinc.org/doc-2.3.2/en/lib-globals.html#all-different-and-related-constraints, it appears like the alldifferent global constraints do not (yet?) support option types? Is that correctly understood? If so, do you know if there are any plans to add support for option types to this family of constraints?

**Comment by Dekker1** [comment]
Hi @Zero3,

As far as I know there are no current plans to expand the globals to all support optional variables. We haven't often seen the occurrence of optional variables in the use of most globals and some already are supported with optional variables. One of the great benefits of using globals is that solvers will be able to use special mechanisms (in CP solvers propagators) to make the model more efficient. I believe solvers would be reluctant to provide these extra propagators necessary to make models efficient. Adding these globals using redefinitions can thus be dangerous as you can easily end up with optional variables where it is unnecessary and the performance of the solvers would decrease rapidly.

If you actually seek to use `all_different` with optional constraints, then `alldifferent_except_0` is probably the global that you would want to use. Normally you would rewrite the domain to not be optional and ensure that if it was optional before it would now be the value zero. If this is not possible, then if zero is not in the domain you can use the following redefinition to post alldifferent on an array of var opt int:

```
include "all_different_except_0.mzn";

predicate all_different(array[int] of var opt int: x) =
  assert(not 0 in dom_array(x)) /\
  let {
    array[index_set(x)] of var dom_array(x) union {0}: y;
    constraint forall(i in index_set(x)) ( if absent(x[i]) then y[i] = 0 else y[i] = x[i] );
  } in all_different_except_0(y);
```

Again, it is better to redefine you initial domains as this definition will create both new variables and a channeling constraint that you might not need.

**Comment by Zero3** [comment]
@Dekker1 thanks a lot for the thorough answer! What you write makes perfect sense.

After reading https://www.minizinc.org/doc-2.3.2/en/optiontypes.html, I was left with the impression that modelling using option types was a good thing to do. The page mostly highlights advantages with option types, and does not mention significant disadvantages like this one. In my case, I actually started rewriting my model using option types in an attempt to improve it, but now I see that this has led me towards a dead end. I will go back to using 0 instead.

Perhaps that page in the documentation should to be updated to mention some of the very useful information from your reply, like the limited availability of global constraints.

**Comment by guidotack** [comment]
The plan is still to add option type versions for globals where that makes sense, including alldifferent. Even if solvers don't support native propagators, MiniZinc can still do a pretty good job at translating those models efficiently (e.g. by turning an alldifferent with optional variables into an alldifferent_except_0 when possible). So it's still a planned feature, but we should probably update the documentation to say that support is currently a bit limited.
