### ISSUE TITLE
FindMUS bundled on MacOS only compiled for ARM

### ISSUE THREAD

**Issue by ccr185** [MiniZinc/libminizinc#562]
Hello!

I have just recently upgraded to the most recent release `2.6.2` and it seems that the bundled findMUS executable for the macOS distribution is only compiled for `arm64` and thus cannot be used for `x86` machines. This can be seen when comparing the minizinc executable and the `findMUS` executable. This can be evidenced by the following commands:

```console
$ file /Applications/MiniZincIDE.app/Contents/Resources/minizinc
/Applications/MiniZincIDE.app/Contents/Resources/minizinc: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
/Applications/MiniZincIDE.app/Contents/Resources/minizinc (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/MiniZincIDE.app/Contents/Resources/minizinc (for architecture arm64):	Mach-O 64-bit executable arm64
```
and then
```console
$ file /Applications/MiniZincIDE.app/Contents/Resources/bin/findMUS
/Applications/MiniZincIDE.app/Contents/Resources/bin/findMUS: Mach-O 64-bit executable arm64
```
This renders the findMUS application unusable on `x86` macos machines as currently bundled. This seems to have been introduced with the `2.6.1` version which also has this behavior. Version `2.5.5` does not exhibit this issue, however.

Thanks for your time!

P.S. Checking the other files bundled with the IDE for this version, it seems that the `fzn-gecode` and `minizinc-globalizer` are not built as universal binaries, this time being only compiled for x86.

**Comment by cyderize** [comment]
We've re-uploaded the macOS bundle with the correct binaries for FindMUS and Gecode.

Globalizer can't currently be built as a universal binary, so it will have to remain as x86_64 for now.
