### ISSUE TITLE
Modulo with negative arguments

### ISSUE THREAD

**Issue by IgnaceBleukx** [MiniZinc/libminizinc#566]
I am using Minizinc in the python library CPMpy and came across this bug.

```python
import minizinc

model = minizinc.Model()

model.add_string("var 0..5: x;\n")
model.add_string("var -5..5: y;\n")
model.add_string("constraint (x mod y) == 1;\n")

gecode = minizinc.Solver.lookup("gecode")
inst = minizinc.Instance(gecode, model)

result = inst.solve()
sol = result.solution

print(f"x = {sol.x}")
print(f"y = {sol.y}")
print(f"x mod y = {sol.x % sol.y}")
```
Output: `x = 1, y = -5, x mod y = -4`

I believe this has something to do with the semantics of the modulo operator in C vs Python.
https://torstencurdt.com/tech/posts/modulo-of-negative-numbers/
Are there any plans to resolve issues like this?

**Comment by Dekker1** [comment]
MiniZinc Python does not guarantee that the arithmetic operations in Python and MiniZinc follow the same semantics. This however seems like it would be a library or solver issue as according to the [documentation](https://www.minizinc.org/doc-2.6.2/en/spec.html#arithmetic-operations)

> The result of the modulo operation, if non-zero, always has the same sign as its first operand. The integer division and modulo operations are connected by the following identity: `x = (x div y) * y + (x mod y)`.

This solution would be in violation of these rules.

(Model in just MiniZinc for copying purposes)

```
var 0..5: x;
var -5..5: y;
constraint (x mod y) == 1;
```

**Comment by Dekker1** [comment]
Looking back at this issue, I was mistaken. `x = 1, y = -5` does abide by the semantics that are described above.

So the issue is just a difference between MiniZinc and Python
