### ISSUE TITLE
add scip 8.0.0 for windows

### ISSUE THREAD

**Issue by eyaler** [MiniZinc/libminizinc#571]
please add scip 8.0.0 for windows to paths

**Comment by Dekker1** [comment]
For those of us that do not use Windows, are you able to confirm that SCIP still follows the same directory structure? (https://github.com/MiniZinc/libminizinc/blob/master/solvers/MIP/MIP_scip_wrap.cpp#L39-L40)

(i.e., there is `C:\\Program Files\\SCIPOptSuite 8.0.0\\bin\\libscip.dll`?)

**Comment by eyaler** [comment]
correct
