### ISSUE TITLE
Pow operator in imply constraint

### ISSUE THREAD

**Issue by IgnaceBleukx** [MiniZinc/libminizinc#572]
When using the Minzinc IDE, the compiling the following constraints results in a compiler error:
```
include "globals.mzn";

var 2..10: a;
var 2..10: b;
var bool: p;

constraint (pow(a,3) == b) -> p;
```

output:
```
[stdlib_math:521-3.523-8]
  in let expression
  in variable declaration for 'r'
MiniZinc: flattening error: free variable in non-positive context
```

I was wondering if this is a bug or if such a constraint is not supported?

Minizinc version: 2.6.2

**Comment by Dekker1** [comment]
This does indeed appear to be a bug. Currently, the return value of the `pow` function (to the compiler) appears to be a free variable (even though it is defined by the `int_pow` relationship). I will have a look at adjusting the library to correct this problem
