### ISSUE TITLE
Config exception: no solver with tag chuffed found

### ISSUE THREAD

**Issue by deluxerootit** [MiniZinc/libminizinc#574]
When on my Linux Ubuntu 20 I run: minizinc --solver Chuffed --solver-statistics -O1 --time-limit 2000 model.mzn

I get the following error:

Config exception: no solver with tag chuffed found

Can you help me ? 

My OS is Ubuntu 20.

**Comment by Dekker1** [comment]
How did you install MiniZinc? Chuffed is not automatically included in MiniZinc when you install MiniZinc from the source. You have to install install [chuffed](https://github.com/chuffed/chuffed) and ensure that the solver configuration (the `.msc` file produced by the install target) is placed on the `MZN_SOLVER_PATH`.

The chuffed solver is included in the MiniZinc bundle (downloaded from https://www.minizinc.org/). In this case it should be automatically detected and the command should not give this error.

**Comment by deluxerootit** [comment]
Thanks. I re-installed MiniZinc bundle (downloaded from https://www.minizinc.org/) and the problem is solved now.
