### ISSUE TITLE
Invalid comparision `this == nullptr`

### ISSUE THREAD

**Issue by StefanBruens** [MiniZinc/libminizinc#575]
Building the code spews dozens of warnings like:
```
[   36s] /home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/lib/type_specialise.cpp: In member function 'MiniZinc::Expression::isa<MiniZinc::Id>() constbool':
[   36s] /home/abuild/rpmbuild/BUILD/libminizinc-2.6.2/include/minizinc/ast.hh:556:3: warning: 'nonnull' argument 'this' compared to NULL [-Wnonnull-compare]
[   36s]   556 |   if (nullptr == this) {
[   36s]       |   ^~
```
https://github.com/MiniZinc/libminizinc/blob/a56602765b4294b796c063664733b28f5a663af7/include/minizinc/ast.hh#L551-L557

As can be verified, the check is optimized away even with `-O1`, for both GCC and Clang, and thus is quite pointless:
https://godbolt.org/z/fTr5sPdfP

**Comment by Dekker1** [comment]
I can verify that these pragma statements do at least still prevent the warning from showing for the current version of Clang shipped with the most recent version of MacOS. With the `__clang__` restriction it might not be surprising that GCC does show the warning. (I believe when this was added they didn't have such a warning).

**Comment by StefanBruens** [comment]
Probably the better approach would be to enable `-fsanitize=null` in `Debug` builds (available with Clang and GCC).

**Comment by Dekker1** [comment]
Currently we do not get these message in the toolchain used for our continuous integration or releases. That is why I don't think anyone in the MiniZinc team will invest time in fixing the issue. If you feel strongly about this issue, then I'm happy to review a PR and merge it if it works better and correctly.

**Comment by Dekker1** [comment]
This is no longer an issue since 60791e98e6c67078b76419387c0fa9d110ec28f5, which change `isa` to a static function.
