### ISSUE TITLE
Please use an SOVERSION for libmzn

### ISSUE THREAD

**Issue by StefanBruens** [MiniZinc/libminizinc#576]
Currently, the shared library is unversioned. To be able to better detect incompatibilities, versioning the library would be very welcome.

Depending on ABI compatibility guarantees, the SOVERSION should be chosen appropriately. In case of doubt, increment more often than strictly necessary.

Gecode e.g. uses an SOVERSION unrelated to the release version, i.e. 6.3 has soversion 51.
openCV derives the SOVERSION from (major_version * 100 + minor_version), as minor versions may be ABI incompatible.

The SOVERSION should be set in
https://github.com/MiniZinc/libminizinc/blob/master/cmake/targets/libmzn.cmake
`set_target_properties(mzn PROPERTIES SOVERSION ${libmzn_soversion})`

**Comment by Dekker1** [comment]
We currently do not offer any support or versioning when using the libminizinc C++ library, so I will close this issue.

**Comment by StefanBruens** [comment]
I think this is a bad decision.
1. Adding a SOVERSION is trivial, as shown
2. Not adding one can cause hard to debug issues when an incompatible library is used.
