### ISSUE TITLE
MiniZinc 2.6.2 can't locate cplex dll (Mac M1)

### ISSUE THREAD

**Issue by bokner** [MiniZinc/libminizinc#577]
After switching from 2.5.5 to 2.6.2:

If running my model with CPLEX solver, I'm getting:
```
MiniZinc: error: cannot load cplex dll `/Applications/CPLEX_Studio221/cplex/bin/x86-64_osx/libcplex2210.dylib'
```
The model still works with 2.5.5 and the same cplex dll settings.

I noticed that in the list of solvers for 2.6.2 it's showing `CPLEX <unknown version>` whereas for 2.5.5 it is a correct `CPLEX 22.1.0.0` version.

System: iMac (24-inch, M1, 2021), Monterey 12.3.1

**Comment by cyderize** [comment]
My guess is that this is because `minizinc` is now a universal binary, and CPLEX is only built for x86_64.

Perhaps try `arch -x86_64 minizinc --solvers` and see if it recognises the CPLEX version?
