### ISSUE TITLE
Cancel in "Add data file to project..." open menu crashes

### ISSUE THREAD

**Issue by Cypher1** [MiniZinc/libminizinc#58]
Minizinc crashes in the user hits the cancel button while adding a data file to the project.

Found on: Mac OSX El Capitan with Minizinc v2.0.8

**Comment by guidotack** [comment]
Can you give me a detailed list of steps to reproduce the problem?  In particular, whether you start from an empty project or loaded an existing project, and which menu items or buttons you click to add a data file.

**Comment by colbec** [comment]
On Linux openSUSE 13.2 / minizinc 2.0.8 the menu item "Add files to project..." does not seem to work at all. Click it and no reaction. This happens with a new empty project or a project which already has mzn and mzd files in it.

Take for example a project with two mzn files and one data file. Remove one of the mzn files from the project using the explorer, save the project and attempt to add it back using the menu. No reaction from the menu item, but right clicking in the explorer adds it back no problem. Alternatively start from a new empty project, again Add files to project is silent on click.

I never noticed this bug, I always use the explorer so it never came to light.

**Comment by Cypher1** [comment]
See previous replies for steps.
I have had it happen with every 'opening' mechanism.

**Comment by AntonKhorev** [comment]
On Windows 7:

* File | Add files to project... menu item doesn't do anything.
* When adding files from project explorer, pressing Cancel works correctly.

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.

**Comment by Cypher1** [comment]
I don't believe this has been solved.
I'm happy to be corrected but haven't received an update with any solution.

Thanks

**Comment by Dekker1** [comment]
Thank you for you message. I've created a new issue in the appropriate repository: https://github.com/MiniZinc/MiniZincIDE/issues/41

**Comment by Cypher1** [comment]
Thanks very much didn't realise the ide was separate.

Cheers
