### ISSUE TITLE
Flattening MZNC_connect instances

### ISSUE THREAD

**Issue by siala** [MiniZinc/libminizinc#580]
Hi, 

I'm getting these warnings with  the MZNC_connect models (from the 2021 competition) when compiling into fzn: 

Command: 
minizinc --compile --solver org.minizinc.mzn-fzn MZNC_connect/connect__0018.mzn --fzn file.fzn 

Warnings: 
Warning: variable `i` shadows variable with the same name in line 2933.10
./MZNC_connect/connect__0018.mzn:2935.52-55

Is this fine?

**Comment by cyderize** [comment]
Yes, that is normal. The warning is just giving an indication that there may be a mistake in the model (variable of the same name in scope as a variable `i` is declared in line 2933 and then a new variable `i` is used in a comprehension in line 2935).

In this case the model is correct, so you can simply ignore this warning.

**Comment by siala** [comment]
Thank you for the reply. In this case what is solver supposed to do? use the second one?

**Comment by Dekker1** [comment]
This is purely a modelling warning. There is just a big danger that the modeller might mean the outer scope variable, even though the inner scope one will always be used.

If both variables are required in the FlatZinc that is send to the solver, then the variables would have been renamed to be different.

**Comment by siala** [comment]
Ok that's good to know. Thank you!
