### ISSUE TITLE
Flatzinc compilation failed on an instance of this year's challenge test

### ISSUE THREAD

**Issue by siala** [MiniZinc/libminizinc#582]
Hi, 

When running the following command: 

minizinc --compile --solver org.minizinc.mzn-fzn  -o out.fzn community-detection_mzn.mzn rnd_n100_e50_s50_d30_c9_p30_json.dzn

the generation fails with the message "Error: syntax error, unexpected ':', expecting '}'"

Best,

**Comment by cyderize** [comment]
I believe that data file is supposed to be in JSON format. If you change the file extension to be `.json` instead of `.dzn` it should work.

**Comment by siala** [comment]
I did and it doesn't work.

**Comment by siala** [comment]
This is working . Thank you. 
So from now json can be used as a data file format (the same way as .dzn)? any other extension for data files?

**Comment by cyderize** [comment]
`.json` and `.dzn` are the only data input formats supported (and they don't don't affect FlatZinc solvers since MiniZinc will still produce the same FlatZinc to pass to the solver regardless of the data input file type).
