### ISSUE TITLE
2.6.2 : FZ syntax error, unexpected '(' expecting FZ_ID 

### ISSUE THREAD

**Issue by Madoxen** [MiniZinc/libminizinc#588]
I've been redirected to issues from [here](https://stackoverflow.com/questions/72353135/minizinc-seemingly-generates-invalid-fz-code)
I'm getting a cryptic error during compilation to FlatZinc:
```
Error: Unknown character in line no. 1914
Error: Unknown character in line no. 1914
Error: Unknown character in line no. 1914
Error: syntax error, unexpected '(', expecting FZ_ID in line no. 1914
```

Below I've attached the FlatZinc output (with line numbers in square brackets):
```
[1913] constraint int_lin_eq([1,1,1,-1],[X_INTRODUCED_894_,X_INTRODUCED_908_,X_INTRODUCED_922_,X_INTRODUCED_955_],0):: defines_var(X_INTRODUCED_955_);
[1914] constraint '-'(X_INTRODUCED_954_,X_INTRODUCED_952_,X_INTRODUCED_956_):: defines_var(X_INTRODUCED_956_);
[1915] constraint '-'(X_INTRODUCED_956_,X_INTRODUCED_955_,X_INTRODUCED_957_):: defines_var(X_INTRODUCED_957_);
[1916] constraint int_ne_reif(X_INTRODUCED_963_,0,X_INTRODUCED_962_):: defines_var(X_INTRODUCED_962_);
```

It seems like minizinc is generating invalid FZ code. 

I've attached my full model with FZ output below:
[enroll.mzn.txt](https://github.com/MiniZinc/libminizinc/files/8762057/enroll.copy.txt)
[enroll.fzn.txt](https://github.com/MiniZinc/libminizinc/files/8762066/enroll.fzn.txt)

**Comment by Dekker1** [comment]
What command are you using to compile the FlatZinc file? It is important to know what MiniZinc library (for what solver) is being used.

**Comment by Dekker1** [comment]
It seemed that there was an internal mismatch between the version of the operator that was matched at type checking and the version that was actually used during flattening because the types of the arguments was different after they were flattened. Because of this problem the name of the operator wasn't correctly converted to it's FlatZinc equivalent.

The issue should be resolved in the next release

**Comment by plchd** [comment]
I've checked the commits on my machine, everything seems to work. Thank you, issue can be closed now 👍
