### ISSUE TITLE
No easy way to build distribution

### ISSUE THREAD

**Issue by expipiplus1** [MiniZinc/libminizinc#59]
The binary distribution contains a bunch of helper scripts, such as `minizinc` `flatzinc` and `mzn-g12fd` which seem to be either unfindable or included in minizinc-old.

It would be great to be able to build all of these programs from this repository, or in the case of the helper scripts, have them included.

**Comment by guidotack** [comment]
Unfortunately some of these helpers are not available under an open-source license, so we can't include them in the repository. We are working on replacements for release 2.1.0.

**Comment by expipiplus1** [comment]
Super, looking forward to it!
