### ISSUE TITLE
Release contains reference to develop version

### ISSUE THREAD

**Issue by MaxOstrowski** [MiniZinc/libminizinc#591]
The Minizinc 2.6.3 release tag branch [2.6.3](https://github.com/MiniZinc/libminizinc/releases/tag/2.6.3) contains a reference to the development version of `minizinc-python`.
In file `libminizinc/tests/requirements.txt`
`git+https://github.com/MiniZinc/minizinc-python.git@develop#egg=minizinc`
It should be branch `0.6.0`

As the `develop` branch of minizinc-python is now incompatible with the 2.6.3 release, cloning the release tag and running the tests fails.
This might break (and did :smile_cat: ) CI's of other projects that depend on minizinc and run these tests to ensure that the installation worked.

**Comment by Dekker1** [comment]
Hi Max,

Although I understand that that is how it is supposed to work, we develop MiniZinc and the MiniZinc Python connection side by side. Where features and changes in one, often require change in the other. As such, we tend to use the develop build from one in the other. This might in the future be resolved using a mono repo or some other way, but at the moment tracking individual tags would not be very productive for our development process.

Although I understand the issue, it should be remembered that the test suite included in this repository is meant to test the MiniZinc compiler. It is not meant to test solvers or to test whether installation works. For such situations other test suites might be devised. For example, the MiniZinc challenge has a good test suite for the functionality of solvers, and for whether an installation is correct only a few minimal tests should suffice.

I will close this issue for now, but I do understand the issue and I would be happy to contribute to other solutions if required.
