### ISSUE TITLE
2.6.2: Memory violation detected

### ISSUE THREAD

**Issue by Madoxen** [MiniZinc/libminizinc#592]
I'm encountering the following error message
```
MiniZinc error: Memory violation detected (segmentation fault).
This is a bug. Please file a bug report using the MiniZinc bug tracker.
Aborted (core dumped)
```

I'm sending my model and data in the attachment.
[model.zip](https://github.com/MiniZinc/libminizinc/files/8840315/model.zip)

I use the following command to solve the model:
`minizinc -i enroll.mzn data/trivial_break.dzn -p 12 --output-time --solver coinbc`

The problem vanishes when I disable the following constraint on line 166
```
array[Student, Day] of var int: break_preference_penalties_day;
constraint forall(s in Student, d in Day)(
  let {
    array[Group] of var bool: day_group_matrix = [assignment[s,g] /\ group_day[g] == d | g in Group];
    array[Group] of var Time: group_day_starts = [if day_group_matrix[g] then group_start[g] else max(Time) endif | g in Group];
    array[Group] of var Time: group_day_ends = [if day_group_matrix[g] then group_end[g] else min(Time) endif | g in Group];
    array[Group] of var Time: group_day_durs = [if day_group_matrix[g] then group_duration[g] else 0 endif | g in Group];
    var Time: min_start = min(group_day_starts);
    var Time: max_end = max(group_day_ends);
    var int: dur = sum(group_day_durs);
    var int: time = (max_end - min_start) - dur;
    var int: penalty = if time >= 0 then time else 0 endif;
  } in
  break_preference_penalties_day[s,d] = penalty
);
```

Changing the solver to gecode from coinbc seems to work as well.

**Comment by Dekker1** [comment]
Did you try the newest version on MiniZinc? With MiniZinc version 2.6.3 the model with the supplied data seems to run fine.

**Comment by Madoxen** [comment]
Hey, I've checked the the newest version 2.6.4v, the bug reappeared. Could we reopen the issue?

**Comment by cyderize** [comment]
I can't seem to reproduce this on `develop` or in 2.6.3 on Windows/Linux. What operating system are you using?

Since switching to Gecode fixes it, it could be happening inside CBC and not in the compiler. Could you try running it with `-v` and check if you see `Calling CbcMain with command 'cbc -threads 12 -solve -quit'...` before the segfault?

**Comment by Madoxen** [comment]
@cyderize I've run my model again. (I've changed it a bit to speed up compilation times, since they are terribly slow for me) I'm attaching output and code-files below: 
[sample.zip](https://github.com/MiniZinc/libminizinc/files/8886991/sample.zip)
