### ISSUE TITLE
 Error in tutorial example

### ISSUE THREAD

**Issue by iortio** [MiniZinc/libminizinc#595]
I get an error when running the following example from the tutorial:

% variables
var float: R;        % quarterly repayment
var float: P;        % principal initially borrowed
var 0.0 .. 10.0: I;  % interest rate

% intermediate variables
var float: B1; % balance after one quarter
var float: B2; % balance after two quarters
var float: B3; % balance after three quarters
var float: B4; % balance owing at end

constraint B1 = P * (1 + I) - R;
constraint B2 = B1 * (1 + I) - R;
constraint B3 = B2 * (1 + I) - R; 
constraint B4 = B3 * (1 + I) - R;

solve satisfy;

output [
 "Borrowing ", show_float(0, 2, P), " at ", show(I*100.0), 
 "% interest, and repaying ", show_float(0, 2, R), 
  "\nper quarter for 1 year leaves ", show_float(0, 2, B4), " owing\n"
];

**Error: Gecode: Float::linear: Number out of limits
=====ERROR=====
Process finished with non-zero exit code 1.
Finished in 54msec.**

Does anyone know why? Thanks.

**Comment by Dekker1** [comment]
Gecode does not work with unbounded floating point values. As mentioned in the text, this example is meant to be run using a linear solver, in particular CBC:

> While Gecode (the default solver in the MiniZinc bundled binary distribution) does support floating point variables, a mixed integer linear programming (MIP) solver may be better suited to this particular type of problem. The MiniZinc distribution contains such a solver. We can invoke it by selecting COIN-BC from the solver menu in the IDE (the triangle below the Run button), or on the command line using the command minizinc --solver cbc:
