### ISSUE TITLE
Feature request: declaring several variables with one statement

### ISSUE THREAD

**Issue by jarble** [MiniZinc/libminizinc#596]
The model from the [MiniZinc tutorial](https://www.minizinc.org/doc-2.5.5/en/modelling.html) includes this series of variable declarations:
```
int: flour;  %no. grams of flour available
int: banana; %no. of bananas available
int: sugar;  %no. grams of sugar available
int: butter; %no. grams of butter available
int: cocoa;  %no. grams of cocoa available
```

I tried to declare all of these variables with just one statement, but this appears to be a syntax error:

`int: flour, banana, sugar, butter, cocoa;`

Does MiniZinc have an option to declare several variables with one statement like this?

**Comment by Dekker1** [comment]
MiniZinc would generally use arrays with enumerated types as indexes for this purpose:
```
enum Ingredients = {Flour, Banana, Sugar, Butter, Cocoa};
array[Ingredients] of int: quantity; % quantity of ingredient available
```

However, since the example you refer to is at the very start of the tutorial, this topic has not been discussed yet.

**Comment by jarble** [comment]
@Dekker1 I wish this simpler syntax were supported as well: is there a way to initialize several global variables in one line without creating an array to store each variable?

I'd prefer to write something like `int: flour, banana, sugar, butter, cocoa;` instead of putting all of the variables in an array.

**Comment by Dekker1** [comment]
There is no such syntax in MiniZinc currently, and although it could quite easily be added, I'm not sure what advantage this would have.

In my experience, when declaring many variables of the same type, either these variables all have distinct meaning that should likely be documented through comments, or they should have been part of an array. I do not see the need for such simplification, since I would never use it. If there is a convincing use-case or other users have the same problem, then we could reconsider this issue.

**Comment by jarble** [comment]
@Dekker1  This simplified syntax would be useful when declaring local variables, since it currently isn't possible to [declare enums in let-blocks](https://github.com/MiniZinc/libminizinc/issues/594).

**Comment by Dekker1** [comment]
I think the usage of enums in let-blocks is really only interesting if you use enum constructors, e.g., `enum REG_NODE = Yes(1..n) ++ No(1..n)` where the `n` would be different in different calls to the let-expression.

If you want to replace the usage of an enumerated type with declarations, then the number of declarations must be static in all occurrences of the let-expression. This means that you could have also put the `enum` as a seperate item.

I admit that it is not great that this would pollute the global namespace with the name of the enumerated type, but I think that is a very different issue.
