### ISSUE TITLE
How serious is disabling hardware random number generation?

### ISSUE THREAD

**Issue by jplauri** [MiniZinc/libminizinc#602]
On running Minizinc on my machine (AMD Ryzen 9 3900X CPU), I get the following warnings:
>WARNING: CPU random generator seem to be failing, disabling hardware random number generation
>WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
After quick googling, this seems to be related to an AMD microcode bug, see [here](https://askubuntu.com/questions/1264439/warning-cpu-random-generator-seem-to-be-failing-disable-hardware-random-number) or [here](https://arstechnica.com/gadgets/2019/10/how-a-months-old-amd-microcode-bug-destroyed-my-weekend/). The solution is apparently a BIOS update.

Without knowing much about Minizinc's internals, how serious are these warnings? With an *enabled* hardware RNG (i.e., a BIOS update), should one expect a difference in runtime? Perhaps the answer is "maybe, you need to try it on your instances" but is there anything one might be able to say about this?

**Comment by Dekker1** [comment]
MiniZinc does not use many random numbers. Unless you use the random number functions from the standard library, MiniZinc should not use the random number generator.

**Comment by jplauri** [comment]
Great, thank you - good to know :-)
