### ISSUE TITLE
counting solutions with Chuffed, missing -s in IDE

### ISSUE THREAD

**Issue by dan1221** [MiniZinc/libminizinc#607]
I'm trying to count solutions using the MiniZinc IDE.  This seems like a common desire when considering combinatorial objects.  But the MiniZinc Handbook is strangely silent on the topic, except for Section 2.6.2. Effective Generators: "Imagine we want to count the number of triangles (K3 subgraphs) appearing in a graph," involving using "sum" to count true predicates by iterating over an integer range.  But "sum" apparently isn't able to count solutions to global constraints, which typically involve a search space consisting of arrays, not just integer ranges.  

The IDE Configuration Editor has a checkbox for "Output Solving Statistics".  That works fine with the Gecode solver, but not with Chuffed.  Unfortunately, Gecode is much slower than Chuffed on the models I've tried, so I can't use it on the larger models.  Is there a way to get Chuffed to output the number of solutions?

Can "sum" be enhanced to iterate over an array, like global constraints, instead of just integer ranges?

Here's an example:
```
% count involutions, a permutation that equals its inverse; OEIS:A000085
include "inverse_fn.mzn"; 

int: n=10;
set of int: N = 1..n;
array[N] of var N: a;
constraint alldifferent(a);   

predicate equals_inverse(array[N] of var N: b) =  % involution 
let {array[N] of var N: c = inverse(b);} in b = c; 

constraint equals_inverse(a);
solve satisfy;

```
If we use "sum" to count involutions, we have to do some serious rearrangement of the above code, and it runs a lot slowerl

```
% count involutions, a permutation that equals its inverse; OEIS:A000085
include "inverse_fn.mzn"; 
include "arg_sort.mzn";

int: n;
set of int: N = 1..n;

predicate equals_inverse(array[N] of var N: b) =  % involution 
 alldifferent(b) /\ 
   let {array[N] of var N: c = arg_sort(b);} in b = c;  % had to switch to arg_sort instead of inverse

     var int: total =   % this is both awkward and inefficient
     if n==2 then
       sum(i,j in 1..n)(equals_inverse([i,j]))  
     elseif n==3 then
       sum(i,j,k in 1..n)(equals_inverse([i,j,k]))         
     elseif n==4 then
       sum(i,j,k,l in 1..n)(equals_inverse([i,j,k,l]))
     elseif n==5 then
       sum(i,j,k,l,m in 1..n)(equals_inverse([i,j,k,l,m]))
     elseif n==6 then
       sum(i,j,k,l,m,q in 1..n)(equals_inverse([i,j,k,l,m,q]))
     else 0
     endif;

   solve satisfy;

   output ["number of solutions is ", show(total)];
```

**Comment by Dekker1** [comment]
Your initial solution would be the preferred MiniZinc way is to use the solution count as produced in the statistics.

There is a `nSolutions` statistic field that is produced by the MiniZinc driver, and thus is independent from the solver used. It seems, however, that there is currently an issue where the command line flag used by the IDE does not output this statistic. We will resolve this for the next MiniZinc release.

A workaround is to use the command line:
```
minizinc -a -s --solver chuffed model.mzn
```
which outputs `%%%mzn-stat: nSolutions=9496` for your model.

Or, you can manually add the `-s` parameter using the "Add custom parameter" option in the IDE.
<img width="469" alt="Screen Shot 2022-09-01 at 10 44 33" src="https://user-images.githubusercontent.com/1564252/187808997-088127ef-58a4-4d23-8ee0-f2e91602fbf4.png">

**Comment by dan1221** [comment]
Thanks!!
