### ISSUE TITLE
Feature request: symbolic solution count

### ISSUE THREAD

**Issue by dan1221** [MiniZinc/libminizinc#614]
For many models, the number of solutions could be given symbolically.  For example, a model of permutations of size n would have n! solutions.  It would be very useful to have perhaps an optional solver that could find such symbolic solution counts, for example by applying the Polya enumeration theorem
   https://en.wikipedia.org/wiki/P%C3%B3lya_enumeration_theorem
and more general symbolic combinatorics.
   https://en.wikipedia.org/wiki/Symbolic_method_(combinatorics)
   http://algo.inria.fr/libraries/

**Comment by Dekker1** [comment]
This is indeed interesting, and I would love to see development in this direction. I believe you are right that you would need to build a MiniZinc (FlatZinc) solver back-end that performs the symbolic counting. However, we currently do not have the developmental resources to focus on such a solver back-end ourselves. If anyone has the expertise and time to develop such a back-end, then I would encourage them to contact the MiniZinc team to discuss what additional features might be required from the MiniZinc solver interfaces. I would be more than happy to assist in that regard.
For now I will close this issue.
