### ISSUE TITLE
How to get file 'mzn2fzn'?

### ISSUE THREAD

**Issue by qkxwxy123** [MiniZinc/libminizinc#624]
My version is 2.6.2. When I use minizinc, the file mzn2fzn is missed. How can I get it now? Thanks.

**Comment by qkxwxy123** [comment]
I have used `minizinc -c --solver org.minizinc.mzn-fzn`. But the feedback is `Error: error: Error: no model file given.`

**Comment by zayenz** [comment]
The error means that you need to supply the model file that should be translated as well. 

For example
```
$ minizinc -c --solver org.minizinc.mzn-fzn my-model-file.mzn my-data-file.dzn
```
