### ISSUE TITLE
scip crashes

### ISSUE THREAD

**Issue by oferst** [MiniZinc/libminizinc#630]
getting 
MiniZinc error: Memory violation detected (segmentation fault).
This is a bug. Please file a bug report using the MiniZinc bug tracker.

when running with --solver scip 
it runs ok with other engines.

**Comment by Dekker1** [comment]
What version of SCIP are you using? I believe there have been some versions of SCIP where the binary compatibility of the shared libraries was broken. I believe that our SCIP interface works with the newest version of SCIP

**Comment by oferst** [comment]
Thank you,
when I run 'scip' as a stand-alone I get

SCIP version 8.0.3 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: Soplex 6.0.3] [GitHash: 62fab8a2e3]


-- Ofer

**Comment by Dekker1** [comment]
I talked to Jason, and he believes that this was a problem we had resolved in the current `develop` branch (available in the next release)

**Comment by cyderize** [comment]
@oferst: I believe SCIP 8 should now be working with MiniZinc 2.7.0. Please let us know if you have any issues.
