### ISSUE TITLE
Unable to run sample from doc.

### ISSUE THREAD

**Issue by ArtyomKaltovich** [MiniZinc/libminizinc#632]
Hello.

I am trying to execute real number problem from the doc https://www.minizinc.org/doc-2.6.4/en/modelling.html#real-number-solving.

**Expected behavior:** 

The sample executed successfully, as described in the doc.

**Actual behavior:**

```sh
$ minizinc --solver cbc zn/1.mzn zn/1.dzn
Error: evaluation error: Abort: Unable to create linear formulation for the `float_times(P, X_INTRODUCED_1_, X_INTRODUCED_2_)`
        constraint. To flatten this instance a quadratic constraint is required, but the
        usage of these constraints is currently disabled for the selected solver. Define
        `QuadrFloat=true` if your solver supports quadratic constraints, or use
        integer variables.
/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/linear/redefinitions.mzn:327.3-341.7
  in if-then-else expression
/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/linear/redefinitions.mzn:334.5-340.5
  in call 'abort'
```  

**Steps to reproduce:**

Copy mzn and dzn files, execute ``minizinc --solver cbc zn/1.mzn zn/1.dzn``

MacOS 12.6.2
Apple M1 Pro
MiniZinc to FlatZinc converter, version 2.6.4, build 570825159

Thank you in advance

**Comment by Dekker1** [comment]
I cannot recreate this issue with the files that can be downloaded from the documentation:
- https://www.minizinc.org/doc-2.6.4/en/downloads/loan.mzn
- https://www.minizinc.org/doc-2.6.4/en/downloads/loan1.dzn

Running `minizinc --solver cbc loan.mzn loan1.dzn` gives

```
Borrowing 1000.00 at 4.0% interest, and repaying 260.00
per quarter for 1 year leaves 65.78 owing
----------
```

The error message would suggest that you are running the loan model without any data. In this case the problem becomes a quadratic model that cannot be solved with CBC (you can use a different solver though).

**Comment by ArtyomKaltovich** [comment]
Hello @Dekker1 Thank you.

Data file was empty, I haven't copy data to it.

Sorry for your time.
