### ISSUE TITLE
std definition of lex_lesseq and friends inflates search space

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#634]
The `std` definition of `lex_lesseq` introduces extra variables that can be left nonfixed. This is a problem in all-solutions search, because you can get tons of duplicated solutions corresponding to different, irrelevant values for those variables. OR-Tools, for example, suffers from that, because it does not (at least not `v9.2.9972`) support `lex_lesseq` natively.

Here is a model `bug.mzn`:
```
include "globals.mzn";

array[1..3] of var 1..2: x;
array[1..3] of var 1..2: y;

constraint lex_lesseq(x,y);
```
A Gecode session:
```
$ minizinc -s -a --non-unique bug.mzn
[...]
%%%mzn-stat: nSolutions=36
```
An OR-Tools session:
```
$ minizinc --solver or-tools -s -a --non-unique bug.mzn
[...]
%%%mzn-stat: nSolutions=195
```
I want to find all solutions to a model of mine, but it does not work woth OR-Tools because of this phenomenon.
Can you suggest a better default definition?

**Comment by a1880** [comment]
From MiniZinc 2.6.4, I am getting 36 solutions with OR Tools (or-tools_flatzinc_VisualStudio2019-64bit_v9.2.9972)
Gecode 6.3.0 also yield 36 solutions.

**Comment by matsc-at-sics-se** [comment]
The crucial flag is `--non-unique`. There are 195 - 36 = 159 redundant, duplicate solutions because of those introduced extra variables.  With `-s` you will also see:
```
%%%mzn-stat: nSolutions=195
```
This is with OR-Tools v9.5.2237 now.
Gecode does not have this problem, because it supports `lex_lesseq` natively.

**Comment by matsc-at-sics-se** [comment]
Here is a formulation that does not inflate the search space. Please consider replacing the `std` formulations by it and its variants.
```
predicate fzn_lex_lesseq_int(array[int] of var int: x ::promise_ctx_antitone,
                             array[int] of var int: y ::promise_ctx_monotone) =
    let { int: lx = min(index_set(x)),
          int: ux = max(index_set(x)),
          int: ly = min(index_set(y)),
          int: uy = max(index_set(y)),
          int: size = min(ux - lx, uy - ly) + 1,
          array[0..size] of var bool: unk,
          % unk[i] is true while constraint is not yet entailed
        }
    in
    unk[0] /\
    forall(i in 0..size-1) (
        if not unk[i] then
            not unk[i+1]
        elseif x[lx + i] = y[ly + i] then
            unk[i+1]
        else
            not unk[i+1] /\
            x[lx + i] < y[ly + i]
        endif
    ) /\
    (unk[size] -> (ux - lx <= uy - ly));
```

**Comment by Dekker1** [comment]
The earlier definition of `fzn_lex_less` (and family) did not use implications. They actually functionally defined the `b` variables. This was changed to promote the possibility for using half-reification. However, this change might not be worthwhile for all solvers so I will revert the standard decomposition to its former definition.

**Comment by matsc-at-sics-se** [comment]
Thank you Jip. My variant indeed defines the variables functionally. Don't forget the other definitions in the `fzn_lex` family.

Free variables are likely to be a problem for all solvers when doing all-solutions search.  Could there be more `std` definitions that introduce free variables?

**Comment by Dekker1** [comment]
In 6ed2cfeec8625c090aa611e11b7dfa94345865b6 I have essentially reverted the changes from 2b10426d3fdfae178227f0de025bf9883f49b5ed, which impacted the Boolean and integer (non-reified) variants. Unrelated, I also moved the definition of the final Boolean to be earlier (as it will be fixed) in all versions of `fzn_lex_less*.mzn`.

Did you see something that I missed in this commit, or was it just meant to be a general reminder?

We generally avoid any free variables in the `std` library, but I wouldn't be able to guarantee there is no other cases. They are not always easy to spot. If you find any others, then I would be happy to take a look.

**Comment by matsc-at-sics-se** [comment]
I didn't look at the actual commit. It was meant to be a general reminder.

I will make a scan of the `std` library.
