### ISSUE TITLE
Feature Request: ceil, floor and round for var float

### ISSUE THREAD

**Issue by raphaelboudreault** [MiniZinc/libminizinc#636]
At the moment, the `ceil`, `floor` and `round` are part of the MiniZinc builtins for the `float` type. In the same way as the `cos`, `sin`, `log`, etc. functions, it could be great to have functions for the `var float` type using new flatzinc constraints `fzn_ceil`, `fzn_floor` and `fzn_float`, which can be easily defined with FlatZinc builtins float linear inequalities (or overridden by solvers as builtins).

**Comment by guidotack** [comment]
Good point. I've added the functions for the next release. The only one that's not trivial is ``round`` when the domain of the variable ranges from negative to positive. It's now defined as

```
predicate float_round(var float: x, var int: y) =
    if lb(x) >= 0 then float_floor(x+0.5, y)
    elseif ub(x) <= 0 then float_ceil(x-0.5, y)
    else if x < 0 then float_ceil(x-0.5, y) else float_floor(x+0.5, y) endif endif;
```

So the case where `x`  is strictly positive or negative is fine, but the general case requires some Boolean logic that doesn't translate into very simple linear constraints.
