### ISSUE TITLE
Compiler hangs

### ISSUE THREAD

**Issue by anonymous192837** [MiniZinc/libminizinc#637]
MiniZinc hangs when compiling the following model. I tried to debug, and perhaps the restore loop at the bottom of flatten_let.cpp needs to be reversed.

```
predicate foo(1..3: start) =
  start = 3 \/
  let {
    1..1: bar = 1;
    1..3: start2 = start + 1;
  } in
    foo(start2) /\ start2 = start2;

constraint foo(1);
```

**Comment by guidotack** [comment]
@anonymous192837 You are absolutely right, the loop that restores the flat bindings was incorrect. Thanks! I'll push a fix.
