### ISSUE TITLE
Incorrect unsatisfiability

### ISSUE THREAD

**Issue by anonymous192837** [MiniZinc/libminizinc#639]
This model is considered unsatisfiable (I tried several solvers):

```
var 1..2: x;

array[1..2] of var opt 1..1: arr;

constraint exists(y in {-1, 1})(x + y in 1..2 /\ absent(arr[x + y]));
```

But `x = 1, arr = [<>, <>]` is a feasible solution. In fact, setting `x = 1` gives this solution.

**Comment by anonymous192837** [comment]
I found that this is already considered unsatisfiable. Maybe it's related.

```
opt 1..1: abs = <>;
constraint absent(abs);
```

**Comment by Dekker1** [comment]
Thank you for reporting the issues, and trying to simplify it.

It looks like these are two seperate issues. The second issue I could locate rather quickly. The parameter evaluation function would look at the domain expression `1..1` and decide that this would mean that this is the value of `abs` (not considering the fact that this is an optional type). I've corrected this.

This does not yet solve the initial problem, I will further investigate.
