### ISSUE TITLE
MiniZinc 2.7.0: flattener error (wrong answer)

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#643]
This is a continuation of #620, which apparently was not quite fixed.
The following model works OK with Gecode:
```
var 0..1: A;
var 0..1: B;
var 0..1: C;
constraint
    not((A!=1 /\ C=1) -> (true xor (B!=1 -> C!=1)));
```
```
$ minizinc -a --solver  gecode latest.mzn
A = 0;
B = 1;
C = 1;
----------
==========
```
but not with `chuffed`, `ortools`, and other solvers:
```
$ minizinc -a --solver  chuffed latest.mzn
A = 0;
B = 1;
C = 1;
----------
A = 0;
B = 0;
C = 1;
----------
==========
```
That second answer is wrong.
So even though no global constraints are in play, something in the respective definition directories makes the `.fzn` come out differently.

**Comment by krzku** [comment]
FYI, the result from JaCoP is also correct ;) 
It seems that minizinc compiler generates the same fzn file for chuffed as well. I did not checked or tools.

**Comment by krzku** [comment]
It seems that minizinc compiler, for some reason, generates wrong bool_clause. For gecode and JaCoP we get

constraint bool_clause([X_INTRODUCED_4_],[]);

but for chuffed 

constraint bool_clause([X_INTRODUCED_4_],[X_INTRODUCED_4_]);

**Comment by matsc-at-sics-se** [comment]
I tracked it down to the following piece of code in `std/redifinitions-2.0`:
```
predicate bool_clause_reif(array[int] of var bool: as,
                           array[int] of var bool: bs,
                           var bool: b) =
  clause(as,bs++[b]) /\
  forall (i in index_set(as)) (as[i] -> b) /\
  forall (i in index_set(bs)) (bs[i] \/ b);
```
With that enabled, flattening goes wrong and generates:
```
var 0..1: A:: output_var;
var 0..1: B:: output_var;
var bool: X_INTRODUCED_4_ ::var_is_introduced :: is_defined_var;
var 1..1: C:: output_var = 1;
constraint bool_clause([X_INTRODUCED_4_],[X_INTRODUCED_4_]);
constraint int_ne(A,1);
constraint int_eq_reif(B,1,X_INTRODUCED_4_):: defines_var(X_INTRODUCED_4_);
solve  satisfy;
```
With that disabled, flattening produces correct FlatZinc, although it contains a fishy `bool_clause`:
```
var 0..1: A:: output_var;
var 0..1: B:: output_var;
var bool: X_INTRODUCED_4_ ::var_is_introduced :: is_defined_var;
var 1..1: C:: output_var = 1;
constraint int_ne(A,1);
constraint int_eq_reif(B,1,X_INTRODUCED_4_):: defines_var(X_INTRODUCED_4_);
constraint bool_clause([X_INTRODUCED_4_],[]);
solve  satisfy;
```
