### ISSUE TITLE
When to use deopt?

### ISSUE THREAD

**Issue by anonymous192837** [MiniZinc/libminizinc#644]
These models give what appear to be internal error messages:

```
array[1..2] of var opt bool: arr;

constraint arr[1] = true -> arr[2] = true;

% flattening error: cannot find matching declaration
```

and

```
array[1..1] of var opt 1..1: a;
array[1..1] of var 1..1: b;

constraint occurs(a[b[1]]) -> a[b[1]] + b[1] - 1 = 1;

% undefined identifier X_INTRODUCED_8_ in line no. 23
```

and

```
var opt 1..1: x;
array[1..1] of var 1..1: arr;

constraint x = count(i in 1..1)(arr[i] = 1);

% could not replace binary operator by call to count_eq
```

All of these can be fixed by calling `deopt` before attempting equality/arithmetic on the optional variables.

But it's not clear to me when `deopt` is required. In fact, consider this modification of the first model, with `deopt`:

```
array[1..2] of var opt bool: arr;

constraint deopt(arr[1]) = true -> deopt(arr[2]) = true;
```

Then one of the solutions is `arr = [<>, <>]`, but `deopt(<>)` is invalid.

Can someone please clarify what the semantics of `deopt` are, and when it is required to use it?

**Comment by guidotack** [comment]
These were all bugs in the handling of option types (3 different bugs, in fact). I have pushed fixes to the develop branch, which will be included in the next release.
In general, you should never have to use `deopt` in normal model code. It is only required to define new predicates on option type arguments, and the rule is that you're only allowed to use `deopt` when it is "guarded" by a test using `occurs` or `absent`, i.e., in a position where it is guaranteed that the value you're trying to de-opt exists.

**Comment by anonymous192837** [comment]
Thanks for your very swift response and fixes.

Do I understand correctly that `<>` does not "propagate" in arithmetic/array access/etc? For example, I expected this to result in `x = <>`:

```
opt 1..2: abs = <>;
opt 2..3: x = abs+1;
```

but instead `abs` is considered 0 in this context:

```
MiniZinc: result of evaluation is undefined: parameter value out of range, declared range of `x' is 2..3, but assigned value is 1
```

If it should propagate, please also consider this case:

```
array[1..1] of 1..1: arr = [1];
opt 1..1: index = <>;
opt 1..1: value = arr[index];

% evaluation error: undeclared identifier '_absent'
```

**Comment by cyderize** [comment]
Operators treat `<>` as the identity element if there is one for the operation - so for addition, `<>` behaves like `0`, and for multiplication, `<>` behaves like `1`. If you use the 'weak' version of addition (the `~+` operator), it will propagate the `<>`:

```
opt 1..2: abs = <>;
opt 2..3: x = abs~+1; % x = <>
```

Except that apparently the weak `~-` and similar operators are missing for `par` optional types - we'll add it to the library for the next release to fix that.

In the second case, that is again a compiler bug, and should actually work and give `value = <>`. We will fix that for the next release as well.
