### ISSUE TITLE
MiniZinc 2.7.0: std expansion of ^/2 is wrong

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#652]
The following model gives 15 solutions, as expected:
```
var -2 .. 2: A :: add_to_output;
var  0 .. 2: B :: add_to_output;
var int: VALUE :: add_to_output = A ^ B;
```
The following model is the same, except now the domain of `B` includes -1 and -2.
MiniZinc reports it as UNSAT:
```
var -2 .. 2: A :: add_to_output;
var -2 .. 2: B :: add_to_output;
var int: VALUE :: add_to_output = A ^ B;
```

**Comment by Dekker1** [comment]
This problem turned out to be in the redefinition used in the Gecode library. I've opened a pull request that resolves the issue: https://github.com/Gecode/gecode/pull/159

I will close this issue here, since it does not involve the MiniZinc compiler.
