### ISSUE TITLE
Minizinc segfaults with Run+check from GUI

### ISSUE THREAD

**Issue by PerMildner** [MiniZinc/libminizinc#662]
I have model file and accompanying project that crashes minizinc (2.7.0, 2.7.1) on macOS with segmentation fault.

The model, project, and checker originates with a Coursera course, so I do not want to post the reproducer publicly.

I have attached a crashdump but unfortunately there is no debug info in the minizinc executable, it seems.

[crashdump.txt](https://github.com/MiniZinc/libminizinc/files/11132570/crashdump.txt)

Let me know and I can send an archive that reproduce the problem.

**Comment by Dekker1** [comment]
I don't think we can easily locate the problem without the model instance. Could you email the model and a data file where it happens to my email, `jip <dot> dekker <at> monash <dot> edu`?

**Comment by Dekker1** [comment]
Resolved by 30f996c23325dd125fe377894e7256d40224bf3e
