### ISSUE TITLE
Assertion failure in chain compression

### ISSUE THREAD

**Issue by anonymous192837** [MiniZinc/libminizinc#676]
The following two models trigger the error added in 99536961fd5d05e20065416a99054a1db1fdf3af:

`ERROR: We expect propagation to have taken care of all fixed variables before chain propagation. This can be ignored in release builds, but should be investigated by the MiniZinc Team`

Model 1:

```
array[1..2, 1..2] of var bool: arr;

constraint if arr[1, 1] then forall(x in 1..2)(not arr[2, x]) endif;

constraint count([arr[2, 1]]) = 1;

solve satisfy;
```

Model 2:

```
array[1..2] of var opt 1..1: arr;

constraint occurs(arr[1]) <-> false;
constraint occurs(arr[2]) <-> occurs(arr[2]);
constraint occurs(arr[2]);
constraint if arr[2] = 1 then arr[2] = arr[1] endif;

solve satisfy;
```

**Comment by Dekker1** [comment]
This message (which should only appear in Debug) would suggest that there is propagation on basic Boolean constraints that is not happening. The output of the model instances should be correct, but could maybe be improved.
