### ISSUE TITLE
seg fault with annotation inside expression

### ISSUE THREAD

**Issue by jnmonette** [MiniZinc/libminizinc#68]
The following piece of code produces a segmentation fault due to the second constraint. In contrast, the first constraint is compiled fine.

```
var 1..4: x;
var 1..4: y;

constraint max((x*y)::domain,x) = 4 ;
constraint ((x*y)::domain) + x = 4 ;

solve satisfy;
```

By the way, thanks for fixing all these bugs so fast. Great job!

**Comment by guidotack** [comment]
I already fixed this yesterday in 76833ab.
