### ISSUE TITLE
Using `-t` option with Chuffed kills the solver before statistics are printed

### ISSUE THREAD

**Issue by raphaelboudreault** [MiniZinc/libminizinc#692]
Relates to https://github.com/chuffed/chuffed/issues/85 and #523.

While I thought that MR https://github.com/chuffed/chuffed/pull/87 and https://github.com/chuffed/chuffed/pull/88 would solve this issue, it still happens on Windows 10 using MiniZinc 2.7.2. The flag `-t` is now passed correctly to Chuffed, but it seems like MiniZinc still kills Chuffed before it has the time to print anything. This can be seen using the flag -s, where Chuffed doesn't print any of its statistics when the timeout kicks in (when I'm pretty sure back in the days, it was doing so). Note that this behavior of missing output also happens when using Ctrl+C (only \*\*\*Interrupted\*\*\* is printed).

**Comment by Dekker1** [comment]
This seems like an issue in Chuffed, not in MiniZinc. Could you please recreate the issue there.

I just wanted to note that I cannot recreate the issue on macOS, but hopefully someone with Windows would be able to recreate it and help solve it.

**Comment by raphaelboudreault** [comment]
@Dekker1 Note that the behavior is correct when using fzn-chuffed alone (with option --time-out).
