### ISSUE TITLE
Order of constraints affect creating unexpected warning in simple program

### ISSUE THREAD

**Issue by sivik0104** [MiniZinc/libminizinc#696]
Running of this simple MZ program:
 
              set of int: DomainSet = 1..2;
              array[DomainSet] of bool: BoolArray = [false, true];
              array[DomainSet] of var 0..1: zero_one_array;
               
              constraint exists (i in DomainSet) (zero_one_array[i] in { 0 });
              constraint forall (i in DomainSet) (BoolArray[i] <-> zero_one_array[i] = 1);
 
throws 'array access out of bounds' warning, but it won't throw if you only exchange order of constraints in the source code

**Comment by Dekker1** [comment]
I'm unable to recreate the problem. On MiniZinc 2.7.4, whichever way around I put the constraints, I do not get any warnings.

**Comment by sivik0104** [comment]
Try with chuffed. Same with or-tools as well.
