### ISSUE TITLE
Different results between versions 2.6.4 and 2.7.4 for arithmetic-target

### ISSUE THREAD

**Issue by krzku** [MiniZinc/libminizinc#698]
Running arithmetic-target model.mzn with, for example, data file 814_with_1_2_4_6_6_7_8_9.json and version 2.7.4 gives objective=8131 (ortools, gecode, chuffed, JaCoP) while version 2.6.4 gave objectibve= 5 (ortools, chuffed and other values for gecode and JaCoP).

**Comment by cyderize** [comment]
It appears that this has already been fixed in the current `develop`, and the objective of 5 is again produced.
