### ISSUE TITLE
symdiff (over set variables)

### ISSUE THREAD

**Issue by pierfle** [MiniZinc/libminizinc#700]
Is there a magic incantation one has to make in order to get set variables to work?

Consider
`var set of 1..3: C;
var set of 1..3: D;
constraint C symdiff D = {2};
solve satisfy`:
Every combination of values for C and D is a solution (but this is incorrect), as the flattened version drops the constraint.

Now consider
`var set of 1..3: C;
var set of 1..3: D;
constraint card(C symdiff D) = 1;
solve satisfy;`:
Now the flattening aborts with an error.
But the equivalent 
`var set of 1..3: C;
var set of 1..3: D;
constraint card(C union D) - card(C intersect D) = 1;
solve satisfy;`
works fine, making me think no incantation is needed and only `symdiff` is broken.

**Comment by Dekker1** [comment]
It looks like internally the bounds of the sets are used to calculate initial bounds on the cardinality of the set. However, no bounds were provided for symdiff causing the issue

**Comment by pierfle** [comment]
The first error in my report above subsists in version 2.7.5.

**Comment by cyderize** [comment]
Yes it does appear that the first problem still persists. Using `include "nosets.mzn";` should give the correct behaviour as a workaround for now (but may not be very efficient for solvers which do have native set variables).

**Comment by Dekker1** [comment]
My apologies, I had missed the first issue entirely. Some optimisations trying to propagate set literal values were overriding the function values by mistake. I've pushed a fix for this problem.
