### ISSUE TITLE
coin-bc solver (bundled with IDE)  outputs unformatted statistics to stderr

### ISSUE THREAD

**Issue by PerMildner** [MiniZinc/libminizinc#705]
Statistics output from the solver is supposed to be output to the **standard output** stream, in a well defined format.
In contrast, error and warning output is supposed to be output the **standard error** output stream.

The statistics output is [described](https://www.minizinc.org/doc-2.7.5/en/fzn-spec.html#statistics-output) as:

> FlatZinc solvers can output statistics in a standard format so that it can be read by scripts, for example, in order to run experiments and automatically aggregate the results. Statistics should be printed to the **standard output** stream in the form of FlatZinc comments that follow a specific format.

The error output is [described](https://www.minizinc.org/doc-2.7.5/en/fzn-spec.html#error-and-warning-output) as:

> Errors and warnings must be output to the standard error stream. When an error occurs, the implementation should exit with a non-zero exit code, signaling failure.

However, the bundled coin-bc solver also emits some unformatted non-warnings to standard error:

```
% '/Applications/MiniZincIDE.app/Contents/Resources/minizinc' --version
MiniZinc to FlatZinc converter, version 2.7.5, build 891740483
Copyright (C) 2014-2023 Monash University, NICTA, Data61
% '/Applications/MiniZincIDE.app/Contents/Resources/minizinc' --solver org.minizinc.mip.coin-bc --statistics shopping01.mzn data/shopping0.dzn 1> /dev/null
45 POSTs [ 45,0,0,0,0,0,0,0,0,0, ], LINEQ [ 0,0,0,0,0,0,0,0,0, ], 5 / 5 vars, 5 cliques, 9 / 9 / 9 NSubIntv m/a/m, 0 / 0 / 0 SubIntvSize m/a/m, 0+5(5) clq eq_encoded  ... 
% 
```
This makes it hard to write solver agnostic scripting, since it is no longer possible to assume that any output to standard error represents a problem.

**Comment by cyderize** [comment]
The spec only guarantees that errors and warnings will go to standard error, and does not guarantee that other logging or statistic-like information will not go to standard error, so it's probably never actually safe to assume that all output to standard error represents a problem.

However, it does seem that in this case the extra stderr output is actually output by the MiniZinc compiler when compilation statistics are enabled. It should probably instead be output when run in verbose mode, or made into proper statistics as you have suggested.

**Comment by PerMildner** [comment]
Yes, unparseable (logging, in this case) output should not be emitted unless explicitly requested.

**Comment by cyderize** [comment]
Depending on what kind of things you're trying to look for, you may also want to have a look at the [`--json-stream` mode](https://www.minizinc.org/doc-2.7.5/en/json-stream.html), which saves you from having to look at stderr at all in most cases of automation since compilation errors and solver status get output as JSON objects to stdout.
