### ISSUE TITLE
2.7.5: MiniZinc incorrectly detects model inconsistency

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#709]
I observed an issue with a solution to the `connect_0018` instance from the 2021 MiniZinc challenge.

[`connect_bugreport.zip`](https://github.com/MiniZinc/libminizinc/files/11781073/connect_bugreport.zip) contains everything needed to reproduce the issue, namely the `connect_0018` instance and two files with assignments to model variables which differ only slightly:

```
diff satisfiable.mzn unsatisfiable.mzn

27c27
< %constraint nMdl_12__Z = 6015;
---
> constraint nMdl_12__Z = 6015;
```

(So `satisfiable.mzn` does not constrain `nMdl_12__Z`.)

Here's what we get when we apply `minizinc` to these problems:

```
minizinc -D mzn_ignore_symmetry_breaking_constraints=true -D mzn_ignore_redundant_constraints=true --output-mode dzn --output-objective unsatisfiable.mzn

...
Warning: model inconsistency detected
=====UNSATISFIABLE=====


minizinc -D mzn_ignore_symmetry_breaking_constraints=true -D mzn_ignore_redundant_constraints=true --output-mode dzn --output-objective satisfiable.mzn

...
_objective = 1144081;
----------
==========
```

So it seems that the assignment `nMdl_12__Z = 6015` is wrong.

However, when grepping for the value of `nMdl_12__Z` in the solution to `satisfiable.mzn`, we get a surprising result:

```
minizinc -D mzn_ignore_symmetry_breaking_constraints=true -D mzn_ignore_redundant_constraints=true --output-mode dzn --output-objective satisfiable.mzn | grep nMdl_12__Z


nMdl_12__Z = 6015;
```

Voila.

I am reporting this issue for MiniZinc 2.7.5 but it reproduces with older versions, too. (2.5.5 was the oldest I tried.)

**Comment by cyderize** [comment]
This seems to be due to the way this model uses the unsafe `lb`/`ub` functions.

When run with a solution, the model gets tight variable bounds, and so some `if-then-else`s which look at `lb`/`ub` of variables end up in different branches which happen to trigger unsatisfiability.

As this is not a compiler bug, I'll close this. However, we will look into that model and see if it can be fixed so that it behaves correctly.
