### ISSUE TITLE
Output sections not working as expected

### ISSUE THREAD

**Issue by CervEdin** [MiniZinc/libminizinc#712]
My understand from reading `--help`

```
  --only-sections <section_1,...section_n>
    Enable only the given comma-separated output sections.
  --not-sections <section_1,...section_n>
    Disable the given comma-separated output sections.
```

and [the section on annotations](https://www.minizinc.org/doc-2.6.4/en/lib-stdlib-annotations.html#mzn-stdlib-annotations-general-mzn-output-section)

one should be able to annotate `output` like this

`model.mzn`
```
output ["Hello\n"] :: mzn_output_section("hello");
output ["World\n"] :: mzn_output_section("world");
```

and then compile and run the model like this

```sh
echo "Only hello" >&2 && minizinc --solver chuffed --only-sections hello model.mzn
echo "Not hello" >&2 && minizinc --solver chuffed --not-sections hello model.mzn
```

but neither option appears to work as expected.

Am I doing something wrong or is this a bug?

**Comment by cyderize** [comment]
Try this:
```
output :: "hello" ["Hello\n"];
output :: "world" ["World\n"];
```

I guess this feature is not really documented as it was mainly for use with the IDE - we'll have a look at adding documentation.

**Comment by CervEdin** [comment]
That worked like expected! I thought I had tried that but I guess I didn't 😶
Thank you for helping me understand!
