### ISSUE TITLE
Is code documentation wanted?

### ISSUE THREAD

**Issue by jbroeksteeg0** [MiniZinc/libminizinc#718]
I've been trying to familiarise myself with the codebase and noticed that there's next to no documentation, is this intended or can I add some in a PR as I explore?

**Comment by Dekker1** [comment]
We are very happy with contributions, and I would be happy to review a PR that adds new comments. Above all, it would be important that the comments are concise, helpful, and correct. I would want to avoid comments that describe what the C++ means or does, and instead focus on adding comments about the flow in C++ definitions and descriptions of declarations (with a focus on expected conditions before or after).

If you need any help, then please feel free to contact me directly.
