### ISSUE TITLE
Using -c option with minizinc command line results in an error

### ISSUE THREAD

**Issue by ravindrarao** [MiniZinc/libminizinc#724]
>minizinc -c p.mzn

   I/O error: cannot open fzn output file. :   No such file or directory.
MiniZinc has encountered an internal error. This is a bug.
Please file a bug report using the MiniZinc bug tracker.
The internal error message was:
"not !fHard:   I/O error: cannot open fzn output file. : No such file or directory"

>minizinc --version
MiniZinc to FlatZinc converter, version 2.7.6, build 905165378
Copyright (C) 2014-2023 Monash University, NICTA, Data61

Platform: Microsoft Windows [Version 10.0.22621.2134]

**Comment by Dekker1** [comment]
It seems pretty clear that you are triggering an error here: https://github.com/MiniZinc/libminizinc/blob/master/lib/flattener.cpp#L954

Although it does seems that the error should be handled better and not be reported as a internal error, it does not seem to be a problem in MiniZinc itself. It is just using the normal C++ `ofstream` to write content to a file, and the error occurs when it tries to open the file.

The command line flag `-c` will by default use a name (and location) based on the MiniZinc model file. In your example, when given `p.mzn` it will try and write to `p.fzn` (both in the current directory). Are you sure that you have writing access in the current directory? Are you maybe working in a folder that is already moved to trash/bin? A common Windows one would be that you might be working in a ZIP file (which does not allow you to write directly).

To test, it might be good to try and write the FlatZinc file to a location that you know that you can write to. You can do to by providing the `--fzn` flag. For example `minizinc -c --fzn ~/Documents/flat_p.fzn p.mzn` (sorry for the unix path in the example, I'm not that familiar with Windows these days).
