### ISSUE TITLE
could not replace binary operator by call to count_eq

### ISSUE THREAD

**Issue by jakkanen** [MiniZinc/libminizinc#728]
minizinc 2.7.6
The following snippet causes minizinc to suggest I file a radar

```
enum color = {red, green, blue};
set of int: shirt_ids = 1..5;
array[shirt_ids] of color: shirts = [red, green, blue, red, green];
var set of shirt_ids: wanted;
constraint forall (c in color)(count(i in wanted)(shirts[i] = c) = 1);
solve satisfy;
```

results in:
```
$ minizinc  minibug.mzn 
MiniZinc has encountered an internal error. This is a bug.
Please file a bug report using the MiniZinc bug tracker.
The internal error message was: 
"could not replace binary operator by call to count_eq"
```

**Comment by Dekker1** [comment]
It seems the function matching fails, because the comprehension will result in a `array of var opt int` type, and we currently don't have a definition of `count_eq` with an argument of this type.

We should either add a definition for this, or disable the rewriting in this case.
