### ISSUE TITLE
Automatic detection of SCIP library file by MiniZinc

### ISSUE THREAD

**Issue by raphaelboudreault** [MiniZinc/libminizinc#737]
Hello!
I am currently trying to use SCIP (version 8.0.3) with MiniZinc (version 2.7.6), and having trouble understanding the default search paths on Linux (WSL Ubuntu 22.04). I first downloaded the SCIP Optimization Suite from the website in a custom location and have the `bin`, `include`, and `lib` folders. From what I understand, the path needed by MiniZinc is the one to the file `lib\libscip.so`. By using the command line option `--scip-dll`, I am successfully able to give the absolute path to the file and MiniZinc runs without any problem. However, I am trying to find a systematic way to install and use SCIP with MiniZinc _without_ needing the command line option. MiniZinc only tries three different locations : `libscip`, `/home/linuxbrew/.linuxbrew/lib/libscip.so`, `/opt/homebrew/lib/libscip.dylib`. How do I get the first option to work? Where do I need to put the symlink or what folder do I need to add to the PATH variable? Nothing I tried worked, unfortunately.

Also, is the documentation [here](https://www.minizinc.org/doc-2.7.6/en/installation_detailed_linux.html#scip) up to date? Does compiling MiniZinc _after_ downloading the binaries of SCIP makes a difference?

Thank you.

**Comment by cyderize** [comment]
That documentation is no longer up to date - MiniZinc no longer needs SCIP to be available when building to enable the plugin, so it makes no difference whether you compile MiniZinc before or after. We'll update that for the next release.

The recommended way to have SCIP be automatically detected (other than setting it up in IDE graphically) would be to create or modify your `Preferences.json` file as documented [here](https://www.minizinc.org/doc-2.7.6/en/command_line.html?highlight=preferences%20json#user-configuration-files).

You would add something like this:

```json
{
    "solverDefaults": [
        [
            "org.minizinc.mip.scip",
            "--scip-dll",
            "/path/to/libscip.so"
        ]
    ]
}
```

It should also be possible to add SCIP's `lib` directory to the `LD_LIBRARY_PATH` variable and have it found that way as well on Linux.

**Comment by raphaelboudreault** [comment]
Awesome! Thank you for your prompt response. I have been able to make it work by using the `LD_LIBRARY_PATH` variable.
