### ISSUE TITLE
configure looks for chuffed but chuffed-0.13.0 doesn't install any cmake files

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#743]
```
CMake Warning at CMakeLists.txt:40 (find_package):
  By not providing "Findchuffed.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "chuffed", but
  CMake did not find one.

  Could not find a package configuration file provided by "chuffed" with any
  of the following names:

    chuffedConfig.cmake
    chuffed-config.cmake

  Add the installation prefix of "chuffed" to CMAKE_PREFIX_PATH or set
  "chuffed_DIR" to a directory containing one of the above files.  If
  "chuffed" provides a separate development package or SDK, be sure it has
  been installed.
```

Version: 2.7.6
FreeBSD 13.2

**Comment by cyderize** [comment]
I think Chuffed 0.13.0 does install CMake files. If you set `-DCMAKE_PREFIX_PATH="<CHUFFED_INSTALL_DIR>/<lib or lib64 depending on OS>/cmake/chuffed"` it should find it. We currently use this for the [WebAssembly](https://github.com/MiniZinc/minizinc-js/actions/runs/6714271647/job/18247242240#step:9:14) build of MiniZinc.

But actually the builtin Chuffed feature probably should be left off for the FreeBSD packages, so you can just ignore that message. We only use them for the WebAssembly build and some other cases where it is desirable to have all the solvers usable in one binary.

**Comment by yurivict** [comment]
Ok, thanks for the explanation.
