### ISSUE TITLE
Build fails to find Highs.h and the it also can't find libhighs.so

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#744]
```
In file included from /usr/ports/math/minizinc/work/libminizinc-2.7.6/solvers/MIP/MIP_highs_solverfactory.cpp:13:
/usr/ports/math/minizinc/work/libminizinc-2.7.6/include/minizinc/solvers/MIP/MIP_highs_wrap.hh:16:10: fatal error: 'Highs.h' file not found
#include <Highs.h>
         ^~~~~~~~~
1 error generated.
```

Highs.h is installed at /usr/local/include/highs/Highs.h by coin-or-highs-1.6.0

Version: 2.7.6
FreeBSD 13.2

**Comment by Dekker1** [comment]
This is an error in newer versions of Highs: https://github.com/ERGO-Code/HiGHS/issues/1308

A workaround has been added in the current develop versions of MiniZinc (and the releases will now uses `dlopen` to load the libraries rather than including them in the executable)

**Comment by cyderize** [comment]
Just a note, if you build HiGHS with `-DFAST_BUILD=OFF` then it should actually work as well.
