### ISSUE TITLE
minizinc segfault on Darwin

### ISSUE THREAD

**Issue by d10genes** [MiniZinc/libminizinc#75]
I downloaded and unpacked the [2.0.10 release for Darwin](https://github.com/MiniZinc/libminizinc/releases/download/2.0.10/minizinc-2.0.10-Darwin.tar.gz), and tried

    $ minizinc-2.0.10/bin/minizinc --help
    [1]    94310 segmentation fault  minizinc-2.0.10/bin/minizinc --help

I assume this isn't expected behavior.

**Comment by guidotack** [comment]
Thanks, that was a problem in the binary packages. I've updated the packages for all platforms.
