### ISSUE TITLE
Outdated documentation for Additional Gecode search annotations 

### ISSUE THREAD

**Issue by Ditta1337** [MiniZinc/libminizinc#763]
Domumentation for [additional Geode searching annotations](https://www.minizinc.org/doc-2.8.1/en/lib-gecode-annotations.html) `activity_x` is outdated.

Example:
`Error: type error: undefined identifier activity_max`

I believe it `action_x` now.

**Comment by Dekker1** [comment]
Yes, the current documentation generation was using the internal version of the Gecode definitions rather than external shipped binary. They are supposed to match, but it seems we are out of date with these annotations. I've updated the documentation generation to use the external Gecode instead.
