### ISSUE TITLE
2.8.1 flatzinc error for Choco

### ISSUE THREAD

**Issue by IgnaceBleukx** [MiniZinc/libminizinc#764]
Dear,

I'm using Choco v 4.10.14 through the MiniZinc interface on MiniZinc v.2.8.1 and I am encountering an error when trying to compile any model.

```
var bool: x;
var bool: y;

constraint x /\ y;
```
**Output:**
```
[flatzinc_builtins:436.78-107](err:/snap/minizinc/896/share/minizinc/std/flatzinc_builtins.mzn?line=436&column=78):
MiniZinc: type error: Type array[int,int] of var float is not allowed in as a FlatZinc builtin argument, arrays must be one dimensional
[flatzinc_builtins:442.76-110](err:/snap/minizinc/896/share/minizinc/std/flatzinc_builtins.mzn?line=442&column=76):
MiniZinc: type error: Type array[int,int] of var set of int is not allowed in as a FlatZinc builtin argument, arrays must be one dimensional
Process finished with non-zero exit code 1.
```

I also opened this issue [in the Choco-solver GitHub repository](https://github.com/chocoteam/choco-solver/issues/1074) but as the bug does not occur when using Minizinc v2.8.0 it is probably more suited to report here.

Kind regards,
Ignace

**Comment by Dekker1** [comment]
Please see the comment on the Choco issue
