### ISSUE TITLE
2.8.2: Gecode::FlatZinc::AST::TypeError

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#768]
rotating-workforce-scheduling:

```
> minizinc rotating-workforce-scheduling.mzn rws-instance-e-25-s-7.dzn
terminate called after throwing an instance of 'Gecode::FlatZinc::AST::TypeError'
=====ERROR=====
```

opt-cryptanalysis:

```
> minizinc mznc2017_aes_opt.mzn r1.dzn 
terminate called after throwing an instance of 'Gecode::FlatZinc::AST::TypeError'
=====ERROR=====
```

**Comment by Dekker1** [comment]
This seems like it would be a problem in the Gecode code base. We will further diagnose and fix the problem where appropriate

**Comment by informarte** [comment]
@guidotack, @cyderize, I tested build1150712751 and found that the issue with opt-cryptanalysis is resolved. However, the issue with rotating-workforce-scheduling has not yet been resolved. MiniZinc 2.7.6 produces this solve goal:

```
solve :: seq_search([bool_search(X_INTRODUCED_717_,input_order,indomain_max,complete), ...
```

while MiniZinc 2.8.2 produces:

```
solve :: seq_search([bool_search([int_eq(X_INTRODUCED_101_,4),int_eq(X_INTRODUCED_108_,4), ...
```

**Comment by cyderize** [comment]
Thanks @informarte - these turned out to be two separate bugs - hopefully they're both fixed now
