### ISSUE TITLE
ast.hh:198: T* MiniZinc::Expression::cast() [with T = MiniZinc::VarDecl]: Assertion `isa<T>()' failed.

### ISSUE THREAD

**Issue by einarjohan** [MiniZinc/libminizinc#77]
When running the attached model with -Dmeh_par=9740, the following assertion is triggered:

```
libminizinc/include/minizinc/ast.hh:198: 
T* MiniZinc::Expression::cast() [with T = MiniZinc::VarDecl]: Assertion `isa<T>()' failed.
```

This was originally found in a quite large and complex model, that I've since tried to trim down to as small an example as I could. Sadly the length of variable-names seems to have an effect on this issue, thus it was not trivial to make a trivial test. Adding or removing a few variables will of course imply that the relevant -D-parameter may need a slight adjustment.

(Files had to be renamed to .txt for GitHub to allow them).
[huge_array.mzn.txt](https://github.com/MiniZinc/libminizinc/files/94644/huge_array.mzn.txt)
[model.mzn.txt](https://github.com/MiniZinc/libminizinc/files/94645/model.mzn.txt)

**Comment by guidotack** [comment]
Thanks for the bug report. This was a garbage collection problem, I've fixed it in the develop branch. If you want to apply the fix to your working copy and you're not up to date with develop, just add a line `GCLock lock;` in flatten.cpp, right before the definition of `class OV1 : public ItemVisitor`.
