### ISSUE TITLE
Missing bounds analysis in generator expression leads to segfault

### ISSUE THREAD

**Issue by wldhx** [MiniZinc/libminizinc#775]
Hi, here's a repro:

```
int: MAXTIME = 24*2;
set of int: TIME = 0..MAXTIME;

% var TIME: x = MAXTIME + 3; % correctly rejected
list of var TIME: downtime_dur = [ 24*d + 3 | d in 1..2 ];
```

The first `var` declaration correctly gets rejected as out of bounds. The second generator fails with

```
MiniZinc error: Memory violation detected (segmentation fault).
This is a bug. Please file a bug report using the MiniZinc bug tracker.
```

**Comment by Dekker1** [comment]
I'm unable to reproduce the problem using the latest release. Could you make sure that you are running MiniZinc version 2.8.2?

**Comment by wldhx** [comment]
That was 2.8.0, indeed doesn't reproduce (fails with model inconsistency warning => unsatisfiable) on 2.7.4 and 2.8.2.

Apologies, I thought I had 2.8.2 then :)
