### ISSUE TITLE
Crash in SCIP readline

### ISSUE THREAD

**Issue by snicolai-blog** [MiniZinc/libminizinc#783]
Using the IDE and this model with SCIP 8.1.0 installed from home-brew on MacOS, I get the following crash.

[taxes.mzn.txt](https://github.com/MiniZinc/libminizinc/files/13933867/taxes.mzn.txt)

[minizinc_crash.txt](https://github.com/MiniZinc/libminizinc/files/13933864/minizinc_crash.txt)

**Comment by Dekker1** [comment]
I'm unable to recreate this on my Mac M1 machine, newest MacOS, using the homebrew version of SCIP and MiniZinc 2.8.2.

Can you give us more details on your environment?

**Comment by snicolai-blog** [comment]
M1Max MacBook Pro

I set the SCIP solver advanced options optimization level to -O2 (two pass compilation), it doesn't crash at -O1.

% scip --version
SCIP version 8.1.0 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: Soplex 6.0.4] [GitHash: 6129793871]
Copyright (c) 2002-2023 Zuse Institute Berlin (ZIB)

External libraries: 
  Readline 8.2         GNU library for command line editing (gnu.org/s/readline)
  Soplex 6.0.4         Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: 950b1658]
  CppAD 20180000.0     Algorithmic Differentiation of C++ algorithms developed by B. Bell (github.com/coin-or/CppAD)
  ZLIB 1.2.12          General purpose compression library by J. Gailly and M. Adler (zlib.net)
  GMP 6.3.0            GNU Multiple Precision Arithmetic Library developed by T. Granlund (gmplib.org)
  AMPL/MP 4e2d45c4     AMPL .nl file reader library (github.com/ampl/mp)
  PaPILO 2.1.3         parallel presolve for integer and linear optimization (github.com/scipopt/papilo)
  bliss 0.77           Computing Graph Automorphisms by T. Junttila and P. Kaski (users.aalto.fi/~tjunttil/bliss/)
  sassy 1.1            Symmetry preprocessor by Markus Anders (github.com/markusa4/sassy)
  Ipopt 3.14.13        Interior Point Optimizer developed by A. Waechter et.al. (github.com/coin-or/Ipopt)

Compiler: clang 15.0.0

Build options:
 ARCH=arm64
 OSTYPE=Darwin-23.0.0
 COMP=AppleClang 15.0.0.15000040
 BUILD=Release
 DEBUGSOL=OFF
 EXPRINT=cppad
 SYM=sbliss
 GMP=ON
 IPOPT=ON
 WORHP=OFF
 LPS=spx
 LPSCHECK=OFF
 NOBLKBUFMEM=OFF
 NOBLKMEM=OFF
 NOBUFMEM=OFF
 THREADSAFE=ON
 READLINE=ON
 SANITIZE_ADDRESS=OFF
 SANITIZE_MEMORY=OFF
 SANITIZE_UNDEFINED=OFF
 SANITIZE_THREAD=OFF
 SHARED=ON
 VERSION=8.1.0.0
 API_VERSION=104
 ZIMPL=OFF
 ZLIB=ON

**Comment by cyderize** [comment]
This seems to be a bug in the compiler with `-O2` when type aliases are used.

As a workaround for now, you can change the type alias to

```
set of float: dollar = 0.0 .. maxDollar;
```
