### ISSUE TITLE
useless sorting constraints

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#784]
The following are pretty useless, aren't they?
```
predicate strictly_decreasing(array [$X] of var bool: x)
predicate strictly_increasing(array [$X] of var bool: x)
```

**Comment by Dekker1** [comment]
Yes, it does not often make sense. I'll remove it from the documentation (since the integer version is clearer), the `fzn_*` definitions, and replace it with a simpler definition that issues a warning to the modeller should you call `strictly_increasing` on an array or length 3 or higher.
