### ISSUE TITLE
`network_flow[_cost]`: documentation issue + assertion idea

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#786]
Says the documentation:

> `balance`: the difference between input and output flow for each node.

which should be the other way around, output flow minus input flow.

Also, I suggest an assertion: the total balance should be zero, otherwise there is no solution, right?

**Comment by Dekker1** [comment]
Thank you for the suggestions

A fix for the `balance` description should soon be merged. I've also added a check for the sum of balance, if it is not zero, then the definition will now return `false` and output a warning.
