### ISSUE TITLE
internal error: missing builtin 'exists'

### ISSUE THREAD

**Issue by jarble** [MiniZinc/libminizinc#792]
I tried to run this model in the [MiniZinc playground](https://play.minizinc.dev/) using the Chuffed solver:
```
enum functions = {animal,dog};
type func = record(functions:funcs,int: input);
array[1..10] of var func:funcs;

function var bool:dog(int:t) =
(funcs:dog,input:t) in funcs;

var int:d1 = dog(1);

solve satisfy;

output [show(d1)];
```
But the solver shows this error message:

```
=====UNKNOWN=====
/usr/share/minizinc/std/stdlib/stdlib_array.mzn:266.3-32:
MiniZinc: evaluation error: internal error: missing builtin 'exists'
Process finished with non-zero exit code 1.
```

**Comment by cyderize** [comment]
As a workaround until this is fixed, you can pass the `funcs` array as an argument to your `dog` function:
```
function var bool:dog(array[int] of var func: fns, int:t) =
(funcs:dog,input:t) in fns;

var int:d1 = dog(funcs, 1);
```

**Comment by Dekker1** [comment]
The problem is resolved when you select the “edge” version of MiniZinc in the playground. The fix has not been included in any release yet, so the “latest” version does not yet include the fix.

**Comment by jarble** [comment]
@Dekker1  Now a different error appears when running this model using the COIN-BC solver:

`MiniZinc: flattening error: variable X_INTRODUCED_19_ needs finite bounds for linearisation. Or, use indicator constraints. Current domain is [[ [ -inf, 0 ] [ 1, 1 ] [ 2, inf ] ]]`

Is this another compiler bug?

**Comment by cyderize** [comment]
I think this is just a limitation of how linearisation works for MIP solvers like CBC.

Without any bounds for the `input` field of the record, it's not possible to turn `(funcs:dog,input:t) in funcs` into an integer variable which the solver can handle.

You can add bounds with 
```
type func = record(functions:funcs,-10..10: input);
```

which will fix the problem.
