### ISSUE TITLE
Getting an error when trying to use Gurobi 11.0.1 from AMPL bundle in Ubuntu

### ISSUE THREAD

**Issue by indrajitsg** [MiniZinc/libminizinc#797]
I downloaded the latest bundle from AMPL website containing Gurobi 11.0.1 along with all the other solvers. Created a "msc" file containing the following:
```
{
  "id": "com.gurobi",
  "name": "Gurobi11",
  "description": "Gurobi executable",
  "version": "11.0.1",
  "executable": "../../../../Downloads/ampl.linux-intel64/gurobi",
  "supportsFzn": false,
  "supportsNL": true
}
```
When I try to run: 
`./minizinc --solver Gurobi11 --gurobi-dll "../../../../Downloads/ampl.linux-intel64/libgurobi110.so" models/army.mzn`

I just get an error:
`====ERROR====`

What am I doing wrong? It works fine with CPLEX in the bundle.

Regards,

**Comment by indrajitsg** [comment]
Okay looks like the issue is with Gurobi not being able to solve that particular problem. Could be an issue with the NL file that gets generated out here. I was able to execute Gurobi on another model.

**Comment by Dekker1** [comment]
Sounds like this issue has already been resolved.

When using Gurobi or CPLEX, we would recommend the internal interfaces rather than the NL interface
