### ISSUE TITLE
Emptied domain

### ISSUE THREAD

**Issue by jnmonette** [MiniZinc/libminizinc#8]
The following model (trimmed down from the bacp model of the 2010 challenge) is incorrectly flattened by MiniZinc 2.0.1. In particular, the domain of neg_obj is wrongly computed.

    var 2..100: objective;
    var -100..-2 : neg_obj = -objective;
    solve minimize neg_obj;

result:

    var 2..100: objective:: output_var;
    var 1..0: neg_obj:: is_defined_var;
    constraint int_lin_eq([-1,-1],[objective,neg_obj],0):: defines_var(neg_obj);
    solve  minimize neg_obj;

Cheers,
JN

**Comment by guidotack** [comment]
Thanks, really no idea how that one wasn't caught by the tests!

**Comment by schutta** [comment]
Hi Guido,

If I want to change the geost definition, should I do in the master oder developing branch?

Cheers,
Andreas
________________________________________
