### ISSUE TITLE
minizinc 2.8.3 Memory violation detected (segmentation fault)

### ISSUE THREAD

**Issue by snicolai** [MiniZinc/libminizinc#806]
MacOS Sonoma 14.4.1 (23E224) on Apple Silicon (M1 Max)

Minizinc 2.8.3
```
% /Applications/MiniZincIDE.app/Contents/Resources/minizinc  -v                  
MiniZinc to FlatZinc converter, version 2.8.3, build 1160071927
Copyright (C) 2014-2024 Monash University, NICTA, Data61
```

```
% /Applications/MiniZincIDE.app/Contents/Resources/minizinc  -c $HOME/finplan2/minizinc/crash.mzn
MiniZinc error: Memory violation detected (segmentation fault).
This is a bug. Please file a bug report using the MiniZinc bug tracker.
```

[crash.mzn.txt](https://github.com/MiniZinc/libminizinc/files/14936259/crash.mzn.txt)

**Comment by cyderize** [comment]
While the crash itself is definitely a bug, the model actually has a type error in it - the function `dependentsInRange` should have the signature

```
function array[int] of bool: dependentsInRange(array[int] of date: dependentBirthdays, int: year, int: maxAge)
```

Which I think will fix the problem. The `$T`/`$$T` syntax is not really designed for users to use (yet), and is not documented (#616).
