### ISSUE TITLE
2d array slicing in comprehension fails, array of arrays not supported

### ISSUE THREAD

**Issue by CervEdin** [MiniZinc/libminizinc#807]
I thought I could assign a _slice_ of a 2d array in a list comprehension, but it seems to fail.

### [`playground.mzn`](https://play.minizinc.dev/#project=%7B%22files%22%3A%5B%7B%22name%22%3A%22Playground.mzn%22%2C%22contents%22%3A%22array%5Bint%2C%20int%5D%20of%20int%3A%20foos%20%3D%20%5B%7C%201%2C%200%20%7C%5D%3B%5Cn%5Cnarray%5Bint%5D%20of%20int%3A%20bar%20%3D%20%5B%5Cn%20%20r%5B1%5D%20%7C%20i%20in%20index_set_1of2(foos)%2C%20r%3Dfoos%5Bi%2C%20..%5D%5Cn%5D%3B%22%7D%5D%2C%22tab%22%3A0%2C%22solverId%22%3A%22org.minizinc.gecode_presolver%22%2C%22solverConfig%22%3A%7B%22enableTimeLimit%22%3Afalse%2C%22timeLimit%22%3A1%2C%22allSolutions%22%3Afalse%2C%22verboseCompilation%22%3Afalse%2C%22verboseSolving%22%3Afalse%2C%22compilerStatistics%22%3Afalse%2C%22solvingStatistics%22%3Afalse%2C%22outputTime%22%3Afalse%2C%22freeSearch%22%3Afalse%7D%2C%22minizincVersion%22%3A%22latest%22%7D)
```zinc
array[int, int] of int: foos = [| 1, 0 |];

array[int] of int: bar = [
  r[1] | i in index_set_1of2(foos), r=foos[i, ..]
];
```
```text
Playground.mzn:3.1-22
  in
variable declaration for 'bar'
  in
array comprehension expression
Playground.mzn:4.15-34
    with
i = 1
    with
r = <expression>
  in
array access
MiniZinc:
evaluation error: arrays of arrays not supported
Process finished with non-zero exit code 1.
```
Seen in _latest_.

**Comment by CervEdin** [comment]
This is fine
```zinc
array[int] of int: bar = [ foos[i, ..][1] | i in index_set_1of2(foos) ];
```
but not what I want 😞

**Comment by CervEdin** [comment]
What I would _really_ want is to be able to iterate over _rows_ in a _2d array_, like in other languages with comprehensions
```zinc
[ r[1] | r in foos where r[2] == 0 ]
```
but just being able to assign `r=ReallyLongTableNameTableThingy[i, ..]` would go along way

**Comment by CervEdin** [comment]
Apparently I can do
```zinc
array[int] of int: bar = [ r[1] | i in 1..1, r=[1,2] ];
```
so I'm guessing this is a bug?

**Comment by cyderize** [comment]
Yes it seems the slice is somehow not being type checked correctly.

As a workaround for now, this seems to work:
```
array[int] of int: bar = [
  r[1] | i in index_set_1of2(foos), r=array1d(foos[i, ..])
];
```
