### ISSUE TITLE
empty set as default value for optional set fails

### ISSUE THREAD

**Issue by CervEdin** [MiniZinc/libminizinc#809]
The following [model](https://play.minizinc.dev/#project=%7B%22files%22%3A%5B%7B%22name%22%3A%22Playground.mzn%22%2C%22contents%22%3A%22enum%20foo%20%3D%20%7BA%2CB%2CC%7D%3B%5Cnopt%20set%20of%20foo%3A%20bar%3B%5Cnset%20of%20foo%3A%20biz%20%3D%20bar%20default%20%7B%7D%3B%5Cnoutput%20show(biz)%22%7D%5D%2C%22tab%22%3A0%2C%22solverId%22%3A%22org.minizinc.gecode_presolver%22%2C%22solverConfig%22%3A%7B%22enableTimeLimit%22%3Afalse%2C%22timeLimit%22%3A1%2C%22allSolutions%22%3Afalse%2C%22verboseCompilation%22%3Afalse%2C%22verboseSolving%22%3Afalse%2C%22compilerStatistics%22%3Afalse%2C%22solvingStatistics%22%3Afalse%2C%22outputTime%22%3Afalse%2C%22freeSearch%22%3Afalse%7D%2C%22minizincVersion%22%3A%22latest%22%7D):
```zinc
enum foo = {A,B,C};
opt set of foo: bar;
set of foo: biz = bar default {};
output show(biz)
```

fails with
```text
MiniZinc: type error: ambiguous overloading on return type of function
```

**Comment by cyderize** [comment]
This is probably more to do with the `opt set` - these are currently not really supported (they happen to work sometimes by coincidence, but there seem to be many places where they don't).

We'll have a look at whether it's possible to make this work, or otherwise make the type checker give a proper error for opt sets.

**Comment by CervEdin** [comment]
Aha. Yeah, I've been a bit curious about why it was possible to have an `opt set` but not an `opt array[_]`.
I see int the [spec](https://www.minizinc.org/doc-2.8.3/en/spec.html#option-types) that option types may be
> Allowed Insts. The argument of an option type must be one of the base types bool, int or float.

Sounds like we're using something that's not officially supported, and working by accident.
Am I understand that correctly?

As a user, I would add that _option_ types that include _sets_, _arrays_ parameters etc. would be useful in the language as it allows for introducing parameters which are backwards compatible.
