### ISSUE TITLE
"Official" Debian package?

### ISSUE THREAD

**Issue by LebedevRI** [MiniZinc/libminizinc#836]
Would there be any interest, in addition to providing the existing "linux binary archive",
to also provide a debian package repository?

After running into inadequacies of the existing debian package,
i've took a stab at creating a package for minizinc+gecode+chuffed from scratch,
and honestly the results make me sad. On a simple-ish model,
it's already 30-40% faster than debian package:
<details>

```
$ time minizinc --solver gecode unreachable.entry.json.mzn
----------
real    0m1.406s
user    0m1.341s
sys     0m0.056s
$ time minizinc --solver gecode unreachable.entry.json.mzn
----------
real    0m1.434s
user    0m1.351s
sys     0m0.076s
$ time minizinc --solver chuffed unreachable.entry.json.mzn
----------
real    0m0.726s
user    0m0.686s
sys     0m0.040s
$ time minizinc --solver chuffed unreachable.entry.json.mzn
----------
real    0m0.725s
user    0m0.676s
sys     0m0.048s
```
```
$ time minizinc --solver gecode unreachable.entry.json.mzn
----------
real    0m0.939s
user    0m0.883s
sys     0m0.056s
$ time minizinc --solver gecode unreachable.entry.json.mzn
----------
real    0m0.941s
user    0m0.886s
sys     0m0.056s
$ time minizinc --solver gecode_presolver unreachable.entry.json.mzn
----------
real    0m0.925s
user    0m0.904s
sys     0m0.020s
$ time minizinc --solver gecode_presolver unreachable.entry.json.mzn
----------
real    0m0.911s
user    0m0.887s
sys     0m0.024s
$ time minizinc --solver chuffed unreachable.entry.json.mzn
----------
real    0m0.410s
user    0m0.382s
sys     0m0.028s
$ time minizinc --solver chuffed unreachable.entry.json.mzn
----------
real    0m0.405s
user    0m0.381s
sys     0m0.024s
```

</details>

**Comment by LebedevRI** [comment]
cc @kaol

**Comment by Dekker1** [comment]
We already provide a AppImage, Snap package, and a binary archive that is compatible with as many linux distributions as we can feasible make it. Each of these targets already works on the latest debian release to my knowledge. Just maintaining these targets has already proven a lot of work, so (speaking for myself) I would not like to add another linux target to that list.

The fix from the debian side also seems quite straightforward. From your previous issues it is clear that you are running a debug build of the MiniZinc compiler. If debian switches its build to a Release build, that would likely correspond to the ~40% slowdown.

**Comment by LebedevRI** [comment]
> We already provide a AppImage, Snap package, and a binary archive that is compatible with as many linux distributions as we can feasible make it. Each of these targets already works on the latest debian release to my knowledge. Just maintaining these targets has already proven a lot of work, so (speaking for myself) I would not like to add another linux target to that list.

> The fix from the debian side also seems quite straightforward. From your previous issues it is clear that you are running a debug build of the MiniZinc compiler. If debian switches its build to a Release build, that would likely correspond to the ~40% slowdown.

If only it were that simple :) Not exactly. That helps with only half of that slowdown,
i get another -16..-20% improvement from LTO and 2-stage PGO,
and i haven't finished dialing it to 11 yet :)

I would love debian to do the right thing, but that would require
active help from the current maintainer with no disagreements
on the road taken. I don't think that will happen. @kaol ?

**Comment by kaol** [comment]
If you have already sent a patch with the compile flags you'd like to see used I must have missed it and I'll have to ask you to send it again. If you haven't then I think it's unreasonable to begin with asking whether I'd do the "right thing".

If you're going to go for a binary outside of a distribution I don't see what benefit having a deb would give.

**Comment by kaol** [comment]
This really isn't the place to have this discussion, I invite you to take it to https://lists.debian.org/debian-science/

**Comment by LebedevRI** [comment]
Yeah that is beyond my current abilities.

**Comment by Dekker1** [comment]
It sounds to me like there is more than enough willingness to solve this issue on the Debian side. I’ll close this issue here.

**Comment by LebedevRI** [comment]
Hm, and current debian packages (minizinc+chuffed) is even 5 **times** slower, not 40%. That is kind-of funny.

**Comment by Dekker1** [comment]
I think you have found some good compilation improvements, and they are likely to be more impactful on longer runs of MiniZinc (and its solvers). It just seems all the more reason to me to get in contact with the Debian maintainers and help them understand what is currently going wrong.
