### ISSUE TITLE
stochastic minizinc

### ISSUE THREAD

**Issue by mastajvidi** [MiniZinc/libminizinc#84]
Hello,
I have two problem with my model in stochastic minizinc:
1. I can't declare my variables as a 2 dimensional array!!  
2. when using smzn2mzn , I see an error that some variables are not defined!!! can you help me set environment variable and other stuff to run it properly???

anyone can help me with these issues please? 

cheers,
Masoumeh

**Comment by mastajvidi** [comment]
I have tried translating stochastic model into the standard minizinc model (smzn2mzn) for stochastic job shop scheduling problem ( designed by Andrea) similar error appears: undefined identifier nbTask !!!
![untitled](https://cloud.githubusercontent.com/assets/16066569/13130644/bfad3c96-d639-11e5-8214-4fc026198f3c.png)

**Comment by hemmidavid** [comment]
Hi Masoumeh
There seems to be an issue with the smzn2mzn using dzn files. A workaround for that would simply be to hard-code the data into the mzn file. With the mzn and sdzn file you can then compile the stochastic model into the deterministic equivalent. 
It will probably take us a while to make a new release, as we are quite busy at the moment. 
 
Cheers, 
David

**Comment by mastajvidi** [comment]
Hi David,

Thanks for your email.

So how did you do that for me then?  (at summer school!)
did you manually change my code or it was possible to use smzn2mzn in your
laptop ?
BTW, now I switched to Minizinc anyway :)

Thanks a lot,
Masoumeh

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
