### ISSUE TITLE
Index set mismatch in comparisson of empty mutlideminsional arrays

### ISSUE THREAD

**Issue by CervEdin** [MiniZinc/libminizinc#844]
It's possible to get index set mismatch in empty milt-dimensional arrays.

See the following example

```zinc
set of int: rows = 1..1;
set of int: cols = 1..0;
array[rows, cols] of var int: X;
array[int,  int ] of par int: x = [||];
% array[rows,  cols ] of par int: x = [| 1: |]; % Not OK
% array[rows,  cols ] of par int: x = [||]; % Not OK

constraint array1d(X) == array1d(x); % OK
constraint          X == x         ; % Not OK
```

It's a big of a strange behavior to get such a mismatch when the arrays are empty.
But I'm a bit unsure of what is the desired behavior here.

Is it wrong to specify a non-empty index set for the 1st dimension but an empty set for the second?
Probably not and I imagine changing this behavior would be a very significant and breaking change to existing models.

If this was just a model file, I would coerce `x` using `array2d` but this approach doesn't work when `x` is assign using a data file.
And specifying the index-set of the first dimension in the data file doesn't seem to work.

As a work-around, I can coerce both arrays using `array1d` but that defeats some of the purpose of the equality check (checking the equality of index-sets and array dimensions).

I would expect either of the following in this situation:
- Be able to specify the index-set in the declaration of `x` and have the parser do the appropriate coercion.
- Skip the equality check of index-sets if any of the index-sets in either multi-dimensional array if both contain an index-set that is empty (both arrays are empty in at least one dimension).

I think I prefer the first, but the second might be easier to implement.

**Comment by Dekker1** [comment]
We discussed this and `array[rows, cols] of int: x = [||]; ` and `array[rows, cols] of int: x = [];` should both be allowed. There was already a coercion in place, but it assumed that the first index would be empty. A fix should be merged shortly.
