### ISSUE TITLE
-a to print all CBC solutions

### ISSUE THREAD

**Issue by skosch** [MiniZinc/libminizinc#85]
(as per my mention of this in #83)

`mzn-cbc` currently doesn't have an `-a` option that would print new feasible solutions as soon as CBC finds them.

[John Forrest's answer](http://list.coin-or.org/pipermail/cbc/2015-October/001821.html) to @glebbelov's question from October,* in conjunction with the `solution` and `heuristicSolution` events documented in `Cbc/src/CbcEventHandler.hpp`, suggest that this should be possible (if not trivial).

For those working on very small prototypes at technically-speaking-commercial projects, CBC is the only affordable option, and not being able to monitor the search progress at all is frustrating, so this would be a valuable feature! I'm happy to help with this, but not sure where to start.

\* sorry Gleb ... it's the first thing that comes up on Google :p

**Comment by glebbelov** [comment]
Yes but 2 days ago the cbc mailing list reported a case where postprocessing takes 4x longer than solving and in a sol callback postpro has to be done every time. Let me try anyway

**Comment by skosch** [comment]
For my use case at least it'd be perfectly sufficient to simply log the objective value, actually, and only print the entire post-pro'd data at the end (optimality or Ctrl-C).

Then again, that may go against what users expect `-a` to accomplish. Maybe `-a` for everything and `-a --bounds-only` to only log incumbents and duals?

**Comment by glebbelov** [comment]
Option -v already does that, printing logs for flattening and solving on stderr while MiniZinc solution goes to stdout. -s prints additionally some solution stats like time/nodes. --cbcFlags gives you full control over the linked cbc code. Finally, Ctrl-C usually stops cbc code normally returning the current solution, at least on Linux.

I need to put this into README as people not always read --help. Btw the last cbc revision 2265 does not link for me, so dont pull until a fix

**Comment by skosch** [comment]
Welp, that's a good point ... and to think I was already running with `-v` the entire time but not paying attention :) I suppose I'm looking for something more machine-readable than what CBC spits out. I'll take another look at whether I can tweak those CBC arguments to my liking and report back.

**Comment by glebbelov** [comment]
Implemented -a to print intermediate solutions except those from feas. pump. Thanks to John Forrest.

**Comment by skosch** [comment]
Thanks @glebbelov, much appreciated!
