### ISSUE TITLE
Issue with placement of where clause in list comprehensions, etc.

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#854]
Consider this program:

```
array[int, int] of int: a = [| 1, 2, 3,
                             | 4, 5, 6,
                             | 7, 8, 9 |];
                             

int: s = sum(i in index_set_1of2(a) where i > 1, j in index_set_2of2(a))(a[i, j]);

int: t = sum(i in index_set_1of2(a), j in index_set_2of2(a) where i > 1)(a[i, j]);

output ["s = ", show(s), ", ", "t = ", show(t)];
```

The output is:

```
s = 45, t = 39
----------
```

So, in the definition of `s`, the `where` clause is ignored.

According to the definition of `<generator-exp>` given by the MiniZinc handbook, the definition of `s` should not parse because `where` is only allowed in the end, after all the generators.

When fixing this problem, please consider changing the grammar to allow for `where` clauses everywhere; this could potentially reduce compilation time, namely when many generators providing many elements each are used and there are complex filters which evaluate only a part of the resulting tuple.

**Comment by Dekker1** [comment]
It seems you are running into a bug that was present in MiniZinc 2.8.6, but that was then quickly resolved in 2.8.7.

You can test your fragment with the latest MiniZinc release: [playground](https://play.minizinc.dev/#project=%7B%22files%22%3A%5B%7B%22name%22%3A%22Playground.mzn%22%2C%22contents%22%3A%22array%5Bint%2C%20int%5D%20of%20int%3A%20a%20%3D%20%5B%7C%201%2C%202%2C%203%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%204%2C%205%2C%206%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%207%2C%208%2C%209%20%7C%5D%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%5Cnint%3A%20s%20%3D%20sum(i%20in%20index_set_1of2(a)%20where%20i%20%3E%201%2C%20j%20in%20index_set_2of2(a))(a%5Bi%2C%20j%5D)%3B%5Cn%5Cnint%3A%20t%20%3D%20sum(i%20in%20index_set_1of2(a)%2C%20j%20in%20index_set_2of2(a)%20where%20i%20%3E%201)(a%5Bi%2C%20j%5D)%3B%5Cn%5Cnoutput%20%5B%5C%22s%20%3D%20%5C%22%2C%20show(s)%2C%20%5C%22%2C%20%5C%22%2C%20%5C%22t%20%3D%20%5C%22%2C%20show(t)%2C%20%5C%22%5C%5Cn%5C%22%5D%3B%22%7D%5D%2C%22tab%22%3A0%2C%22solverId%22%3A%22org.minizinc.gecode_presolver%22%2C%22solverConfig%22%3A%7B%22enableTimeLimit%22%3Afalse%2C%22timeLimit%22%3A1%2C%22allSolutions%22%3Afalse%2C%22verboseCompilation%22%3Afalse%2C%22verboseSolving%22%3Afalse%2C%22compilerStatistics%22%3Afalse%2C%22solvingStatistics%22%3Afalse%2C%22outputTime%22%3Afalse%2C%22freeSearch%22%3Afalse%7D%2C%22minizincVersion%22%3A%22latest%22%7D)

It will output:
```
s = 39, t = 39
----------
```

We actually do allow the presence of where clauses anywhere in the sequence of generators, and actively move them to the front to minimize the number of iterations when we can.
