### ISSUE TITLE
mzn2fzn-2.0.12 segfaults on mqueens instances

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#92]
mzn2fzn-2.0.12 segfaults on all mqueens instances from the minizinc-benchmarks repository, for example:

    mzn2fzn mqueens2.mzn n11.dzn
    Segmentation fault

This happens on x86_64 Linux, I have not tried other systems.

Versions 2.0.10 and 2.0.4 work fine.

**Comment by guidotack** [comment]
Thanks for the report.  This bug has been fixed, the patch will be part of the upcoming 2.0.13 release.
