### ISSUE TITLE
minizinc.org certificate is considered insecure by browsers

### ISSUE THREAD

**Issue by Zero3** [MiniZinc/libminizinc#95]
The certificate used for HTTPS on https://www.minizinc.org/ is considered insecure by major browsers because it expires in 2017 and uses SHA1. The site is thus served with different kinds of warnings in browsers because of its false sense of security.

I suggest that you replace the certificate. Your CA has deprecation guidelines here: https://cs.auscert.org.au/news/deprecation-of-sha1-certificates. The Let's Encrypt project is an alternative worth considering too: https://letsencrypt.org/.

**Comment by guidotack** [comment]
Fixed.
