### ISSUE TITLE
feature request: floored division and modulus

### ISSUE THREAD

**Issue by guidotack** [MiniZinc/libminizinc#97]
_From @matsc-at-sics-se on April 2, 2016 7:5_

MiniZinc provides div/2 and mod/2 for truncated division (towards zero) and its corresponding remainder operation.  In ISO Prolog, div/2 and mod/2 stand for floored division (towards the nearest smaller integer) and its corresponding remainder operation, aka. modulus.  So the MiniZinc naming is a bit unfortunate, as is the lack of operators for floored division and modulus.  I have an application that relies heavily on modulo arithmetic and so really needs genuine modulus. Consider this a feature request. Illustrating example:

```
solve satisfy;
output [show(-5 div 3), " ", show(-5 mod 3), "\n"];
```

and output:

```
-1 -2
```

With floored div and mod, it would output:

```
-2 1
```

_Copied from original issue: MiniZinc/MiniZincIDE#14_

**Comment by guidotack** [comment]
We had a lot of discussion about floored div vs truncated div and decided to go with the definition in C and Java instead of Prolog (just for even more context, Python 2 also uses floored division while Python 3 has two operators (// for floored vs. / for floating point).

You can define floored division directly in MiniZinc if you need it.  I guess it would make sense to add these to the standard library (so that solvers can override them if they have native versions).

    function int: floor_div(int: x, int: y) = floor(x/y);
    
    function int: floor_mod(int: x, int: y) = x - y*floor(x/y);
    
    function array[int] of var int: floor_divmod_t(var int: x, var int: y) ::promise_total =
      let {
        int: minq = max(abs(ub(x)),abs(lb(x)));
        var -minq..minq: q;
        var 0..ub(y)-1: r;
        constraint y*q + r = x;
        constraint abs(r) < abs(y);
        constraint y < 0 <-> r < 0;
      } in [q,r];
    
    function array[int] of var int: floor_divmod_mt(var int: x, var int: y) :: promise_total =
      let {
        var ((dom(y) diff {0}) union {1}): yy = if y=0 then 1 else y endif;
      } in floor_divmod_t(x,yy);
    
    function var int: floor_div(var int: x, var int: y) =
      if mzn_in_root_context(y) \/ not (0 in dom(y)) then floor_divmod_t(x,y)[1] else
      let { constraint y != 0 } in floor_divmod_mt(x,y)[1] endif;
    
    function var int: floor_mod(var int: x, var int: y) =
      if mzn_in_root_context(y) \/ not (0 in dom(y)) then floor_divmod_mt(x,y)[2] else
      let { constraint y != 0 } in floor_divmod_mt(x,y)[2] endif;

**Comment by Dekker1** [comment]
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.
